### ISSUE TITLE
Chips with US flag oversized

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#130]
## Summary

Small issue, only on Safari desktop from what I've seen, but any chip using the US flag on the Details panel seems to be oversize, placing "United" and "States" on different lines. Doesn't seem to be a length issue, since it doesn't happen with United Arab Emirates, for example.

![Screen Shot 2020-11-08 at 9 38 31 AM (2)](https://user-images.githubusercontent.com/52076788/98467961-415f8980-21a6-11eb-942b-4b5e28da7a7b.png)

### Filters indicator dot

I think this may be related to the [squished dot](https://user-images.githubusercontent.com/52076788/98261442-7b385200-1f52-11eb-9b7f-c30025c2a425.png) problem (more in https://github.com/Language-Mapping/language-map/pull/127#issuecomment-722487052) . will try to fix in one go.

### Vatican City flag missing
Totally different problem but might as well lump it in: 

![image](https://user-images.githubusercontent.com/4974087/98483681-9f509900-21c7-11eb-9382-d43d2b3ce591.png)

i think i just need to change this to Vatican City:

![image](https://user-images.githubusercontent.com/4974087/98483692-b7281d00-21c7-11eb-8a35-3f46aba0057d.png)

**Comment by abettermap** [comment]
@rperlin-ela thanks for documenting. w/o digging into troubleshooting, i'm baffled by squished dot. i mean it's gotta be a screen size thing but it's weird i don't see it on 1920x1080. can kinda sort duplicate it in Safari with `CMD + -` but it only flashes for a sec.

Future Jason: try setting a `flex-basis` on it. that's gotta be it.

**Comment by abettermap** [comment]
Ross, you don't happened to have your screen zoomed out on the 1920 do you? You can reset the zoom with `CMD + 0`. that would explain the 1920 but i don't have a modern enough monitor to test the 2560.

**Comment by abettermap** [comment]
covering Vatican thing in #131 instead

**Comment by rperlin-ela** [comment]
> Vatican

Great — sorry for these curveballs!

> Ross, you don't happened to have your screen zoomed out on the 1920 do you? You can reset the zoom with `CMD + 0`. that would explain the 1920 but i don't have a modern enough monitor to test the 2560.

No, not zoomed out, tried the reset. It's still happening on the iPad too (always, given that the panel is at the bottom). On the other hand, "United States" chip is just fine on iPad
