### ISSUE TITLE
Pop-ups far from points

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#138]
## Summary

Seemingly on desktop only, in situations just hovering over points after zooming out (not doing anything else), the pop-up for a given point seems to appear quite far away (but consistently far) from the point being hovered over. It's as if the pop-up is not appropriately following the point in the new zoomed-out situation. Not sure but 

I don't think it's related to the 3D tilt. Seems to happen with any point, though it's easier to see with suburban points. Actually clicking on points there is no problem.

In the attached screenshots, the point being hovered over is indicated crudely with a red arrow and the pop-up (far away) should be visible

![Screen Shot 2020-11-29 at 10 37 03 PM (2)](https://user-images.githubusercontent.com/52076788/100566826-01676000-3295-11eb-962b-2851833f8e7b.png)
![Screen Shot 2020-11-29 at 10 36 58 PM (2)](https://user-images.githubusercontent.com/52076788/100566844-117f3f80-3295-11eb-8202-2ff47f5aa1c1.png)
![Uploading Screen Shot 2020-11-29 at 10.36.36 PM (2).png…]()
![Screen Shot 2020-11-29 at 10 36 07 PM (2)](https://user-images.githubusercontent.com/52076788/100566779-e137a100-3294-11eb-8b7e-d154f210b2c7.png)

**Comment by abettermap** [comment]
Oh on HOVER, I thought you meant the popup when the point is _clicked_. Yeah I've seen this before I think, but it's been like that for awhile, way before census AFAIK, so gonna have to back-burner it for the time being. 

Thanks for documenting though, now it's official.

**Comment by abettermap** [comment]
@rperlin-ela this is fixed yeah?
