### ISSUE TITLE
Labels indiscernible if too concentrated

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#141]
## Summary
Not exactly a bug but some of the communities are too tightly packed to show all of them at once at the default zoom level for when a community is selected:

![image](https://user-images.githubusercontent.com/4974087/101080818-7e7d2880-3566-11eb-83d4-fd052d2619d1.png)

3D reset and sans popup for clarity:

![image](https://user-images.githubusercontent.com/4974087/101080875-92c12580-3566-11eb-9317-3149c7910c67.png)

Can't see individual points until essentially the street block level:

![image](https://user-images.githubusercontent.com/4974087/101080976-b5ebd500-3566-11eb-9bc8-9db2d7ad8e14.png)

## Solutions

1. Spread out the lat/lon in the data, or
1. Make the map zoom in super far when a community is selected

My take: if there are quite a few instances like this then I'd say Solution 2, but if it's mainly just this Glendale area then Solution 1. This is the first time I've noticed so this so maybe it is just Glendale?

**Comment by abettermap** [comment]
@rperlin-ela if you think Solution 1 then pass the Assignee to me, otherwise all yours. Open to other ideas but those seemed the obvious two.

**Comment by abettermap** [comment]
oh i guess the third option would be to allow overlapping labels/conflicts with symbols but that doesn't seem useful here as it would affect labels that look fine as-is. i think the points are just super close so maybe just scatter them a couple blocks apart.

**Comment by rperlin-ela** [comment]
Thanks — I’m not viewing with labels too often, and dots-only is the default, so I’m loath to do much more rainmaning (having already done plenty), but I’ll try if it’s just or mostly Glendale and maybe Prospect Heights where I think I see the same issue. Park Hill and Astoria have similar clusters but seem ok to me— especially with labels on we just have to hope people will understand to zoom and see more...

**Comment by abettermap** [comment]
Ok sounds good, your call either way, just thought I'd point it out. I can also make the zoom level slightly higher although it's still not helping much in Glendale. This is zoom level 16 (my first screenshot above was 14):

![image](https://user-images.githubusercontent.com/4974087/101086385-04e93880-356e-11eb-9af5-08aa966405a8.png)

I'll just leave it and if you get a rainman hankering then go for it.

**Comment by abettermap** [comment]
unrelated but since i've got your attn...

i think the Final Output might have lost its footing after the source workbook got moved:

![image](https://user-images.githubusercontent.com/4974087/101086632-63aeb200-356e-11eb-8e2d-5c7535cf5a3b.png)

**Comment by rperlin-ela** [comment]
Adjusted Glendale, hopefully better now

**Comment by abettermap** [comment]
yep it bought us one more label at zoom 14:

![image](https://user-images.githubusercontent.com/4974087/101268949-5f2cf980-3726-11eb-9901-1bc567ae8ba9.png)

and a few more at 14.5, so i'll roll with that:

![image](https://user-images.githubusercontent.com/4974087/101269024-16c20b80-3727-11eb-85de-5ff704fdaee8.png)
