### ISSUE TITLE
Removing comma in Non-NYC locations in Explore

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#142]
## Description

This is tiny and may already have been addressed somewhere, but because locations are separated by comma in the cards, the ones like "Dover, NJ" could look like two separate locations— see screenshot below from in Explore/WorldRegion/CentralAsia. Applies also to Explore/Country/CountryName, Explore/Macrocommunity/MacroName, that whole level where neighborhoods and towns are shown together in the cards under their respective languages.

I'm down, hoping it's easy, just to strip out the comma before the state abbreviation so you have "Bensonhurst, Dover NJ, Forest Hills" etc.

![Screen Shot 2020-12-05 at 8 24 04 PM (2)](https://user-images.githubusercontent.com/52076788/101269071-7c6ac380-3738-11eb-895a-b6b6fb29cbf9.png)

**Comment by abettermap** [comment]
Could it just be changed to that or **Wayne (NJ)** in the data or would that mess anything up?

**Comment by rperlin-ela** [comment]
Good call, I don’t see why not. Just changed in the spreadsheet and will upload new tileset shortly
