### ISSUE TITLE
"Pre-details" wrapup

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#144]
## Description

Finalize the "language profile" page.

#### Census popout
Remaining wording/UI edits: https://github.com/Language-Mapping/language-map/pull/143#issuecomment-739982298

- Vintage
- Rm btns heading
- Change wording
- Make language bold: _Related ACS 2014-2018 Data (PUMA-level): **Tibetan**_

#### Language-level chips
(some of these need to be added to Config sheet first)

- Country
- Language Family
- World Region
- Macrocommunity (not sure if this is language-level)

 **Did we decide if these (and the non-clickable meta like glotto, iso, global speakers) will go into a popout or show 24/7?**

### Body (Neighborhoods)
Described in https://github.com/Language-Mapping/language-map/issues/136#issuecomment-738491655 and https://github.com/Language-Mapping/language-map/issues/136#issuecomment-739440239.

**Comment by abettermap** [comment]
@rperlin-ela please add anything i may have missed, and let me know about the question in bold when you have a chance. For now I'm just going to try 24/7 and only popout in a pinch if deemed too busy, but i think it will be very comparable to Details' intro.

**Comment by abettermap** [comment]
(from other thread)

> Right. I don't know if this gets at what you're feeling, but maybe first above we should have The Census Bureau's American Community Survey (ACS), then below

I'm using a verbatim truncated version of what's in Spatial and would like to continue to so that we don't have two different sets of wording to maintain, so if the `(ACS)` addition is added here then I'll need to change the Spatial intro.

**Comment by rperlin-ela** [comment]
Looks good. I guess the order (after Census?) should be Country, World Region, Language Family. I think we can leave Macrocommunity off since it could get confusing, doesn't feel essential here. But squeeze in Global Speaker Total (where available)? I hadn't thought of it, but Video/Audio are language-level, not sure if it would make any sense to squeeze in

I think 24/7 would be ideal, and if it sort of mirrors Details while being distinct, that's great

**Comment by abettermap** [comment]
## Census popout
How's this for census popout? Sufficient?

![image](https://user-images.githubusercontent.com/4974087/101383622-9a3e4280-3876-11eb-94bf-ffa9888e5b1f.png)

And Spatial with the extra ACS:

![image](https://user-images.githubusercontent.com/4974087/101383789-cc4fa480-3876-11eb-934c-2b280a2c402a.png)


## Chips et al replies
> Looks good. I guess the order (after Census?) should be Country, World Region, Language Family. I think we can leave Macrocommunity off since it could get confusing, doesn't feel essential here. 

Sure thing, i just went alphabetical from my prev list, but i'll be refactoring the Details intro so that i can reuse it. I think the only chip difference will be that Details includes Neighborhood (e.g. Woodside +1) and Macrocommunity, so are you okay with neighborhood being first in Details? So that would be:

1. Neighborhood
1. Census
1. The other 3

> But squeeze in Global Speaker Total (where available)?

yep, i'm thinking `glotto | iso | speakers` on the line before the chips, like how Neighborhoods is in Details currently (sans bold though)

> I hadn't thought of it, but Video/Audio are language-level, not sure if it would make any sense to squeeze in

ah cool, didn't know that, but yeah makes sense to follow suit with those two. wow so basically at this point I can reuse the _entire_ Details intro except for:

- "Clear selection"
- Neighborhood/Town
- Macrocommunity

**Is that correct?**

Poor Matt, just keeps getting more columns thrown at him! But yeah if those are added I think I can adjust the code and reuse all of that.

## Data

### _notes cols
I'm going to scrap the `_notes` columns because:

1. every time a new column is added, i have to adjust the range in the code, so let's just say "all the columns in the sheets are needed". it was recommended in the docs to use ranges, but this is getting tedious so i'll use whole sheet.
1. we can achieve what `_notes` accomplishes via in-cell Comments and Notes anyway

### Long-term vision
I could see a world when your MB upload contains only the columns needed in the map:

- ID
- Endonym
- Font Image Alt (maybe)
- Language
- Latitude
- Longitude
- Size
- Status
- World Region

And I consume everything else from sheets or CMS or DB. 

Just futurizing here, but it just reinforces that we're on the right track with all this language-level effort.

**Comment by rperlin-ela** [comment]
> How's this for census popout? Sufficient?

Great!

> And Spatial with the extra ACS:

Sweet!

> Sure thing, i just went alphabetical from my prev list, but i'll be refactoring the Details intro so that i can reuse it. I think the only chip difference will be that Details includes Neighborhood (e.g. Woodside +1) and Macrocommunity, so are you okay with neighborhood being first in Details? So that would be:
> 
> 1. Neighborhood
> 2. Census
> 3. The other 3

Seem right to me. The way we're headed, Neighborhood and instance-level Descrip are the key differences between "Language Profile" and "Details", so I guess anything that emphasizes them

> ah cool, didn't know that, but yeah makes sense to follow suit with those two. wow so basically at this point I can reuse the _entire_ Details intro except for:
> 
> * "Clear selection"
> * Neighborhood/Town
> * Macrocommunity
> 
> **Is that correct?**

Yep, that's right. So everything will be shared except "Details" will have those special ones, and the "Language Profile" page will have its special ones: ISO, Glotto, Speaker Total, and ideally/eventually there will be different Descrips at each level.


> ### Long-term vision
> I could see a world when your MB upload contains only the columns needed in the map:
> 
> * ID
> * Endonym
> * Font Image Alt (maybe)
> * Language
> * Latitude
> * Longitude
> * Size
> * Status
> * World Region
> 
> And I consume everything else from sheets or CMS or DB.
> 
> Just futurizing here, but it just reinforces that we're on the right track with all this language-level effort.

Yeah, let's get things as elegant and clear as we can. I'm not sure if it makes any difference, but in case it wasn't clear, Endonym, Font Image Alt, and World Region, should all be language-level properties, so could move those too

**Comment by abettermap** [comment]
> Yeah, let's get things as elegant and clear as we can. I'm not sure if it makes any difference, but in case it wasn't clear, Endonym, Font Image Alt, and World Region, should all be language-level properties, so could move those too

sorry, didn't explain well, a few different data/config sources here: 

1. Config sheet, with all the language-level info (what we'll achieve this week)
1. Final Output, which is hybrid of instance-level and language-level for convenience on the code side, and would be same as now except I'd hit it from the Sheets API directly
1. An MB-only newcomer: subset of Final Output containing only what MB needs: coordinates, ID, label fields, and symbology fields. Bit of redundancy with Final Output but at least it wouldn't have Descriptions as part of the map data.

I could take it a step further and do JUST the ID and coords, and join to Final Output as needed, but that's more trouble than it's worth.

**Comment by rperlin-ela** [comment]
Cool, thanks for the breakdown, yeah I think I get it, had the sense that we were going for a bit of a hybrid given the Labels and Symbology, not a pure language-level/instance-level split. 

Pretty solid if, once this is up and running, I only need to upload tileset if changing the fields you mention in 3

**Comment by abettermap** [comment]
> Pretty solid if, once this is up and running, I only need to upload tileset if changing the fields you mention in 3

oh yeah, i didn't even think of the benefit of less upload frequency. another +1.

i've been tossing around the idea of writing a script for you so you can do it all in one go via APIs. you'd have to open Terminal on your Mac, but there'd just be one command like `./upload` or something, and i'd document it of course.

MB seems like they'd gain an edge over Carto if they offered the same "sync with other services like Dropbox or Drive" service, that's super handy.

**Comment by rperlin-ela** [comment]
If a script isn’t too bad to write, that’d be great — we’re doing something similar with all our recordings, for archiving purposes
