### ISSUE TITLE
Lower Case after Hyphen in Explore Breadcrumbs

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#146]
Hopefully a quick fix, but would be great to have capitalization after hyphen as elsewhere, e.g. "African-American" or "Afro-Asiatic" in attached screenshots

![Screen Shot 2020-12-08 at 4 14 57 PM](https://user-images.githubusercontent.com/52076788/101542563-ef5e7f00-3970-11eb-82c5-fa2eea6ac736.png)
![Screen Shot 2020-12-08 at 4 13 59 PM (2)](https://user-images.githubusercontent.com/52076788/101542564-eff71580-3970-11eb-8ef4-44b2420a8f3d.png)

**Comment by abettermap** [comment]
Strange! Should be an easy fix.
