### ISSUE TITLE
UI decisions based on new schema/setup

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#150]
## Summary
Got some really significant changes coming to the schema and how we fetch config and data. Need to determine how they should impact the UI and code.

### Filtered vs. not
**Does this need to continue to use only the filtered data, or could it just always search the unfiltered set instead?** The latter is nicely standalone API-wise and need not rely on the same huge all-column data that the table needs, and it would be trivial to implement with the Airtable setup. The only columns we'd need (from the "Language" table in Airtable): 

1. Glotto
2. ISO
3. Language
4. Primary Neighborhoods (or `primaries` or whatever I called it)
5. For each of the instances, an `id`, either our current one or, ideally, the Airtable internal ID (which I will add to the dataset), so that the clicked result takes users to Details.

The potentially weird scenario would be clicking a result for a community that's currently filtered out in the table and the map. However, now that Airtable is separate from MB, the user would still see the full Details view and (I think) the map would still zoom to the right spot and most likely show the popup. You just wouldn't see the point itself, although I could slap a generic icon instead of the currently selected symbology? That little dot is not exactly standing out anyway:

![image](https://user-images.githubusercontent.com/4974087/102027618-915fdc00-3d62-11eb-96ec-7fd60e927a4a.png)

I think a big fella would stand out more, something similar to this (pretend there's a popup there):

![image](https://user-images.githubusercontent.com/4974087/102027641-b9e7d600-3d62-11eb-9f97-bc4e57460ec8.png)

and the user has other means for interpreting the symbol anyway:

![image](https://user-images.githubusercontent.com/4974087/102027667-dc79ef00-3d62-11eb-970d-251dd1a45e3f.png)

### Primary vs. addl neighborhoods
Regardless of filters, we are searching primary neighbs, correct? As in, a search for `Albanian (Geg)` should return Morris Park and Tompkinsville, but not Belmont?

### Language-level description
Should this be included as part of the search, behind a hidden column? Similar to instance-level Description, but sans column (the "view details" btn technically comes from Description).

My concern is that the data is going to be huge if there are two Description-like columns included. Maybe it's fine, but either way just wondering if this should be the approach. No promises that the Search won't choke with that many records! 

`1100 rows X many columns = a lot of cells`

### Neighborhood/s
Probably came full circle and back again on this, but now that we'll have "Primary" and "Addl" neighborhoods broken out in the data, should they be shown as such in the table (in their own columns)? I think this falls under the same concept as our intended hiding-of-the-addl approach in Details (e.g. "Woodside +1"), and adding an additional column seems potentially unruly, not to mention inconsistent with how we'll be presenting it in Details. 

The _/Explore/Thing/Language/LangName_ will indeed break out addl neighbs, but since that is more of a language-level view (whereas the table is more of a mixture between language and instance-level) I think it makes sense to reinforce our distinction between primary and addl in the table by not tiptoeing around the distinction but rather obviating it with a dedicated "Primary Neighborhood" column. 6 months into this project, I think it's time to commit to this concept and call it what it is. The user has _plenty_ of opportunities to explore and discover more instance locations, and it will be presented and spelled out very clearly in _/Explore/Thing/Language/LangName_ and the `Woodside +1` chip.

#### Combo
I am not very open to combining the two columns after we finally dismantled them into their respective parts and agreed on a way to present it in the UI. This would be more work, another Airtable column, and an inconsistent way to communicate Neighborhoodness, so let me know an A or B answer: show "Primary Neighborhood" in table, or show that _and_ Addl?

**Comment by rperlin-ela** [comment]
> ## Omnibox
> ### Filtered vs. not
> **Does this need to continue to use only the filtered data, or could it just always search the unfiltered set instead?** 

Yep, I reckon it can always search the unfiltered set.

> The potentially weird scenario would be clicking a result for a community that's currently filtered out in the table and the map. However, now that Airtable is separate from MB, the user would still see the full Details view and (I think) the map would still zoom to the right spot and most likely show the popup. You just wouldn't see the point itself, although I could slap a generic icon instead of the currently selected symbology? That little dot is not exactly standing out anyway:
> 
> ![image](https://user-images.githubusercontent.com/4974087/102027618-915fdc00-3d62-11eb-96ec-7fd60e927a4a.png)
> 
> I think a big fella would stand out more, something similar to this (pretend there's a popup there):
> 
> ![image](https://user-images.githubusercontent.com/4974087/102027641-b9e7d600-3d62-11eb-9f97-bc4e57460ec8.png)

Seems like a good solution, I'm into it.

> Regardless of filters, we are searching primary neighbs, correct? As in, a search for `Albanian (Geg)` should return Morris Park and Tompkinsville, but not Belmont?

You mean no secondaries in the omnibox, right? Yes, I think that makes sense.

> Should this be included as part of the search, behind a hidden column? Similar to instance-level Description, but sans column (the "view details" btn technically comes from Description).

Forgot about this. Could be nice but I don't think it's crucial, and certainly not worth it if there's a performance impact.

> I think it makes sense to reinforce our distinction between primary and addl in the table by not tiptoeing around the distinction but rather obviating it with a dedicated "Primary Neighborhood" column. 

Understand what you're saying but I have two concerns/counter-arguments. One is that the Data Table, despite some hidden columns, has been kind of masquerading as the total data set for the real geeks to play with. ISOs and Glottos don't really need filtering, and something like Macro is pretty marginal, but cutting the Addl Neighborhoods seems like a hit to the usefulness of this table. Like: go here to filter and sort and sift in all kinds of great ways, just don't come here to see all the languages spoken in Astoria!

The second thing I'm worried about is that with the very blunt distinction between Primaries and Secondaries that's emerging is that we're losing the fact that Secondaries are for the most part associated quite specifically with certain Primaries. In other words, there is a Punjabi community in Brooklyn (with one record), for which the Primary Neighborhood is Flatbush and the Secondary Neighborhood is Kensington. Not "there is a Punjabi community in the NYC with these four Primary Neighborhoods and these Six Secondary Neighborhoods scattered all around". Does that make sense?

At the moment, at least those who know about the areas and communities can see Primary-Secondary relationships represented in a few places besides shout-outs in Descriptions. I understand that for other users it might all be a blur, and I really like that we're tackling the confusion of Secondaries not showing up on the map, but just having a laundry list of alphabetized Primaries followed by a list of alphabetized Secondaries seems to mean losing something that we actually already have in our data. I'm open to various ways, but I want to keep representing this. Like maybe in Explore, but for now I think that's shaping up to be two alphabetized lists one after another. And if I'm understanding it right, we just decided that it makes sense to axe secondaries in the Omnibox altogether.

So besides Table, I guess the +n in Details (e.g. Woodside +1) is the one place we'll still have Secondaries being associated with a particular record? Having it only there just feels too marginal to me, so if the combo in Table is out, which I agree makes sense, I think I'm on the side of having an "Additional Neighborhoods" column in the table short of any other solution. Believe me, I really don't want to add more columns to our poor overstretched table, especially with two long headers "Primary Neighborhoods" and "Secondary Neighborhoods". I'm down to change those names if it's worth it and to consider of other solutions to keep the table trimmer.

Just a related thought that I can try to reinforce in Help: we definitely don't want people to think we're showing them the Primary Languages spoken in Astoria (as in the top languages spoken there). We're not. We're showing them the languages for which Astoria is a Primary Neighborhood. So anything that suggests "Primary Languages" and "Additional Languages" (as in the Neighborhood table in Airtable, even if it's just meant to be shorthard and no one sees it) could be confusing.

**Comment by abettermap** [comment]
If combo would communicate it better then we could probably make one in Airtable, but I could see that getting confusing for a lot of reasons code-wise and maybe UI-wise. So, if the two-column approach and some supplemental Help wording sufficiently communicate your message and goals, let's roll with that. 

Let me know what the column headings should be, and please rename them in Airtable. I created [a view](https://airtable.com/tblHBOmrPVk0WJGZ1/viwZj06z4ObY9bnA3?blocks=hide) with just the relevant Data cols, and another one of the same name in Language table.

**Comment by rperlin-ela** [comment]
One more hopefully coherent thought before I hit the hay. What about replacing “Neighborhood” in the table with “Primary Location” that serves up either Primary Nabe or Towns for the suburban ones? That way one value per record, and also every record has a value. In a way that would match what we’ll be serving up in the top half of Pre-Details, right, which should probably also be called “Primary Location(s)”, and in card footers? So hopefully something we’ll already have anyway in Airtable. Just a thought, but somehow I feel like that could better justify leaving Secondaries out of the table...

**Comment by abettermap** [comment]
> What about replacing “Neighborhood” in the table with “Primary Location” that serves up either Primary Nabe or Towns for the suburban ones?

yeah that sounds good, i thought i had suggested that but maybe it was actually including Town in that column 

> That way one value per record, and also every record has a value. In a way that would match what we’ll be serving up in the top half of Pre-Details, right, which should probably also be called “Primary Location(s)”, and in card footers?

Whew, so many implications with this! The routing (`/Explore/Neighborhood`) is super married to the data, and there are dozens of spots in the code to consider. Whatever we settle on, we should do so before I start working on any of the airtable-driven Explore stuff (and table and omnibox for that matter).

so would the /Explore/Neighborhood become _/Explore/Primary Location_? i'll say off the bat that any disparity between the route and what's in the data is kind of a deal-breaker, so let's confirm we're on same page there.

> So hopefully something we’ll already have anyway in Airtable.

well it's just based on Neighborhood right now, but yeah with a formula it's conceivable that Town and Primary Neighborhood columns could be combined into a "Primary Location" field via formula and ensure that all the records in that column are populated.

and Addl/Secondary wouldn't change, right? still distinct from Primary (and Town obviously)?

> Just a thought, but somehow I feel like that could better justify leaving Secondaries out of the table...

sounds good. and if you want to include Secondaries, but hidden yet still searchable via Search in table, that might be doable. i'm not sure how well it searches arrays though, i don't think we've had that scenario yet, it's all been strings so far.

let me know about the Primary Location field. or better yet, take a stab at creating it in the Data table. 😉  i'll give you a hint: it's going to be a formula, probably very similar to what I created for "Census Pretty" in the Language table...

buena suerte!

**Comment by abettermap** [comment]
> In terms of the data, I don't see a need for this because it's only the neighborhoods that have tons of languages, most towns just have one, and we've made our city focus clear

ok so `/Explore/Neighborhood` will live on with its current behavior, correct? essentially [this](https://airtable.com/tbl8X3GzdMtx8SS0A/viwvkeDXEnVaYL1jD?blocks=hide)? 

> But out of curiosity would it be awful or impossible to add Explore/Towns sometime in a SOW far, far in the future?

how about in the recent, recent past? already [a thing](https://deploy-preview-151--languagemapping.netlify.app/Explore/Town) ;) The beauty that is routing! 🏅  And if you want it to be in the top-level Explore landing, I think if I set up based on [this](https://airtable.com/tblBCPWzZ8GViUz1c/viwxLD7GSugijhdlI?blocks=hide) then that could ultimately be controlled on your end. 

Not set up yet, will likely save the Explores for last. Today going to do my best to knock out airtable-only map symbology, and Details if i can. looking fwd to that one as it will be awesome to see it load way before the map is done.

> Just threw in a Concatenate formula

beauty! sweet JSON gold coming back:

![image](https://user-images.githubusercontent.com/4974087/102254644-23ccc080-3ec6-11eb-8e5c-70b51e88433b.png)

i stole your concat idea for the Census Pretty as well.

> required axing "New York (NY)" as a town (do we need that?)

seems awfully redundant, and Town should represent non-NYC locations so i'd vote No.

> Not exactly consistent and maybe just a feeling that will pass, but I'm a little tempted to put (NYC) after the neighborhoods now

whatever floats your data boat. i'm not going to do any extra checks in the code, although i don't think the NYC addition would require that anyway.

IMO i think it's fine sans since the "(NY)" and "(CT)" indicate the non-neighb-ness pretty well, and a lack thereof says "neigbh-ness". and we've got blurbs for days if that doesn't cut it.

**Comment by abettermap** [comment]
oops forgot to reply to this...

> Understood, but my thought was that we were kind of doing this anyway now. 

ah you're right, i must've been thinking it was Neighb-only for pre-Details. so, at that level i'll be hitting your `Primary Location` field, correct? i mean it will be a rollup-ish field of it in the Language table, but either way that's the field i'll be consuming, right?

> For instance, Amharic, where East Orange (NJ) and the NYC neighborhoods are all happily swimming together in Pre-Details. Parkchester is a Secondary, so that'll get bumped down, but then won't we have a header like "Primary Location" covering the other three?

yep, we've got some deets on that floating around somewhere, in #132 i believe.

**Comment by rperlin-ela** [comment]
> ok so `/Explore/Neighborhood` will live on with its current behavior, correct? essentially [this](https://airtable.com/tbl8X3GzdMtx8SS0A/viwvkeDXEnVaYL1jD?blocks=hide)?

Yeah, including both Primaries and Secondaries

> > But out of curiosity would it be awful or impossible to add Explore/Towns sometime in a SOW far, far in the future?
 
> how about in the recent, recent past? already [a thing](https://deploy-preview-151--languagemapping.netlify.app/Explore/Town) ;) The beauty that is routing! 🏅 And if you want it to be in the top-level Explore landing, I think if I set up based on [this](https://airtable.com/tblBCPWzZ8GViUz1c/viwxLD7GSugijhdlI?blocks=hide) then that could ultimately be controlled on your end.

Sweet!

> ah you're right, i must've been thinking it was Neighb-only for pre-Details. so, at that level i'll be hitting your `Primary Location` field, correct? i mean it will be a rollup-ish field of it in the Language table, but either way that's the field i'll be consuming, right?

Great, I think so

**Comment by abettermap** [comment]
> Yeah, including both Primaries and Secondaries

Hmm, that's not something we discussed, unless i'm not understanding correctly. We're not going to have multiple sections of cards or lists at the `/Explore/Neighborhood` level, just one set of cards, so change that Gallery view I created so that it resembles what the cards are supposed to look like. 

For `/Explore/Something/Language/LangName`, yes, we will have a section of "Primary location" cards, followed by an "additional locations" list.

> Great, I think so

going to take that as a yes.

**Comment by rperlin-ela** [comment]
I meant just sticking with what we currently have— see Lower East Side screenshot below. Hebrew, Romanian etc have the LES as a  Secondary Neighborhood. It’s fine not to divide this into two sets, I thought it could literally stay exactly like it is, except for the footers which I think we agreed would change throughout to show only Primaries.

In the Airtable Gallery at first I see only Primaries (with the label Primary Languages which we don’t want), but then when I click I see two sets of cards, Primaries and Addl.

I know we’re in favor of a clearer separation of Primaries and Secondaries overall, but this is a place where I think it makes sense to see everything and I was figuring so be it if they’re all together. And a case of "if it ain’t broke". Sorry if I'm misunderstanding or not thinking of something

**Comment by abettermap** [comment]
> I meant just sticking with what we currently have— see Lower East Side screenshot below.

not seeing it, please post.

> In the Airtable Gallery at first I see only Primaries (with the label Primary Languages which we don’t want), but then when I click I see two sets of cards, Primaries and Addl.

sorry this caused so much confusion, i didn't mean that the Airtable gallery was an exact replica of the UI (clicking, and content, etc.). I just thought it would be an easy way to say: "Are these the languages that should be shown in the card footer for Auburndale when the user is at the URL of `/Explore/Neighborhood`?"

![image](https://user-images.githubusercontent.com/4974087/102391546-17626980-3f93-11eb-859c-7dfdf14df40d.png)

and are all the cards in the Gallery the entirety of cards that should be shown for `/Explore/Neighborhood`? 

what about the ones that don't have any primary languages? should they be excluded from `/Explore/Neighborhood`?

![image](https://user-images.githubusercontent.com/4974087/102391918-99eb2900-3f93-11eb-8f45-a62b7a0fe30c.png)

**Comment by rperlin-ela** [comment]
> not seeing it, please post.

Right, attachments don't seem to make it when I reply to an issue from email.

![Screen Shot 2020-12-16 at 8 26 17 AM (2)](https://user-images.githubusercontent.com/52076788/102393722-be9ccc00-3fa6-11eb-9627-2fe54b4354cd.png)

> sorry this caused so much confusion, i didn't mean that the Airtable gallery was an exact replica of the UI (clicking, and content, etc.). I just thought it would be an easy way to say: "Are these the languages that should be shown in the card footer for Auburndale when the user is at the URL of `/Explore/Neighborhood`?"

For card footers, yes, exactly

But my bad for not being clear that #149 is really only about the card footers.   

Are you ok with `/Explore/Neighborhood/Something (like Lower East Side) remaining as it is now?

> and are all the cards in the Gallery the entirety of cards that should be shown for `/Explore/Neighborhood`?

As with`/Explore/Neighborhood/Something, I think I'm pretty happy with `/Explore/Neighborhood/ as is, i.e. showing all languages associated associated with a nabe (see Lower East Side above) as well as showing nabes that don't have primary languages, e.g. Laurelton, Castle Hill etc.

Any reason not to from your end?

**Comment by abettermap** [comment]
> Right, attachments don't seem to make it when I reply to an issue from email.

If you happen to be on your phone, I highly recommend the GH iOS app.

> Are you ok with /Explore/Neighborhood/Something (like Lower East Side) remaining as it is now?

Is that the one with the comprehensive/combined primary/secondary footers? That's fine, as long as `/Explore/NotNeighborhood/Something` is consistent. I think we'd need a formula field to smash those two together for this view, though.

> As with /Explore/Neighborhood/Something I think I'm pretty happy with /Explore/Neighborhood/ as is, i.e. showing all languages associated associated with a nabe (see Lower East Side above) as well as showing nabes that don't have primary languages, e.g. Laurelton, Castle Hill etc.

So, the neighbs w/o primaries in `/Explore/Neighborhood` would just have empty footers then? But when clicked they would take you to the list of cards where they occur as primary and/or secondary?

> Any reason not to from your end?

If i understand correctly, no? I'm getting simultaneously more and less confused by the comment though. If you are able to create a Gallery that contains a representation of just what I need for those levels, that would go a long way. I'm kind of losing time trying to make those and clarify the requirements, so anything helps.

**Comment by rperlin-ela** [comment]
Getting pretty confused here now as well, sorry if I'm missing things. I'm down to hop on a call quick but have a million other things to do as well. I really want just about everything to **remain the same**. The only request was in #149 that _footers showing Neighborhoods_, across the board, only show Primary Neighborhoods, but otherwise I would just keep **everything exactly as it is now**, including  /Explore/Neighborhood. Sorry if I've said anything contradicting that

If #149 is hard or has ramifications I'm not seeing, we can drop it. I don't see any need to change anything else about how Neighborhoods are presented in Explore, except Pre-Details (aka the Language Profile) where we're going to split Primary Neighborhoods (with cards) and Secondary Neighborhoods (with bullets) for any given language, right?
 
> > Are you ok with /Explore/Neighborhood/Something (like Lower East Side) remaining as it is now?
> 
> Is that the one with the comprehensive/combined primary/secondary footers? That's fine, as long as `/Explore/NotNeighborhood/Something` is consistent. I think we'd need a formula field to smash those two together for this view, though.

Take the Lower East Side screenshot. I want all the same cards to appear with Lang and Endonym exactly as they currently do. I was just hoping (with #149) to change the footers to show Primary Neighborhoods. So for Arberesh, we would change "Lower East Side" to "Great Kills, Lower East Side", just as in the Primary Neighborhoods column in AirTable. Don't understand what would need a formula.

> So, the neighbs w/o primaries in `/Explore/Neighborhood` would just have empty footers then? But when clicked they would take you to the list of cards where they occur as primary and/or secondary?

I'm happy with Explore/Neighborhood and Explore/Neighborhood/Auburndale etc exactly as they are now. They have language names in their footers and I'm fine with all language names in all footers as they are now. They shouldn't be blank because we wouldn't be changing the way we display language names in footers, only neighborhood names

**Comment by abettermap** [comment]
I think we are good on the decisions here? Some overlap probably with #151. I will get secondary neighborhoods into /Explore/Neighborhood footers and do this:

> hide the Addl Neighborhoods while keeping it searchable?

i still think we should remove glotto and ISO from the table though. they're not advertised, and it's already searchable and advertised in omnibox. could make the case that it's same concept as searching hidden Addl Neighbs and Descrips, but neighborhoods would be something the user is already searching for and showing up in Addl Locations (and/or Description in some cases).

something for another SOW/issue, but regardless of approach we should advertise what the user can search for and that some of the results may be hidden, e.g. it's hanging out behind Description or Addl Neighborhoods, which won't be apparent since their table columns are hidden.

**Comment by rperlin-ela** [comment]
Ok all sounds good
