### ISSUE TITLE
Support single-quoted Airtable filter values

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#152]
## Summary
these guys are causing trouble w/AT API filters, which need single quotes wrapped around values:

![image](https://user-images.githubusercontent.com/4974087/103307804-3ec32880-49ce-11eb-9d19-c3e82ab51ade.png)

Might be [this bug](https://community.airtable.com/t/using-api-to-filter-records-fails-when-the-value-contains-a-comma/20035/4) (???)

**Comment by abettermap** [comment]
@rperlin-ela not sure I have a solution to this at the moment, so if there's another character that would suffice in place of `'` that would be the easiest interim fix. Let me know if that's doable.

**Comment by rperlin-ela** [comment]
You mean trying to substitute some very close look-alike character while we figure it out? Unfortunately the character is pretty integral to the endonym for all these, usually representing an ejective or glottal stop

**Comment by abettermap** [comment]
Ok no worries, just checking if there was an easy way out. 

You mentioned endonym. Could that have the quote but the language name have an alternate character?

**Comment by rperlin-ela** [comment]
Right, but I believe these are all cases where endonym and language name are the same. We could probably get away with ’ instead of ' or that kind of thing, but otherwise not sure

**Comment by abettermap** [comment]
Ross- 

I haven't looked through the rest yet, but `Ge'ez` is [not actually spelled](https://en.wikipedia.org/wiki/Ge%CA%BDez) with a `'` character, but rather whatever this thing is: `ʽ`

I changed it in Airtable and it [works like a champ now](https://map.languagemapping.org/Explore/Language/Ge%CA%BDez).

I'll look through the others while I'm waiting to hear what you think, but could this be the solution?

**Comment by abettermap** [comment]
## Other character
i fixed these and their endos in Airtable:

1. Geʽez
1. K'iche'
1. Poqomchiʼ
2. Qʼanjobʼal
3. Qʼeqchiʼ
4. Tzʼutujil

## Questionable

1. P'urhépecha looks pretty single-quotey but Purépecha is also an acceptable spelling

## True single quote
and then there were two.

1. Pa'O
2. Fe'fe'

so, would `PaʼO` and `Feʼfeʼ` be acceptable to native speakers with that character?

**Comment by abettermap** [comment]
not sure what this site is all about, but that's the character they're using for Fe'fe: https://pbase.phon.chass.ncsu.edu/pattern/6390

and library of congress uses that for Pa'O: https://id.loc.gov/authorities/subjects/sh92006042.html

i think you were at a "hard no" on the single quote thing when i brought it up before, but at least for most of the instances in the AT Language table it seems like `ʼ` is an acceptable replacement so let me know if that works for the remaining ones.

**Comment by abettermap** [comment]
sorry to pummel you before you've had a chance to reply, but in the Mac Character Viewer there are at least half a dozen Unicode chars that come up in an "apostrophe" search:

![image](https://user-images.githubusercontent.com/4974087/103838494-6f4c3780-504a-11eb-9a34-7d70498b7abb.png)

and a whole different set in a search for "quotation":

![image](https://user-images.githubusercontent.com/4974087/103838559-9b67b880-504a-11eb-9367-d1f96cacab55.png)

so if any of those apostrophes (except this `'`) can be used in place, then no code has to be changed (i don't have a solution right now anyway)

**Comment by rperlin-ela** [comment]
We’ll make a phonologist of you yet! It feels like the old endonym days again

Don’t need a full breakdown, but why is this issue only in the Language—won’t pop up elsewhere? What exactly is it we would need to avoid in the future? I gather it’s fine in Endo and must be all over Description too.

As I said, "We could probably get away with ’ instead of ' or that kind of thing”. I just want it to look right and for people to be able to search with what’s on their keyboard. What we had seemed like the most universal choice for that, and clearly there’s a lot of confusion around apostrophe/single quote, but looks like we have some acceptable subsitutes.

What you’ve got for Ge’ez seems fine, kind of a hybrid endo-lang name, and 2-6 are all Mayan languages I think we should be able to treat the same. The ʼ you have below looks fine (though for K’iche’ it seems like you have the straight ones? meant to be different?). It’s probably fine for the other three pending it looking good, being able to search on a normal keyboard, and no one complaining.

Do you know or can you check what Unicode characters you’re looking at here? That’s key. Like, is U+0027 the verboten one and you’re talking about substituting U+2019? In your top screenshot, is the first one the problem child, but the third or sixth would be ok?

**Comment by abettermap** [comment]
ugh, i must have tried the fix on the wrong file or line last time, got it working now:

![image](https://user-images.githubusercontent.com/4974087/103842228-ab839600-5052-11eb-8e8f-1aa07185c27e.png)

> Don’t need a full breakdown, but why is this issue only in the Language—won’t pop up elsewhere? What exactly is it we would need to avoid in the future? I gather it’s fine in Endo and must be all over Description too.

any time i'm querying any of the airtables and using a filter, e.g. "Show me records from Language where `name = 'Akan'`". The single quotes are part of Airtable's filter syntax, so it breaks if value already has single quotes in it, e.g. `name = 'Fe'fe''`. see the problem?

if i switch to doubles though, all set: `name = "Akan"`. i must have tried the fix too late at night. 🤤 

## AT edits
after my AT edits these are the only three left w/single quotes:

![image](https://user-images.githubusercontent.com/4974087/103842336-ee456e00-5052-11eb-8b1b-b95c02d79bc2.png)

if that's correct then we're set, if not then feel free to change back using whatever mark you want except _double_ quotes. ;)

but there shouldn't be any of those, right? in a nutshell it's anything from `/Explore` down that uses values derived from the URL, e.g.:

![image](https://user-images.githubusercontent.com/4974087/103842452-319fdc80-5053-11eb-9947-b565c815ec13.png)

for most or all i think i'm hitting the `name` field in the corresponding table (e.g. Neighborhood), so if there are any double quotes in any of these seven tables, we should address that somehow:

![image](https://user-images.githubusercontent.com/4974087/103842530-61e77b00-5053-11eb-891f-b7accfdecf47.png)

**Comment by abettermap** [comment]
double quotes in the `name` field of any of these seven tables, that is

**Comment by rperlin-ela** [comment]
Great— all set, then? Double quotes definitely don’t come up in any language names and I don’t see how it would come up in the name field for any of these.

**Comment by abettermap** [comment]
cool, i think we're set then, sorry for the unneeded steps and false alarms
