### ISSUE TITLE
Clickable "Size" and "Status" in UI Table

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#156]
## Description

This is a tiny thing, but given the great click-to-filter capability with all the columns (obviously except Global Speakers) I would expect the same with Size and Status. Apologies if there's some reason we decided against this long ago that I've forgotten. If in agreement, only fix if this is a very simple and quick thing! Otherwise totally fine as is, feel free to close issue and ignore.

**Comment by abettermap** [comment]
I gave it a try a few times but the problem is that those columns' filters are dropdown/selects. There's probably a solution out there but in the interim, which of these would you prefer?

1. as we have it now
2. open-text filter type, no dropdown, but the clicked values would work

**Comment by rperlin-ela** [comment]
Got it— either way is good. Slight personal preference for the consistency of 2 but only if it’s super-quick for you to change. Otherwise 1!
