### ISSUE TITLE
Table export: additional requests

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#158]
_Originally posted by @rperlin-ela in https://github.com/Language-Mapping/language-map/issues/118#issuecomment-756193122_

A few more:

- [x] - Prevent "Global Speaker Total", if empty, from displaying in PDF as 0
- [x] - Prevent comma or other random mark from appearing where there's a missing endonym, e.g. Chinese (Mandarin), Coptic, Bantawa etc
- [x] - "Location" instead of "Primary Location" to match UI Table?
- [x] - Space after the comma where there are multiple countries
- [x] - Switch "full source dataset" link from Sheets to https://airtable.com/shrqQo5FJHvhKtffs

**Comment by abettermap** [comment]
@rperlin-ela 

> Prevent comma or other random mark from appearing where there's a missing endonym, e.g. Chinese (Mandarin), Coptic, Bantawa etc

I got this to work but not sure if the check is too heavy-handed:

**If text includes any non-UTF chars, show nothing.**

If it is then I don't have a fix but if not then we're good, so let me know:

![image](https://user-images.githubusercontent.com/4974087/103933402-905f6780-50e0-11eb-81f5-2d4a5f125773.png)

**Comment by rperlin-ela** [comment]
Can’t tell just from this if we’ve lost any endonyms we had before, but otherwise seems promising!
