### ISSUE TITLE
Connect domain to Netlify

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#17]
Maya successfully set up Netlify with GH in #5, just need to set up domains now. I added some [relevant info](https://docs.google.com/document/d/1D4WaIMbhZGtz08KrkLsn1p7KpBdJI5ez7yfKQI8rpkM/edit#heading=h.j9eji0s5vlf0) to the setup doc, but this might take a little more coordination.

I'm thinking that all deployed URLs except those on `master` (aka staging/dev/review) can keep their defaults. We just need a final decision on **what the prod URL will be**, but I think `map.languagemapping.org` did not have any objections?

I believe the team has full control over DNS through Google Domains, so setup should be straightforward.

**Comment by fiddleHeads** [comment]
To switch to languagemap.nyc:

1. In Netlify, follow these [instructions](https://docs.netlify.com/domains-https/netlify-dns/#add-a-domain-you-own) to add and register languagemap.nyc in Netlify.

2. Then go the domain [settings ](https://app.netlify.com/teams/maya-daurio/dns/languagemap.nyc ) for this domain you just registered and note the Nameservers. The next step will be to point the Nameservers in Namecheap to Netlify.

3. To change the nameservers in Namecheap use these [instructions](https://www.namecheap.com/support/knowledgebase/article.aspx/767/10/how-to-change-dns-for-a-domain/).

Under the Domain tab, select Custom DNS.
Copy and past the (4) Nameservers from Netlify under your domain settings page here.
Click the green checkmark to save changes.
Changes may take up to 48 hours to go into effect.

4. In Netlify, add languagemap.nyc as a domain alias under Domains. Click the dropdown arrow next to Options to change this to the Primary domain.

**Comment by abettermap** [comment]
Thanks Maya. Is this just for documentation purposes or have you done the steps already? There are a few other non-code places that will need the new url as well (nothing needed on your part, should just be Ross, except Netlify if you're handling that).

**Comment by abettermap** [comment]
Disregard, just read Ross's email. Nice work!
