### ISSUE TITLE
Switch Endonym and Language in "Explore" Cards

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#175]
User suggestion to switch the position of Endonym and Language in the "Explore" cards where they appear together, to match the prominence of Endonym in the Language Profile and in Details. This would not apply to card footers, which are Language only. It would apply at the level of Explore/World Region/Something, Explore/Neighborhood/Something etc. Would also want to have it in Explore/Languages and change "Common language name in English" to something like "Common endonym (used by community) and name in English"

**Comment by abettermap** [comment]
I think I did this one in under 3 minutes 🏆
