### ISSUE TITLE
Change domain to languagemap.nyc

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#179]
## Description

Switch to super-awesome domain name.

## Related items

#17 has some documentation

## Resolution

- [x] In-code, which should only be the README and HTML (me)
- [x] The GH repo/s and maybe GH org (it's a Settings thing, so whomever has access)
- [x] MB API tokens: have whitelisted URLs from which the tilesets can be accessed (I already updated them)
- [ ] Any WP help/about stuff with absolute links, aka has "map.languagemapping.org" in the href (Ross)
- [x] Airtable API access: I don't "think" this has URL stuff but I can check
- [x] Sentry: this probably has URL stuff somewhere. I can change it when ready.
- [x] Google Sheets API: no longer using
- [x] Google Fonts: has no API stuff
- [ ] YouTube API: I think this one will need to be updated (Ross). You can leave the old whitelisted URLs intact, just be sure to add the new one/s.
- [x] Google Analytics: definitely needs to point to the new URL when ready (me I guess?)
- [x] Google Tag Manager: may need to point to the new URL when ready (me I guess?)
- [ ] Google Forms (???)

**Comment by abettermap** [comment]
## Me

Some notes/updates from my changes:

- GTM: couldn't find any URL references
- GA: had at least a couple, which I changed. Configured real-time was working.
- AT: no URL refs
- Sentry: only found one spot ("Allowed Domains"). Not sure how to confirm until an error occurs.
- GH: updated org-level and front-end site reference
- Code: README, meta tag in HTML, and default link for Share btns: 5760ff2c1b456355af1e9c66d89f5556e39267ff

## Not me

@fiddleHeads or @rperlin-ela might want to check Google Forms to see if it has anything domain-specific. Doesn't affect code (just don't change the form URL!).

I haven't looked at the Netlify domain setup but if it's the primary domain then presumably this will switch over on its own eventually in Google Search results:

![image](https://user-images.githubusercontent.com/4974087/107416772-1735a480-6ad2-11eb-8434-fb91d1f67b69.png)

## What's left

YouTube API, WP stuff should be it.

## Confirmed variations

...new domain working with:

- http
- https
- no protocol
- www w/http
- www w/https
- www no protocol

**Comment by rperlin-ela** [comment]
All good, and don't see any issues with the Google Form (Contact and Feedback)

> * [x]  Any WP help/about stuff with absolute links, aka has "map.languagemapping.org" in the href (Ross)
> * [x]  YouTube API: I think this one will need to be updated (Ross). You can leave the old whitelisted URLs intact, just be sure to add the new one/s.
> * [x]  Google Forms

**Comment by fiddleHeads** [comment]
Thanks Jason and Ross. I couldn't see anything with Google Forms, either. Interesting about the Google search. Will have to keep an eye on that to see if it does switch over on its own.

**Comment by abettermap** [comment]
Might want to do this either way: https://support.google.com/webmasters/answer/9008080

**Comment by fiddleHeads** [comment]
Thanks Jason.

I created a new DNS record from [DNS settings page](https://app.netlify.com/teams/maya-daurio/dns/languagemap.nyc) in Netlify using the following settings and then was able to verify in the Google webmasters site you sent above. 

Record Type: TXT
Name: @
Value: google-site-verification=N3AjLG152jDfKWVHW37uyduUul6NzRtzw8jp5Iyw-3M
TTL: 1
