### ISSUE TITLE
Details: nest into Language route hierarchy

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#182]
## Description

Cart before horse but this will determine some large aspects of SOW3 so let's discuss here...

The request is to remove Details from its own devoted nav level and nest it into the hierarchy. In tandem, include a Back-like ("up one level" to be specific) button or link in the top left of the Details panel. This is pretty standard in mobile apps and makes sense here. For consistency, the button/link would need to be included in other panels as well.

## Initial prototypes

Would we want to double-up on the language name here or rely on just the breadcrumb like this?

![image](https://user-images.githubusercontent.com/4974087/110009909-e6185080-7cda-11eb-96ae-dd5fc29df804.png)

I'm kind of digging the double-up myself, as long as the sub-heading is subtle in color:

![image](https://user-images.githubusercontent.com/4974087/110011427-ac484980-7cdc-11eb-839b-232939f74f2a.png)

Use same format for other panel levels as well:

![image](https://user-images.githubusercontent.com/4974087/110010994-24623f80-7cdc-11eb-8eae-c841343913e7.png)

## Implications
...may be far reaching. Let's think it through.

### Routing
At a glance there are about 3 dozen instances in the code where `/details` things occur. 

Proposed new routes:

1. https://languagemap.nyc/Language/Peruvian%20Quechua/719 **OR**
2. https://languagemap.nyc/Language/Peruvian%20Quechua/details/719

Item 2 would allow the next issue to be addressed.

### "Try one at random" btn
Would this path be the "new empty details"? Basically anything that matches the `/Language/LangName/details` pattern.

https://languagemap.nyc/Language/Peruvian%20Quechua/details

### Super-long language names
e.g. `Caribbean Hindustani` would take up a lot of the "up one level" space and there are certainly others which are longer. Just leave enough room above the Endo I guess?

### Breadcrumbs
Would it be as simple as this?

![image](https://user-images.githubusercontent.com/4974087/110012121-6b046980-7cdd-11eb-90d1-d601acf45a80.png)

"Simple" as in UI-simple. This will/would be quite a potential nightmare in the code.

### Anything else
Tons of moving parts. What are we missing?

**Comment by rperlin-ela** [comment]
> I'm kind of digging the double-up myself, as long as the sub-heading is subtle in color

Doubling up looks good

> Use same format for other panel levels as well:

Makes sense

> Proposed new routes:
> 
> 1. https://languagemap.nyc/Language/Peruvian%20Quechua/719 **OR**
> 2. https://languagemap.nyc/Language/Peruvian%20Quechua/details/719

1 makes more intuitive sense but if 2 is a real time/problem-saver doesn't seem like a big deal. Just a little trace of the old Details left for those in the know...

### "Try one at random" btn
> Would this path be the "new empty details"? Basically anything that matches the `/Language/LangName/details` pattern.

Not sure I totally understand this, but I don't think it matters what the URL is as long as we can keep the current behaviors that show this when a) someone clicks on the map but not a point, and b) when someone clears a selected community (though I don't find this crucial)

> 
> ### Super-long language names
> e.g. `Caribbean Hindustani` would take up a lot of the "up one level" space and there are certainly others which are longer. Just leave enough room above the Endo I guess?

Open to ideas, but yeah that's all I got
> 
> ### Breadcrumbs
> Would it be as simple as this?
> 
> ![image](https://user-images.githubusercontent.com/4974087/110012121-6b046980-7cdd-11eb-90d1-d601acf45a80.png)
> 
> "Simple" as in UI-simple. This will/would be quite a potential nightmare in the code.

Looks intuitive to me, and let's check in on the nighmarishness as we proceed.

> 
> ### Anything else
> Tons of moving parts. What are we missing?

The only thing I'm wondering is if we should call Home "Home" and if it should be the ultimate root here. If we have the principle that we shouldn't toss users between panels unless we have to, maybe the root should just be Explore. Not to go crazy, but maybe Home is not a helpful name for that panel at all — what about putting a magnifying glass and calling it Search, since it'll now be home to language searching and location searching.

**Comment by abettermap** [comment]
Oops, I lumped this into #208 i believe. 

I think the only thing still applicable to salvage from this issue above is that we’re keeping the subtitle and making it not linkable. Back button and timeline thing both will achieve the same thing.

**Comment by abettermap** [comment]
Ross- 

would this work as a unique route path?


```
/Explore/Language/:LangName/:PrimaryLocation
```

example:

```
/Explore/Language/Chakhar Mongolian/Sunset Park
```

Or does it need to lean on the **AT Data table id**? e.g.

```
/Explore/Language/Chakhar Mongolian/615
```

i guess in other words, where would you expect the "up one level" Back btn to take you from The New Details?

**Comment by abettermap** [comment]
and similarly, the Timeline will also be determined by where this view sits in the hierarchy.

**Comment by rperlin-ela** [comment]
I think “up one level” from New Details definitely goes to the relevant Language Profile, even if someone arrives in a different way. Does that work? Wouldn’t that happen with either of these options? 
/Explore/Language/Chakhar Mongolian/Sunset Park
/Explore/Language/Chakhar Mongolian/615

So I may be missing something, because I know there's some twisty logic with the routing of things like this <https://languagemap.nyc/Explore/Neighborhood/Bay%20Ridge%20(Brooklyn)/Egyptian%20Arabic>  but if I think either of the above would work. The top one is a little more human-readable, so maybe a nod to that, and there should never be any ambiguity or duplication if that’s what you’re worried about. If it’s helpful or easier or feels clearer to use the AT Data table id in the route, that seems ok too — your call!

**Comment by abettermap** [comment]
> I think “up one level” from New Details definitely goes to the relevant Language Profile

right but which one, the neighborhood lang profile or the language lang profile?


hmm the `id` has been a mixed bag. although it has been super easy to hit AT using that, especially from the MB clicks.

i guess another question would be, where would you hope that the next Back takes them? if using the /Explore/Language then they'd have one level less of depth in the timeline. not sure if that matters but this just provides on more option of exploration:

```
/Egyptian Arabic
/Bay Ridge (Brooklyn)
/Neighborhood
/Explore
```

**Comment by rperlin-ela** [comment]
I got you— I would default to the language lang profile. I think there are plenty of ways to explore already, so I’d favor a clearer and more direct route. And again we know that the Back button is not really Back. But I’m open if one way is easier to implement or makes more sense to you.

**Comment by abettermap** [comment]
shoot i think it's gonna have to be like this

/Explore/Language/Chakhar Mongolian/615

if user arrives at New Details via map click, map has to use what's available in that point, in other words our For Map export columns. we don't have a primary location in there and we don't want one just for this, but we DO have a Language column being uploaded to mb, so i think that's the way.

**Comment by rperlin-ela** [comment]
Seems fine to me

**Comment by abettermap** [comment]
ok took some doin' but i got this wired up. sorry if we covered this already, but what should the 229 be here?

![image](https://user-images.githubusercontent.com/4974087/112667898-743bae80-8e23-11eb-80d1-1f8a2d3a9a36.png)

can it just say "Details" generically for all instances?

also if you ever have any languages called "none", let a brother know 😉 

![image](https://user-images.githubusercontent.com/4974087/112668053-9fbe9900-8e23-11eb-996a-8229ae4bb017.png)

and while we're there, what to say instead of "none" for Back?

![image](https://user-images.githubusercontent.com/4974087/112668100-b1a03c00-8e23-11eb-86a4-cba43fb48830.png)

it's not very important of course but i'd like to keep Back at that level for consistency and an escape hatch, so how about "No community selected"?

**Comment by abettermap** [comment]
or maybe "Community Details" generically for my first question?

**Comment by rperlin-ela** [comment]
Nice one. Generic “Community Details” seems fair and a shout-out to our roots.

We do have Nones, but I don’t think there’s a None! “No community selected” seems fine and consistent

**Comment by abettermap** [comment]
wowwww the code for anything to do with routes config, especially for Details, is just absolutely all over the place. another dev would have a helluva time picking this up without some trials and tribs!

i'll try to clean it up a little and consolidate if i get a chance, it's going to be messier w/Neighbs and Census routes if i don't.

## Testing 

i haven't finished all the things i mentioned in https://github.com/Language-Mapping/language-map/pull/211#issuecomment-807903645 but i just pushed my changes for the nested Details so please test all instances where that comes into play, e.g table, map click point, map click empty (for the "no comm selected"), and obviously the Lang Profile cards.

pretty sure i got 'em all but holler if not.

**Comment by rperlin-ela** [comment]
Oh man I love this, so natural, no one will ever know it was otherwise.

**Comment by abettermap** [comment]
Right? Pretty smoove! Just our little secret that it was ever otherwise. Yours and mine and the Internet's.
