### ISSUE TITLE
Minor wording changes

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#183]
Change the written copy for the following items (specific text may already be indicated in a separate spreadsheet):

1. “Details” view: improve default text when no community is currently selected. If needed, perform basic style edits (_Any slight improvements in styling, even like bolding, to make it look less like an error page?_) to accommodate the change: _Please select a community by clicking a point on the map, searching for a language from Home, or specifying a community in Data._ 
2. Census language search box: change default placeholder text to “Choose a language or start typing here”.
3. Explore/Neighborhood/Language view: use the same introductory text as that of /Explore/Town/Language.

**Comment by abettermap** [comment]
@rperlin-ela I missed this in the Notes column:

> Any slight improvements in styling, even like bolding, to make it look less like an error page?

Can you clarify please? It doesn't look like an error page to me.

**Comment by rperlin-ela** [comment]
Trying to interpret others’ feedback here, and re-wording will help, but maybe just bold or bigger font on some kind of header to make this seem more of a piece with the rest of the site, nothing complicated

**Comment by abettermap** [comment]
Ok I'll throw some options out there.

For census text, this was the request:

![image](https://user-images.githubusercontent.com/4974087/111179846-10d39600-8572-11eb-84da-21e3c7e4c864.png)

Doesn't look super-instructiony to me so how about one of these:

1. Drop the "here"
2. Choose a language or enter text

I like 2.

**Comment by rperlin-ela** [comment]
2’s good

**Comment by abettermap** [comment]
for "no selection" how's this:

![image](https://user-images.githubusercontent.com/4974087/111185016-2ac3a780-8577-11eb-8102-78c94bd9221b.png)

and when not found:

![image](https://user-images.githubusercontent.com/4974087/111185130-4929a300-8577-11eb-9bd9-133b19d558f4.png)

only thing i don't like now is the **button wording**. 

thoughts?

**Comment by abettermap** [comment]
i know you were opposed to this before and i could go either way but is it any more acceptable with the extra text above?

![image](https://user-images.githubusercontent.com/4974087/111185434-91e15c00-8577-11eb-8bea-a295dfed166a.png)

or this?

![image](https://user-images.githubusercontent.com/4974087/111185503-a4f42c00-8577-11eb-9a31-e0d2f0b0f57f.png)

or?

![image](https://user-images.githubusercontent.com/4974087/111185553-b3dade80-8577-11eb-81dc-4c81330eec99.png)

**Comment by rperlin-ela** [comment]
Boom, you nailed it for “No Selection”, and then “Show me a community” is great for the button.

What’s the “when not found” scenario again— besides someone typing a weird number into the URL? Not where people search for a point that’s excluded by current filters? In general I think ID numbers will confuse people, but ok if this won’t be seen much.

**Comment by abettermap** [comment]
If YOU haven't seen it then yeah it won't be seen much. It would be for the manually-typed URL scenario, yes. The only reason I noticed it is because that component shares the same stuff for both scenarios, and only the "reason" changes.

The ID is more for us internally in case we're troubleshooting. I don't see a user typing anything in manually but if they did this will at least provide a fallback instead of going up in flames.

I think we're good on that view. As for Item 3 in this issue, I mistook the location (it's not switchable with Town's text). So this should be correct:

![image](https://user-images.githubusercontent.com/4974087/111190126-67de6880-857c-11eb-91c6-ef18e38bc2c5.png)

(purple is just since i have it selected w/my mouse)

**Comment by abettermap** [comment]
Really digging the new empty Details, high five to whomever suggested it!
