### ISSUE TITLE
Add/restore missing UI bits

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#184]
- [ ] “Details” view: show Macrocommunity as a clickable, linkable “chip” in the same manner as existing chips such as World Region.
- [ ] Colored circle for "World Region" no longer appearing in UI table (migrated from #174)
- [ ] “Details” and “Language profile” views: for ASL, Avestan, Mongolian, or any Language with an image for its endonym, include English name below the image (consistent with all other text-only languages).

**Comment by abettermap** [comment]
@rperlin-ela should Macro be shown in Language Profiles in addition to Details? can't remember what was decided.

**Comment by abettermap** [comment]
actually, i thought that's why it was omitted from Details (because Lang Profile already has it and we were trying to reduce the similarities) and because it's a Lang-level thing. not to mention we now support multiple macros, so Details would get BIZZZAY with all that going on.

I think it's a one character or two-line change on my end depending on what you're after, so let me know

**Comment by rperlin-ela** [comment]
Yeah, we did deliberately omit it for the reasons you mention, and I still like the idea of reducing similarities (or increasing difference!) between the two, but I think let’s add it to Details after all. All the other chips in Details besides neighborhood are lang-level too, and not that many have one macro let alone multiple, so I guess we might as well go for consistency
