### ISSUE TITLE
"Status" legend items: include descrip/label

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#185]
- [x] “Home” view: “Status” legend: support descriptive blurbs via Airtable in the same manner as that of the legend for the “Size” symbology. May require some AT adjustments.
- [x] Remove `queryFields` from code after confirming obsoletion.

**Comment by abettermap** [comment]
@rperlin-ela just to confirm what i think we already discussed elsewhere, we are not using the `description` field of the `Status` table anywhere, correct?

![image](https://user-images.githubusercontent.com/4974087/111199480-471b1080-8586-11eb-90f6-9a8e8d0dca8c.png)

i'm assuming so and therefore going to rename that field to `label` so you can use it the same way as Size. this whole setup is really janky w/lots of moving parts in the code and Airtable, so i'm open to something less gross, but this is the quick and dirty way so i changed it as such in AT:

![image](https://user-images.githubusercontent.com/4974087/111200036-ecce7f80-8586-11eb-8d2b-12b899c7c6c3.png)

aside from grossness, that's just NOT the way to do it data-wise so my bad on creating the schema that way, but we have so many little variations between the three legend options and it's hard to keep track of them all, especially after the fact. i think this is one of those issues we could get sucked into easily, so let me know how far to go on this.

also, if we're using current definitions, it's a lot bigger than Size's, and eats up tons of space, so that's a consideration regardless of schema and data stuff:

![image](https://user-images.githubusercontent.com/4974087/111200819-c0ffc980-8587-11eb-9372-3e158fc98bc4.png)

"Read more" expansion will get messy and involve work. Something super-custom for Status only might look better, but also work. this looks pretty good IMO but it's a misleading amt of work since i just slapped it together in the browser and code would take much longer:

![image](https://user-images.githubusercontent.com/4974087/111201819-cc072980-8588-11eb-9f8d-05673a0673a3.png)

i knew Status had meatier descrips, so that's why i wanted to confirm in our pre-SOW convo that there wouldn't be any style changes, just AT and code. style = much more work than we discussed.

Thoughts?

**Comment by abettermap** [comment]
If you're ok w/reusing the same thing for Size:

![image](https://user-images.githubusercontent.com/4974087/111202854-fd342980-8589-11eb-88e2-bf0c6818f812.png)

then at least that's just two variations instead of 3 (i'm counting the grouping of World Region as a variation). code aside, it would be nice to stick with some UI consistency here instead of tossing special scenarios around.

**Comment by rperlin-ela** [comment]
Yep, looks right and makes sense to me how you’ve set it up in AT. If it’s working, no worries if it’s a little gross.

The meatiness of each of these is an issue. I just quickly edited them down to the bone— does that help? At least bold before the colon would be good. And I assume I’ll be able to edit these as with Size whenever as needed

**Comment by rperlin-ela** [comment]
Sounds fine, more consistency is good

**Comment by abettermap** [comment]
yes you can continue to edit Size using `label`. 

if i'm changing styles for part of it (e.g. bold before colon) then i'm changing design though. there's only parameter for these little swatch things (besides icon) and it's for the legend label. problem is, component gets used frequently throughout the UI (e.g. table), so if i mess with it here then i have to be careful it doesn't wreck the other bits.

again, i think i brought the design question up specifically in our convo because the Status defs are so big. if you want style/layout changes, that's cool, it looks better and makes sense in the schema, but you might have to concede on some other tasks in the SOW. i've already made the fix we discussed, staying within the guess time range (0.5 - 3hrs) but it might go past 3 w/the discussion, AT stuff, and design changes, so let me know what you think.

**Comment by abettermap** [comment]
we could change the fields to Rich Text and you could style it, but still extra work and more prone to inconsistencies.

**Comment by rperlin-ela** [comment]
Ok, doesn’t seem worth it to bold a few words, I'm just hoping that it looks fine with the newly condensed text so let’s see

**Comment by abettermap** [comment]
![image](https://user-images.githubusercontent.com/4974087/111207155-e0e6bb80-858e-11eb-8da8-4c9e2db8b5c0.png)

**Comment by abettermap** [comment]
it's not terrible. run with it and make a new issue to do it properly "later"?

**Comment by abettermap** [comment]
just dropping the font size helps a little

![image](https://user-images.githubusercontent.com/4974087/111207693-8e59cf00-858f-11eb-9793-a058726a37ee.png)


and doesn't look bad w/world region:

![image](https://user-images.githubusercontent.com/4974087/111207517-594d7c80-858f-11eb-80fe-888951795ba6.png)

**Comment by abettermap** [comment]
also if you don't capitalize the first letter after the colon, then the term (e.g. Liturgical) maybe stand out a little more

**Comment by rperlin-ela** [comment]
done, nice one

**Comment by abettermap** [comment]
nice, here's where we're at:

![image](https://user-images.githubusercontent.com/4974087/111221372-08924f80-85a0-11eb-8b4f-a3ca9afeea45.png)

or this with a smaller font:

![image](https://user-images.githubusercontent.com/4974087/111222863-00d3aa80-85a2-11eb-9e7f-c95af7ced0e6.png)

some other minimalist suggestions:

1. "used" is in every item. any way to reword the Status definition at the top as kind of a "prelude" to the items? Either way could probably drop "used" from Liturgical.
2. along those same prelude lines, maybe indicate that they're all current unless otherwise noted? then have only "formerly" for Historical and no "currently" in the others. Not sure if that works or not. 
3. "primarily" to "mainly" in Reviving gets us a few chars closer to one line 😆 
4. Reviving: could you say 'second-language teachers' instead?
5. Liturgical: "daily" instead of everyday?
6. Residential: change to `, possibly other settings`

i think we're past nickel-and-diming and down to pennying-and-nickeling 🤑

**Comment by rperlin-ela** [comment]
Cut further, now really down to the bone.

I like smaller font.

You’d give Hemingway a run for his money!

**Comment by abettermap** [comment]
Ha, maybe he'd pay out in absinthe instead. Plus my pockets are already full of these pennies, you know?

Good whittling though. My only main suggestion would be find a way to define Community without using that word in the definition.

Oh if you want it stand out a little more, there's always all-caps for the terms...
