### ISSUE TITLE
“Share” buttons: indicate language in post title/body

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#186]
“Share” buttons: in the post title, if possible and relevant, specify the language specific to the link being shared. Currently this is working for Twitter but not Facebook or LinkedIn, and the status of Reddit is unknown. If it is not possible to achieve this then some indication of the selected language will be made in the body of the post when possible (LinkedIn may not support this), e.g. “Chakhar Mongolian [language] is spoken in Sunset Park (Brooklyn) [location]. Part of an interactive map...”

**Comment by abettermap** [comment]
@rperlin-ela do you have a Reddit acct? If so can you let me know if it needs work or just FB/LinkedIn? No mention of WhatsApp or email so I'll assume good on those.

**Comment by rperlin-ela** [comment]
I don’t, can assume the ones mentioned are what needs work

**Comment by abettermap** [comment]
just as an FYI in case there is any question about the variations between platforms, here's what is available for each one (in addition to the URL, which is common to all): https://github.com/nygardk/react-share#share-button-props

so, whatever is available for each is what i'll use.

related: **can we swap Reddit for FB Messenger?** Might be less work than testing Reddit and i could see it being used more.

**Comment by abettermap** [comment]
couple more updates/questions...

**good enough for FB?** they only have one parameter so i made it same as twitter (i feel like users are just going to customize/overwrite the placeholder anyway, or at least that's what i might do):

![image](https://user-images.githubusercontent.com/4974087/111210549-fc53c580-8592-11eb-801b-98f9478dba6c.png)

**scratch the Messenger thing**, it requires a FB app ID, don't want to go through those steps.

i might have a reddit acct lingering somewhere but not sure of login and not going to create acct just for this, so if you know someone with an acct let me know if prod Reddit share is correct for them. otherwise i'll just set it to same as fb/twitter and **assume reddit is working**?

as for LinkedIn, it takes 2 params (title and summary), which i've already been supplying it, but i don't understand its impact since only the title is shown:

![image](https://user-images.githubusercontent.com/4974087/111211238-cbc05b80-8593-11eb-8e93-139bde0f079a.png)

i can't test locally since LinkedIn is not digging my dev URL, so i'm not sure if it's getting the title from the app-level title (what we use on load by default) or the dynamic one passed to it, but I'm pretty sure it's the former because i'm already feeding it the same first part as twitter (e.g. the "Hasidic Yiddish - Languages of New York City Map"), and i don't see the "summary" (the  'An interactive map of...' part) anywhere. so, can we say **LinkedIn is as good as it will get?**

last but not least for social, i'll **assume Whatsapp is fine** since it also only accepts a title.

will address the email btn color in that issue when i get to it.

**Comment by abettermap** [comment]
(TLDR on that whole thing: **all i'm changing is FB**)

**Comment by rperlin-ela** [comment]
Sounds like we’ve done our best with what’s available — all good
