### ISSUE TITLE
"Label by": allow change during "Show by: None"

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#187]
(not really a bug but sort of)

“Home” view: restore support for “Label by” interaction when “Show by: None” is set. 

**Near-Future Jason:** there's a commit with JUST this. Figure it out from there.

**Comment by abettermap** [comment]
@rperlin-ela of all the requests in this SOW this was the one that made me the most uneasy (my time estimate 2-8 hours, ha), and i'm not off to a good start. I know it's very important to you though, so when you like me to throw in the towel? i've only got maybe 15-30 into it so far (30-60 if you include when i looked at it pre-signing-SOW), but 8 hours feels like a lot to put into this small issue so let me know what you think.

I haven't scoured the issues yet but i KNOW we talked about this at some point. i did find the commit that caused it, with a log message of:

> "Label by" dropdown: disable if "Show by" is none:
> 
> Since there are no longer separate label layers, this makes sense.

what's funny is that the disabling was implemented with **one line of code**, which seems like a misleadingly easy fix. however, it was in mid-september, long before we ever set up Airtable, so my assumption is that the one-line "undo" went out the window with Sheets and/or an MB-only approach. thousands of lines have changed since then and obviously not all are relevant but still plenty of things for me to investigate and detangle in pursuit of a fix.

sorry i can't give you a solid estimate on this one, but i've been pretty up-front from the beginning that it's a troubling uncertainty to resolve so hopefully no huge surprises! either way let me know how far you want me to take this.

**Comment by abettermap** [comment]
So, part of the issue is that the "Show by" setting dictates some of the impacts on "Label by", specifically font color:

Size + Language:

![image](https://user-images.githubusercontent.com/4974087/111231237-88bfb180-85ae-11eb-9ad5-63c50fd5b6f6.png)

World Region + Language:

![image](https://user-images.githubusercontent.com/4974087/111231271-a0973580-85ae-11eb-8189-8081f87d9e2e.png)

It's possible this had something to do with the reasoning behind the change (I made the label colors match World Region in the same PR, and I recall the new setup being more conducive to that), but either way it's pretty baked into the functionality. Currently I have **a dozen** spots commented out and hardcoded in the code, and I _still_ haven't been able to make the labels appear on their own.

The baking got turned up to 500 or so with Airtable in the picture. The value of the "Show by" determines which table to query in Airtable for the legend settings, and also which row from the Schema table to know more config stuff yet. There's also some config within the code to make matters worse, so it's all a fragile and delicate balance.

Basically when the dropdown changes, I have a bunch of logic set to jump ship if "None" is set, otherwise AT will try unsuccessfully to find a table called "None" and a row in Schema with "None" as the `name`. Obviously either one of those will break the World (Region 😆 ), so the way forward would require some rethinking of the whole setup.

For starters, what colors should the labels be if "None" is set in Show By? Airtable aside, it's still wondering MB-wise what to set the label colors to, and when the brother (or parent?) Show By gives it "None", it also breaks everything as well.

It's kind of a house of cards here, so let me know what you think. I'm thinking it would at a minimum have to be unraveled from the Show By and brought in as its own layer (again). OR, maybe something like this:

![image](https://user-images.githubusercontent.com/4974087/111233007-cc67ea80-85b1-11eb-83cb-aee22b908470.png)

![image](https://user-images.githubusercontent.com/4974087/111232467-c6253e80-85b0-11eb-8115-471a33d666dd.png)

(or vice versa with `Hide point symbols` unchecked by default)

In which case Label By could still lean on El Hermano o Padre, and the checkbox would determine visibility. I think I'd have to set the point size to like 0.1px and make them transparent, but seems doable. I would likely follow suit with a checkbox for "Label By" as well. 

Either way, **tons of work and not what I was anticipating whatsoever in this SOW**, so we can punt to the end of this week and maybe if there's like a _full day_ available, give it a shot. Otherwise there's not going to be time for the other issues, and we're not likely going to make the jump from "bug fix" to "sizable new functionality" without sacrificing some of them.

Thoughts?

**Comment by abettermap** [comment]
One related thing to mention- even with the points gone, the map is still going to be very crowded with labels turned on, especially with ultra-long Languages. The effort might outweigh the benefit in that sense, but I suppose it just depends how far the user is zoomed in.

I'm not optimistic about The Big Fix in this SOW, but maybe some small tweaks are available to the existing symbology that would prioritize the words a bit more than the points. Would that be useful?

**Comment by abettermap** [comment]
If I hard-code the size to 0 manually:

![image](https://user-images.githubusercontent.com/4974087/111346517-e7833a80-8643-11eb-8f37-c460944d8e45.png)

So that + the checkbox to "turn off" points (aka smoke and mirrors to set size to 0) seems like correct approach. And to axe "None".

**Comment by abettermap** [comment]
I'm seeing the light now haha. Knowing the ambiguity of the "points", I can understand why this is important. GIS-brain-maddening, but concept-important. 😄 

I'll see what it would take to checkbox it. Stand by, captain.

**Comment by abettermap** [comment]
@rperlin-ela BOOYAH:

![image](https://user-images.githubusercontent.com/4974087/111356926-739a5f80-864e-11eb-93c7-311f7bfcf91f.png)

> Where there's a will, there's a hack
> 
> --The Jason

## Questions

1. What should the **wording** be for the text next to the switch? Keep in mind this will affect icons (Status) and not just circles.
2. Should there be anything in the little popover triggered by the ℹ️  btn? I can go either way, it's just along for the ride since I copied the code from another component.

**Comment by abettermap** [comment]
Question 3: Should it be the way i set it up as shown (aka "Hide = on", toggled off by default) or the opposite ("SHOW language point symbols" and toggled on by default)? I prefer the former since the color of the switch competes with the legend symbols

**Comment by abettermap** [comment]
i thought maybe something like this for popout:

![image](https://user-images.githubusercontent.com/4974087/111357855-4ef2b780-864f-11eb-929a-cf1c37712fab.png)

and this for the switch text:

![image](https://user-images.githubusercontent.com/4974087/111357920-5f0a9700-864f-11eb-8d09-50d7b175bca1.png)

**Comment by abettermap** [comment]
(or scrap the ℹ️  entirely, i don't really care, it's pretty intuitive and you can mention it in Help for Power Helpers)

**Comment by rperlin-ela** [comment]
Genius. Where's there a J, there's a sun or a lamp(el) to light the way!

"Hide = on" is good as you have it.

I think scrap the ℹ️ entirely.

How about just "Hide points/icons"?

Yessssss!

**Comment by abettermap** [comment]
consider it scrapped, captain.

"Hide points and icons" I can do. We're out of minimal mode so we can afford to deslashify!
