### ISSUE TITLE
Standardize font sizes for paragraph-like elements

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#188]
- [x] “Home” view: World Map text: standardize font size for this and similar UI components.
- [x] “Clear/View Filter” message: follow font size standardization used in World Map text.
- [x] Census popouts
- [x] Census panel
- [x] Language profile panel (not the "read more" intro)
- [x] No comm. selected (related: #183)
- [x] Explore panels' intro (e.g. "Common language name in English" at `/Explore/Language`)
- [ ] Any others?

Some of those might not apply but should really just be able to reuse a single component w/the same color and font size.

**Comment by abettermap** [comment]
@rperlin-ela FYI I'm going to demote the World Map text in this chunk of tasks even though it was more a part of the relocating Location Tools. Might give us a little better feel for how the font size looks in its new home-within-a-Home.

**Comment by abettermap** [comment]
Looks pretty good with the standardized fonts and below legend:

![image](https://user-images.githubusercontent.com/4974087/111236904-90388800-85b9-11eb-86f9-2528ac6f72c1.png)

Collapsed:

![image](https://user-images.githubusercontent.com/4974087/111236949-a8100c00-85b9-11eb-8f5b-bcad7cf86fbd.png)

Shouldn't be much convo about the other items in this issue but just holler if you see something off about the world map part.

**Comment by abettermap** [comment]
@rperlin-ela Standard enough for the first panel (the warning and world map text)?

![image](https://user-images.githubusercontent.com/4974087/111343879-75a9f180-8641-11eb-87e7-0674218d1272.png)

**Comment by rperlin-ela** [comment]
Looks good to me!

**Comment by abettermap** [comment]
I didn't really specify in the issue but I'd rather not "standardize" the intro where it's okay to be small text:

![image](https://user-images.githubusercontent.com/4974087/111367081-f70d7e00-8659-11eb-94a1-46acaa6550b0.png)

The following paragraph will do though

**Comment by rperlin-ela** [comment]
Totally— not a rigorous assessment, but I think in my head there are three “standards” (small, regular, and large), and the idea is to herd everything to fit those?

**Comment by abettermap** [comment]
Not sure. If I would've adhered more closely to Material UI (the component/style framework we're using), there are A LOT more: https://material-ui.com/components/typography/#component

This is something that would've been avoided if I'd done a true Style Guide, but alas. 

I think we're on the same page though. I would agree with small as the text I showed above, and things like "World map..." medium. Not sure if large refers to any paragraphs, or headings too (many sizes of those in the app), but i'm just doing paragraph-y things here.

The orig request was actually just for Clear Filters warning and any Home paragraphy stuff, so the rest is just a bonus anywya.

**Comment by rperlin-ela** [comment]
Yep, sounds good!

**Comment by abettermap** [comment]
Only tangentially related to fonts but i got sucked in so maybe something good for this issue or the "move Location Tools to Home" or both or neither, but any thoughts on this? We don't really have much depth in the UI (it's often called "elevation"), so just trying to bring it out a little.

![image](https://user-images.githubusercontent.com/4974087/111377639-815bdf00-8666-11eb-936d-e46afbc2fb1a.png)

**Comment by abettermap** [comment]
or more compartmentalized:

![image](https://user-images.githubusercontent.com/4974087/111377843-c253f380-8666-11eb-915b-d763a0031b5b.png)

elevation aside, the whole first panel is just kind of a waterfall of flatness and heading-less sections, so something to break out the concepts would be useful to some.

**Comment by rperlin-ela** [comment]
Either seems nifty to me, maybe a nod to the compartmentalized— we’ve got Location search coming there— but up to you, as long as it’s straightforward!

**Comment by abettermap** [comment]
Not sure we finalized the plan for that, and I don't think I wrote the issue yet, but yeah I'll work it all in there. Would still like to make an obvious tab or similarly easy way to switch between Search and Location Search in the same spot. I'm thinking the GPS and Counties/Neighb toggle/s don't need to be part of that party.

Anyhoo cart before horse, i'll run with the elevation and you can critique heavier when i push. Cross the Loc Search bridge later.

If you ever change your mind on the legend heading, I think "Legend" would go a long way. It's not apparent at first what all the dots mean, or that Show By affects them. For the latter, my vote would be single-groupage from a relatedness standpoint, although compartments do make it stand out nicely.

How about this (not in this branch though):

"Search By" up top, in a group (the elevation thing is called "Paper"), with two nav tabs, one for our omnibox (active by default), labeled "Language", and one for location, labeled... Location. That's it for that Paper.

Second Paper has two tabs: "Legend" (active by default, showing all our current stuff including dropdowns) and "Map Tools" which contains our catch-alls (County toggle, GPS, etc.). The latter (Map Tools) strikes me as "not used super often but sometimes", so it's not top-shelf like Search stuff, and is even secondary to Legend.

I know that's a lot of visual but just trying to stir the Home pot since we're going to have some sizable reorganization soon-ish.

**Comment by rperlin-ela** [comment]
Can’t remember what I said before, but I’m not against having the word “Legend” there. Rest of your proposal, from what I can picture, sounds good.

**Comment by abettermap** [comment]
Cool, I pushed up what I had so far so let me know what to axe/keep.

Reminder to Near-future PR-reviewing Ross to scour the UI for "Any others?" item mentioned in issue. I "think" I got them all but let me know of any obvious misses.
