### ISSUE TITLE
Try new color scheme

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#189]
Questions:

1. are the primary's the same for all? **YES**
2. are the primary's the same as current? **NO, at least not using the color dropper in Dev Tools. I confirmed that I gave Julia the correct colors via email though, and they haven't changed since then.**
3. are secondaries same for light/dark scenarios? **YES**

Take screenshots of each of these applied to the theme (might just be secondaries depending on above answers):

![image](https://user-images.githubusercontent.com/4974087/111042675-c8926780-83fb-11eb-8730-560302b87005.png)

**Comment by abettermap** [comment]
Ok super related to #190 (the link color part) so I'm not sure what to try first. Also I'm not necessarily the best to ask about color so @fiddleHeads  and @rperlin-ela we might need you both (or anyone else who has color opinions) to settle some decisions.

Right off the bat, the first "blue" set I tried seems like a welcome relief to the all-green approach, including for links:

![image](https://user-images.githubusercontent.com/4974087/111387614-9c811b80-8673-11eb-895d-f91fff39c1fc.png)

maybe a little intense for buttons:

![image](https://user-images.githubusercontent.com/4974087/111387671-b589cc80-8673-11eb-949b-5aff967762b9.png)

but i think it really depends on the context, because this doesn't seem as intense:

![image](https://user-images.githubusercontent.com/4974087/111387741-d4885e80-8673-11eb-93ac-09615e0a74c8.png)

I don't hate it in the table either:

![image](https://user-images.githubusercontent.com/4974087/111388063-537d9700-8674-11eb-8dc8-53584327be77.png)

switches are definitely a bit much:

![image](https://user-images.githubusercontent.com/4974087/111388352-b7a05b00-8674-11eb-9779-c177894a344d.png)

### Next steps/any thoughts?

Like I said, that was only the _first_ palette I tried, so just **wondering if there's any initial thoughts on the "blue" concept**? I'm open to mixing and matching green/blue too, even though SOW says across the board for some things (that's not how it works in code, there's a handful of spots to change certain bits, and I'll likely miss some so you'll have to point those out if i do).

My feeling is to go with:

1. one color (whether green or blue) for all links and link-like things (e.g. table column headings)
2. same color for all buttons, switches, and other input-y control things
3. the color for 1 and 2 can be the same (or at least same palette), but stick with the same for all the instances like i said

**Comment by abettermap** [comment]
(oh and ONE color for things like panel title bar and such)

tried the last palette on the page and definitely don't mind that one either:

![image](https://user-images.githubusercontent.com/4974087/111389127-07335680-8676-11eb-9cfa-e8fcccb9165a.png)

again, nice break from the 24/7 green (note that the links here are the old color, only the btn color is new, i just haven't changed links yet):

![image](https://user-images.githubusercontent.com/4974087/111389251-4661a780-8676-11eb-86b4-f410ec6c5207.png)

for comparison, both the blue's i showed are way less intense than the red:

![image](https://user-images.githubusercontent.com/4974087/111389353-7446ec00-8676-11eb-93c3-6711f0426962.png)

keep in mind we also have census symbology set to a green palette as well, so ratcheting down the greenness of the UI would be nice there too.

**Comment by abettermap** [comment]
gonna have to veto the second palette (Option 2), the links are pretty intense:

![image](https://user-images.githubusercontent.com/4974087/111389782-2d0d2b00-8677-11eb-999d-51801092c3bf.png)

and i feel the buttons are a bit too vibrant:

![image](https://user-images.githubusercontent.com/4974087/111389847-4ca45380-8677-11eb-8bca-55ff685efe83.png)

not opposed to Option 4 for buttons:

![image](https://user-images.githubusercontent.com/4974087/111390090-c3d9e780-8677-11eb-94b8-7a30230c2837.png)

sorry i know this is a million things and super visual but just trying to isolate some scenarios and options so let me know if you've got any gut feelings so far! happy to make tweaks in-browser like this, it's quick

**Comment by rperlin-ela** [comment]
I’m not the best person either, so I’ll defer, and I think consistency or division of labor is the main thing. The blue does feel a little intense somehow, like I wonder how a color more like “South America” would look. But in principle a blue-green combo sounds good. I don’t love the blue links showing up in Description right now where everything else is green. But the all-blue table or census pop-out look pretty good to me (not the toggles). That’s all I got!

**Comment by rperlin-ela** [comment]
I meant the darker blue (Option 1)— actually like the look of Option 4

**Comment by abettermap** [comment]
Ditto on Option 4. That's two in favor! @fiddleHeads or @markturin , any opposition to Option 4 for buttons and related UI controls? No pressure, you can blame me if something looks bad 😃 Just trying to rule out any hard "No's". ￼

**Comment by abettermap** [comment]
Shoot, big typo- this was actually Option 3 I believe: https://user-images.githubusercontent.com/4974087/111390090-c3d9e780-8677-11eb-94b8-7a30230c2837.png

**Comment by rperlin-ela** [comment]
Yep, that’s the one

**Comment by fiddleHeads** [comment]
So are you thinking Option 3 or 4 according to the pallettes up above? I'm a little confused. I think I'm good with either, though.

**Comment by fiddleHeads** [comment]
Sorry, I inadvertently closed the issue and then had to reopen it. So are you thinking Option 3 or 4 according to the pallettes up above? I'm a little confused. I think I'm good with either, though.

**Comment by abettermap** [comment]
Ok, let's simplify this. I know colors can be a dead-end convo due to subjectivity and a lack of knowledge (myself included), so if you have a chance and an opinion, **let me know if this looks sufficient** (it's Option 3 from Julia's doc): https://deploy-preview-199--languagemapping.netlify.app/

It also addresses the link color item in #190.

**Comment by fiddleHeads** [comment]
Thanks Jason. I think it looks great.
