### ISSUE TITLE
Color/style/visibility UI improvements

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#190]
- [x] Census dropdown: make results background black (same as the search box in “Home”)
- [x] Hyperlink: standardize all instances using theme color instead of light blue. **TBD, kind of based on #189. The idea is that all hyperlinks are the same color throughout the app**
- [x] “Details” and “Language profile” views: improve visibility of Audio/Video links by making them more prominent than the surrounding elements, either through a different element type such as a button, positional changes, or simple style adjustments.
- [x] “Share via Email” button: colorize to avoid misconception that the button is disabled.
- [x] Panel “breadcrumbs”: underline links to make their purpose obvious.

Use light green everywhere but do #189 first so we know how it looks.

**Comment by abettermap** [comment]
@rperlin-ela trying a few options for the Audio/Video thing:

### 1 - Separate line and pronounced

![image](https://user-images.githubusercontent.com/4974087/111506117-e9fe9680-870e-11eb-9a25-590032aff311.png)

### 2 - Same line, pronounced, same order as current

![image](https://user-images.githubusercontent.com/4974087/111506318-20d4ac80-870f-11eb-84ef-b305313a3ac5.png)

### 3 - Same line, pronounced, first

![image](https://user-images.githubusercontent.com/4974087/111506443-3f3aa800-870f-11eb-8e04-cafcff7585ae.png)

### 4 - Same line, outlined, first

![image](https://user-images.githubusercontent.com/4974087/111507024-d869be80-870f-11eb-8af1-0ead0a1e5d67.png)

### 5 - Grouped
Slightly more work for this since it's a new component but still easy, although not sure it helps our cause: https://material-ui.com/components/button-group/ (basically any of those on that page)

### 6 - Distinctions
I like **option 4** above, but i think it should be distinct from the chips via subtle border (I know, getting bizzzay up there, but it feels worth it):

![image](https://user-images.githubusercontent.com/4974087/111507990-cf2d2180-8710-11eb-9387-d5088bb8294f.png)

Keep in mind we could potentially scrap the Language name with the incoming "Up one level" btn for more space:

![image](https://user-images.githubusercontent.com/4974087/111508440-537fa480-8711-11eb-9161-a1517741d4ae.png)

## Takes

### Mine
**I like Option 6**

### Yours
Whatcha got?

**Comment by abettermap** [comment]
Sorry Ross, gonna be mixing some convos here since I smashed them all into one issue, but shifting gears to the email btn...

So, the current gray DOES actually resemble a semi-standard (if there is such a thing), but we can't use the "standard". So I just tried a bunch of randos (don't worry about the code, just give me the number):

### 1 -  hsl(45 54% 55% / 1)

![image](https://user-images.githubusercontent.com/4974087/111516016-13242480-8719-11eb-93f6-bf9166238d97.png)

### 2 - hsl(32 54% 55% / 1)

![image](https://user-images.githubusercontent.com/4974087/111516092-259e5e00-8719-11eb-89dd-b9fb9c3696d9.png)

### 3 - hsl(23 54% 58% / 1)

![image](https://user-images.githubusercontent.com/4974087/111516200-42d32c80-8719-11eb-8cfd-3d35bdb6167e.png)

### 4 - shoot, lost it!

![image](https://user-images.githubusercontent.com/4974087/111516355-6ac29000-8719-11eb-97bd-4c8ef91f63f9.png)

### 5 - #202020
Not quite as disable-y as current:

![image](https://user-images.githubusercontent.com/4974087/111516539-a0677900-8719-11eb-8367-c4536407e534.png)

I'd probably go with **option 3** myself. There are millions of colors, hard to just pick one at random (all the buttons had baked-in defaults, which I used), especially w/the competing surrounding elements' colors, you know?

**Comment by rperlin-ela** [comment]
Option 3 for the email button looks good to me!

**Comment by abettermap** [comment]
Decisive! Done. Let me know on the Audio/Video stuff, and hopefully an easy Yes/No on the B-crumbs, which I made the normal white instead of subdued, with the underlines the "secondary" text color (the off-white you see in some paragraphs). Keep or axe?

![image](https://user-images.githubusercontent.com/4974087/111519411-ab6fd880-871c-11eb-83f1-7934336b2901.png)

**Comment by rperlin-ela** [comment]
﻿
Give me a few hours on the other stuff, but breadcrumbs look good!

**Comment by rperlin-ela** [comment]
On the right track, for sure. I think I like Option 6 too, but don’t scrap language name, I think, rather be repetitive than confusing, and I don’t want to hide the Profile— I’m still thinking through exactly what I want to show there but it’s a nice slot. So I think “Read more” stands.

**Comment by abettermap** [comment]
Sounds logical to me. Any feelings on the top and bottom borders in Option 6?

**Comment by rperlin-ela** [comment]
Up to you— I like some bordering but not too much and not sure about dashed

**Comment by abettermap** [comment]
Ok I'll play w/some options. Thought the consistency would be good with the dashed in the census popout but they're not the same concept I guess, and maybe dashed was a poor choice there as well.

How about solid line on top or bottom or both (I'll make that decision before I push) using the pictured gray, but a more pronounced line (either through color, height, both, or a fancy lil guy [like the bottom one here](https://css-tricks.com/examples/hrs/) to separate the whole intro section from whatever is below it?

**Comment by rperlin-ela** [comment]
Hmm, dashed in the census pop-out I feel at peace with, but yeah I like the sound of what you describe, go for it

**Comment by abettermap** [comment]
Sweet.

Sorry to pummel, one more related thing...

New layout breaks on mobile because Clear Selection wraps:

![image](https://user-images.githubusercontent.com/4974087/111543282-72456180-8738-11eb-8add-04b2749f9395.png)

so are any of these acceptable to Average Human Users™?

![image](https://user-images.githubusercontent.com/4974087/111543403-9f920f80-8738-11eb-8bc9-90a3fa12da00.png)

![image](https://user-images.githubusercontent.com/4974087/111543449-b0428580-8738-11eb-9066-f1bfe69cfa80.png)

![image](https://user-images.githubusercontent.com/4974087/111543480-bafd1a80-8738-11eb-82b7-8ec9d6633d49.png)

![image](https://user-images.githubusercontent.com/4974087/111543511-c4868280-8738-11eb-9d13-a69188d02f81.png)

i pasted screenshots since the icon gives it the feel too. but the icon kind of sucks (i think it's a "collapse" btn). so would any of these support whatever-text-you-pick?

![image](https://user-images.githubusercontent.com/4974087/111544008-7b82fe00-8739-11eb-9f0c-45159d47d17a.png)

![image](https://user-images.githubusercontent.com/4974087/111544053-89d11a00-8739-11eb-901a-0c03856545e0.png)

I'd probably run with "De-select" myself (i think GIS calls it Unselect) combined with `IoIosCloseCircleOutline`.

**Comment by rperlin-ela** [comment]
IoIosCloseCircleOutline is a good call and I think “Clear” might cover it since we do use that word in other places. De-select seems good too.

**Comment by abettermap** [comment]
Is it elegant in here or is it just this lil symbol guy?

![image](https://user-images.githubusercontent.com/4974087/111549681-3adbb280-8742-11eb-86fe-ab796e9b3352.png)

Adds a little flair to supplement the big-cap first letter below, but... regardless of what we do up top, there's less and less of a chance that the user will see the description below without scrolling on mobile in the scenario like above (2 lines of chips, Read More, etc.), and same for 2-line Language names as well. Don't forget, it's going to be pushed down even _further_ once "up one level" joins the party. There's just A LOT going on in there, and i'm not sure how to cram it all in without being illegible or tacky.

Re: the top/bottom border, i just scrapped it since i think the vertical spacing is enough to distinctionize from the chips and the Read More but let me know what you think.

Related: the "read more" has never really shown up well against the stuff behind it, even when it was a green link. any suggestions??

When there's no lang-level descrip, and 2 chip rows, fits "ok":

![image](https://user-images.githubusercontent.com/4974087/111550275-67dc9500-8743-11eb-9e67-3b06cb4c0c7f.png)

i think we're going to lose a good bit when we up-one-level it though. that link will need reserved space for long words without overlapping the main heading. cross that bridge i guess.

i'll push what i've got, probably been looking at nitpicks too long!

**Comment by abettermap** [comment]
So after a spell away from the computer and 3/4 of an IPA, here's what I'm thinking on the fancy thing. 

- Double line is too much. Back to single. Flew too close to the sun. 
- It needs to be a more subtle shade than the disabled audio/video buttons. Too similar. Like it should be juuuust enough to stand out from the _background_ of the panel behind it. It's not actionable and not even disabled, it's just an arbitrary boundary between two UI pieces. 
- Could probably be a bit further down from the buttons above it. Although maybe less important once we're back to one line. 
- I do like the fancy symbol though. 

My two cents.

**Comment by abettermap** [comment]
@rperlin-ela For the audio/video buttons, now that I have made them stand out simply with bold text, do you care if I put them back in the center? It looks weird all spread out on certain screen sizes. ￼￼

**Comment by rperlin-ela** [comment]
I agree— back in the center
