### ISSUE TITLE
“Language profile”: support language-level text (NOT description)

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#193]
“Language profile” view: support language-level text, independent of the current language-level descriptions in Airtable, and include it in the introductory section in the same style and functionality as that of the “Details” view. This will involve introducing a column in Airtable, similar to current open-text description columns, and consultation will be provided to Ross as needed.

Part of the reason for this is to allow language-level info that is not applicable to the intro "read more" of Details intro.

**STATUS**

Ross already created a new table, just need to knock out the column/s. Jason will consult.

**Comment by abettermap** [comment]
@rperlin-ela i think this one might be a little more work than the others since it's not tied to Language table the same way and will also be used different in the code and UI. I'll take a stab when I get to this issue, and from what I see you've got a good start on it so I'll let you know what I've changed when I get there.

**Comment by rperlin-ela** [comment]
Sounds good

**Comment by abettermap** [comment]
Question on the `Language Profiles` table: should I bank on the `id` column always being a Language? That wasn't the case for `Language Descriptions` (intentionally), just wondering if it will be like that for this new table. It's fine either way but I can basically just lean on the `name` field from `Language` for my queries and maybe not even need these fields in `Language` table:

![image](https://user-images.githubusercontent.com/4974087/111706458-f4e92200-8807-11eb-84db-e7974b6322ae.png)

Smells kinda fragile that way since there's not really any validation and it's up to you to keep the names exact between the two tables manually. Personally I'd say let's just roll with the Link + Formula like I have it, then you'll have validation AND be able to sort/filter on the Link column.

**Comment by abettermap** [comment]
I'd say unless you're opposed what i've got in screenshot above, let's keep. I believe this is what you asked for and it's pretty straightforward code-wise:

![image](https://user-images.githubusercontent.com/4974087/111707324-73928f00-8809-11eb-86bd-6c25546dedd6.png)

also i'm ready to de-elegantize the intro if you are, haha. it had its time in the sun, now it's time to go.

**Comment by rperlin-ela** [comment]
Looks like you’re nailing it. And probably good to leave the AT table as it is. Normally I think the id column would be a language, but if it’s just a matter of saving a column I’d leave us with a little more flexibility in case there are situations. 

I’ll miss the elegance of yore, but glad to see Johnny Minimal back in town

**Comment by abettermap** [comment]
ha so is that an Aye for de-elegantizing then?

feel free to delete this field:

![image](https://user-images.githubusercontent.com/4974087/111709048-8d81a100-880c-11eb-9227-d664ac67beb1.png)

you'll get a warning:

> Deleting this linked field will convert the "Language" field in the "Language Profiles" table to a single line text field type. Are you sure you wish to delete this field?

it's fine. just delete the field it produces along with these if you don't need them in the `Language Profiles` table:

![image](https://user-images.githubusercontent.com/4974087/111709293-f537ec00-880c-11eb-99f5-e89041e39a88.png)

**Comment by rperlin-ela** [comment]
Aye

Ok, deleted that one and will now delete “Language 2 (2)” and “Language 2"

**Comment by rperlin-ela** [comment]
Don’t shoot me for asking, just a question— does the “Read More” component have to say “Read More” 24/7 even if the text is totally visible without expanding? Reason I ask is, for certain entries, I could use that space for a very simple little disclaimer instead of putting it in the body of the description, see /details/224 for an example. Just an experiment and a thought— and I totally understand if you hate the idea or if “Read More” comes with the territory, just askin'

**Comment by abettermap** [comment]
ha, no shots fired. good point. unfortunately the calculation for what determines "is totally visible" is not super straightforward. The number of characters and words that fit in a certain space is difficult to determine, especially on multi-lines like that. Not to mention our design is responsive, so the font size and padding and margins and layout in general will fluctuate as the screen size gets smaller.

That said, your question made we wonder if there's a CSS property for the multi-line ellipsis overflow, and now there IS. This would let me truncate and ellipsize at a certain number of _lines_ rather than by line width (which is how it's been for ages and is basically useless for more than one line).

Not sure if specifying the "number of lines cutoff before ellipsizing" helps your cause, but if so then let me know. If it's any calculations like "what will be visible at X screen size and how many characters would fit"... no sir.

**Comment by rperlin-ela** [comment]
If I understand right, that could help. I could probably figure out by trial and error what a line means and adapt. The way it seems now, we don’t need “Read more”/ellipsis if it’s just one “line", so we could start with that. 2+ could have the “Read More”. If we don’t nail it after a try or two, we can scrap!

**Comment by abettermap** [comment]
Ok, that sounds promising. See my comment just now in the last PR though, I/we need to back off on the blur between what actually needs to be completed and the low-hanging UI fruit. I'll try to restrain from passing on more ideas when it's way out of scope, or at least idea-dump into GH Land for future use.
