### ISSUE TITLE
3D/2D: don't force, allow setting consistently

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#194]
Allow toggling between 2D and 3D in the map (on a per-session basis, not stored between sessions) via a button in the map navigation controls, and remove the current functionality of forcing 3D when a community is selected.

Always show the btn too.

**Comment by abettermap** [comment]
@rperlin-ela you've been on a roll with icons these days. I'd like to either do:

1. one for 2D and one for 3D and it just changes back and forth on click
2. or use the existing one and just make it look active/inactive
3. or active/inactive with a new icon

I could see it going several ways so let me know what you think.

**Comment by rperlin-ela** [comment]
Took a quick look (like maybe a cube says 3D) but I think I’m out of my depth and would just go with your option 2 since the existing one is not bad

**Comment by abettermap** [comment]
I'm thinking the inactive is not the best approach since the buttons are already blackish. Disabling/inactivizing usually entails some level of grayness or desaturating the current color, but since we don't have any color I'm leaning towards a button that alternates between two states:

1. (Default): An icon that represents "3D", or even just says "3D". When clicked it will make the map 3D.
2. Vice versa

There are probably more logical UI controls we could use (it's very switchy/toggly) but if its permanent residence is below the Zoom controls then I feel like icon or text swapping is the way to go. 

Open to ideas, but that's all i've got at the moment.

**Comment by rperlin-ela** [comment]
Yeah, the way Google Earth does it is fine by me— little thing thart says 3D switches to 2D and vice versa

**Comment by abettermap** [comment]
cool. feels pretty natural to me, although i could see users thinking that the button text refers to the _current_ pitch (e.g. 2D = "i'm looking at 2D right now"). but my argument would be that whatever the button shows, that's what the action is, since we're already doing that w/the other btns (zoom in/out/reset).

either way it's working well except for the mobile popup off-centering but i'll circle back either after SOW3.1.4 or during Week 4. it worked in the past with just the "reset pitch" btn and i don't want to degrade functionality.
