### ISSUE TITLE
Improve cross-panel interactions

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#195]
- [x] “Home” search box: make Language group headings linkable to “/Explore/Language/Language Name”. **If this starts looking hard, jump ship. Was just a minor request.**
- [x] Add a toggle near the Census search box to turn off language points using the same functionality as ~“Show by: None”~ **turning on "Hide points and icons"** in the Home panel ~symbology dropdown~.

**Comment by abettermap** [comment]
@rperlin-ela for the ELA data toggle in Census, which of these options seems better?

1. Instead of a _toggle_, use a _button_ saying "Hide ELA data" or whatever. If either the ELA points or labels (or both) are visible, the button is **enabled**, otherwise disabled since the ELA stuff is already hidden.
2. A toggle as described in the issue above. The toggle's enabled/disabled state would be determined in the same way as the button option.

To me Option 1 feels more natural and follows the same thinking as the "Show in map" of the Census popout: if that census language is already selected, the button is disabled.

**Comment by rperlin-ela** [comment]
Nice. By “otherwise diasbled since the ELA stuff is already hidden”, I assume you mean someone has doine “Hide points and icons” on Home and there are no labels.

If you think button over toggle, let’s do that. I didn’t see this thing as necessarily being in the pop-out, only in the more spacious Census panel, if that makes any difference.

**Comment by abettermap** [comment]
Actually it **does** need to be a toggle because if the user clicks a _button_ which becomes disabled after click and then changes their mind, they won't be able to undo their last action without going to the Home panel, and they may not even know about the functionality there in the first place. So yes to original toggle suggestion. ￼

> By “otherwise diasbled since the ELA stuff is already hidden”, I assume you mean someone has doine “Hide points and icons” on Home and there are no labels.

Correct. Although now that I think of it we are going to need a checkbox in Home to show/hide labels just like we're doing with the points. Otherwise the "hide all ela data" switch won't know what "Label by" value to restore (Language or Endo) when "hide ela..." is turned back off and showing labels. 

There should be plenty of room for the labels toggle in Home, either through minimal text and/or foregoing my "elevated" group in Home. I also like the consistency with the show/hide points toggle. The None stuff probably never should have gone into dropdowns anyway. Bad Jason!

Don't worry if the logic doesn't make sense, I just need an all-clear from you to add that extra checkbox for labels and remove it from the Label By dropdown. ￼

**Comment by abettermap** [comment]
Oh and yes to the panel-only census inclusion for the ELA data toggle, not the census popout.￼

**Comment by rperlin-ela** [comment]
Toggle called “Hide ELA data” in Census sounds good, and I hope it will help people keep straight what’s ELA and what’s census, though elsewhere we haven’t really flagged very clearly that it’s ELA data.

A “Hide labels” set to on, just under “Label by” and right of “Hide points and icons”, sounds like it should be good. Not sure how the dropdown would look by default, but it sounds like you’ve got idea. Whatever we can do to make this as intuitive as possible… To create a clearer parallel, what do you think about changing “Show by” to “Symbolize by” and changing “Hide points and icons” to “Hide symbols”?

**Comment by abettermap** [comment]
Johnny Minimal, in the house! Ha I can dig those changes, although I thought "symbolize" was too GIS-y to some? Fine by me though. I think "Display by" works too, but symbolize is most accurate and reinforces the "symbols" in "Hide symbols".

> Not sure how the dropdown would look by default

It would just be `Language`, no? As for the initial state and text of "Hide Labels", which of these makes more sense?

1. "Hide Labels", switched on by default
2. "Show Labels", switched off by default

I could go either way. Part of me likes having both of those toggled off on load, but another part likes the consistent behavior and wording for both toggles.

Code-wise the logic might get a little screwy mixing it up like that, so unless you have strong feelings about "Show Labels", probably best to stay consistent w/Hide.

**Comment by rperlin-ela** [comment]
All good on this. I think I’d give the nod to the consistency of “Hide Labels”, and I guess still off by default

**Comment by abettermap** [comment]
Omni part was a piece of cake. Want it like this:

![image](https://user-images.githubusercontent.com/4974087/111805148-65d71b00-8896-11eb-90cb-7558385c84d2.png)

Or bold with more char spacing?

![image](https://user-images.githubusercontent.com/4974087/111805625-cf572980-8896-11eb-97f5-f825ac5cdbc4.png)

or larger font

![image](https://user-images.githubusercontent.com/4974087/111805827-04637c00-8897-11eb-9c0c-f7f181788fe3.png)

underline

![image](https://user-images.githubusercontent.com/4974087/111805943-18a77900-8897-11eb-8001-1c1398b3fd93.png)

some kind of little char or icon

![image](https://user-images.githubusercontent.com/4974087/111806417-910e3a00-8897-11eb-8026-cb41b4860397.png)

IMO they all suck in different ways but i'd lean towards the first option or the second.

**Comment by abettermap** [comment]
*sorry, the third: larger font

**Comment by rperlin-ela** [comment]
yeah that one, larger font!

**Comment by abettermap** [comment]
k well i spoke too soon about piece of cake. the functionality/linkage is fine, and so is the font, but... i can't get it to stay "sticky". you know how when you scroll, the language heading "sticks" to the top until you get to the next one? that.

anyway got over an hour into that (an hour and two minutes since i posted the screenshot of it working) so gonna have to circle back later if it's a deal-breaker. i like "sticky" but it's not overly useful here since many of the languages only have one location. plus it's only really noticeable if you're scrolling aimlessly versus actually typing something deliberate in the box (which is the main point of it).

i could see arguments for non-sticky too, like it saves space, so i'm fine without sticky if you are, just don't want to rob you of any existing features!

**Comment by abettermap** [comment]
jeez Louise. sticky isn't working in prod anyway so nevermind. disregard, captain!

**Comment by abettermap** [comment]
Ok I knocked out both of the tasks but I can see convos about the census one getting hairy, so here's my take (and @fiddleHeads feel free to weigh in. i'm not sure if you were the requestor on this one but we won't turn down a third voice either way)...

The main problem is that hitting this switch:

![image](https://user-images.githubusercontent.com/4974087/111828333-c1ae9d80-88b0-11eb-8a9c-7a0eea0b22aa.png)

...heavy-handedly turns the points and labels on or off regardless of the previous state. Example scenario:

1. user has Endo's on but points off
2. goes to Census panel
3. switch is turned off since labels are shown
4. user clicks switch. labels and points both hidden like we'd expect.
5. user clicks again, but now both the labels AND points are shown

rather than go down the road of keeping track of whether or not the points and labels were already hidden or shown in the Home panel, can we just **adjust the wording of the toggle in the Census panel** to reflect what the switch does? it's semi-confusing as it is, especially if user isn't aware of the show/hide toggles in Home. Maya if you're not in the loop we have added these to Home:

![image](https://user-images.githubusercontent.com/4974087/111828792-6f21b100-88b1-11eb-92e0-5f6569da6ce0.png)

in my experience with UI pieces that affect other UI pieces without the user's knowledge, while well-intended the costs of convoluted code are greater than the benefits to the user. i knew there would be some implications when i started thinking through the UI process, but i don't want to make it more complex than it needs to be since it's kind of a bonus feature anyway (the user can already toggle the stuff in Home).

to make it simpler for them, i suggest one or a combo of these:

1. change the wording of the text to say bluntly that it turns stuff on or off regardless of what was set before. this could be via one of those ℹ️  buttons or directly in the text
2. if it makes it easier, include a link to Home like  `More options` or something:
    
    
![image](https://user-images.githubusercontent.com/4974087/111830230-48647a00-88b3-11eb-92a2-07dfcd75d732.png)

3. change the wording of the toggle dynamically:

![image](https://user-images.githubusercontent.com/4974087/111829662-962cb280-88b2-11eb-95eb-6572ebc26f68.png)

![image](https://user-images.githubusercontent.com/4974087/111829621-890fc380-88b2-11eb-8da1-adca407eaea7.png)

I pushed a deploy so let me know how it "feels": https://deploy-preview-201--languagemapping.netlify.app/

**Comment by rperlin-ela** [comment]
I get the problem, and this is a good way of thinking about it, but I’m checking the deploy… and it seems great, like the thing remembers what I went in with. Could that be, or am not I getting? I’ve tried it with World Region, Size, Status, and different labels, and when I slide the new Census toggle back and forth it seems to go back fine to what I just had. With filters too! It’s just what I would expect as a user.

For the text I’d go with “Hide ELA symbols and labels”. I still feel we could use a line or something somewhere besides Help clarifying what’s ELA data vs. Census data. Maybe you won’t mind me slipping that in somewhere when we give Census its own beautiful panel...

**Comment by abettermap** [comment]
> Hide ELA symbols and labels

oops, good catch!

as much as i'd like to say we've got this issue in the bag, i don't think you tried the scenario i mentioned above (the 1-5 steps), or maybe it's not a concern but i'm guessing the former so i'll break it down:

defaults, on load:

![image](https://user-images.githubusercontent.com/4974087/111835760-f9224780-88ba-11eb-9bc4-d70fad5040dc.png)

![image](https://user-images.githubusercontent.com/4974087/111835779-00e1ec00-88bb-11eb-9a1f-1501abfb6d09.png)

and when i turn this on, it hides everything as expected:

![image](https://user-images.githubusercontent.com/4974087/111835824-11926200-88bb-11eb-9ae9-dddaad9ce85a.png)

however, when i turn it back off:

![image](https://user-images.githubusercontent.com/4974087/111835779-00e1ec00-88bb-11eb-9a1f-1501abfb6d09.png)

it's now showing the labels:

![image](https://user-images.githubusercontent.com/4974087/111835916-338be480-88bb-11eb-9761-0a816bf8cf0c.png)

either way, i'm going to throw this in the "circle back later" pile (if you didn't catch it through your testing so far) and knock out #196 . if/when it starts to become a problem, i'm thinking i could just have an additional property in the code to "override" the current state of the two Home toggles, although that might be a different kind of confusing code-wise. i'll have to think on it.

> Maybe you won’t mind me slipping that in somewhere when we give Census its own beautiful panel...

i think that falls closely enough into the ol' Census panel task. If you let me know what the text is in a new GH issue which also includes the SOW details about the Census panel task, you've got yourself a deal. ;)

on a related note i was wondering if this:

![image](https://user-images.githubusercontent.com/4974087/111836536-11df2d00-88bc-11eb-916a-2453f0139a75.png)

could use the slim version as in the popout:

![image](https://user-images.githubusercontent.com/4974087/111836598-2cb1a180-88bc-11eb-9177-2ba2c7516b1a.png)

or perhaps the 3-line truncation w/ellipsis i mentioned for Read More yesterday. that could get confusing w/the existing `More info` link though. or maybe it won't be an issue with all the newfound space of dedicated Census panel real estate.

**Comment by rperlin-ela** [comment]
Got it, was moving a little quick. Now I think I see: it does fine with everything except that it turns on the labels even if you had them off (by default or otherwise). That’s not too bad, and seems ok to think on and return to.

Sounds good about Census panel text. Yeah the slim version seems fine and that’ll help squeeze in a touch more about ELA data.

**Comment by abettermap** [comment]
> except that it turns on the labels even if you had them off (by default or otherwise)

right and same goes for symbols.

i also could see the accidentally-forced-on labels as a happy accident. like "whoa cool didn't know i could do that" if the user hadn't played with the Label By dropdown yet.

**Comment by fiddleHeads** [comment]
Just catching up here and agree it doesn't seem too bad that the labels turn on even when they were previously off and could perhaps even be a neat surprise.

I also think the slim version for the Census panel text seems fine.
