### ISSUE TITLE
On Census language change, zoom to initial extent

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#196]
On Census language change (either via Census search box or the "Show in map" button of the Census pop-out), zoom the map to the initial default level. Enable this functionality by default, but add a nearby toggle switch to disable this behavior on demand.

**Will need some wording for the toggle.** Ideas/options for terminology:

- "home"
- "full"
- "default"
- "initial"
- "original"

e.g. `Auto-zoom to initial extent` is how my brain wants it since it's not "full". No strong feelings on the others, but I have GIS bias.

**Comment by abettermap** [comment]
@rperlin-ela any opinions on the wording for General Human Users? I can see there being some various thoughts on this depending on the user.

**Comment by rperlin-ela** [comment]
"Auto-zoom to initial extent" makes sense to me

**Comment by abettermap** [comment]
@fiddleHeads good call on this one if it was your suggestion, pretty handy and easy to implement.

@rperlin-ela i got sucked into some dropdown stuff a bit but it will pave the way for more room when we migrate Location Tools, and also it makes census dropdown nicer:

![image](https://user-images.githubusercontent.com/4974087/111849556-7954a700-88d3-11eb-8e31-08f56256fde5.png)

definitely adds space to Home:

![image](https://user-images.githubusercontent.com/4974087/111849581-8bcee080-88d3-11eb-9b6f-6d9dfdc70ebe.png)

**Comment by rperlin-ela** [comment]
Well, hello Omnibox and Census Box, aren’t you looking good today? (These are great.)

Auto-zoom seems to be working great too. Only one thing I noticed that feels like a hitch, I think only on mobile. Let's say I'm in 3D and I select a census language. It auto-zooms fine to initial extent but then if I next switch to 2D, it doesn't give me the 2D version of initial extent but takes me to a position quite a bit to the south. Make sense.

**Comment by abettermap** [comment]
Ok good to know, that's the same issue or related at least to the off-center popup problem on mobile. 

Since it's occurring in more than one spot I'll definitely fix it in Week 4, but I think we're good to merge into prod for now.

**Comment by fiddleHeads** [comment]
Wow, I agree these are great. I really like how everything is looking and performing in this deploy. You're making fast progress, Jason. 

I can't replicate what Ross is describing on desktop.

**Comment by abettermap** [comment]
I think there's going to be a handful of things like this so I'll start an issue to collect them for Week 4 and fix them then.

**Comment by abettermap** [comment]
Thanks for the feedback Maya, had great ideas to work with in the first place, really digging all the stuff that was requested. 

And yeah it's just mobile. Desktop should be fine.
