### ISSUE TITLE
Nested panels: add "Back" up-one-level button

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#200]
## Jason edits

~~Breadcrumbs: adapt text and format it to the new structure of the nested Details view.~~ droppin' the crumbs, Boss. we've got enough on split btn and timeline below in thread, let's use that as guidelines for this:

> Implement "Up one level" functionality through a button or link in the top-left corner of all nested panels. For example, “/Explore/Neighborhood” would link to “/Explore”, “/info/about” would link to “/info”, and “/Explore/Language/Dzongkha” would link to “/Explore/Language”. This will serve as a useful supplement to the semi-obscure functionality of the panel title breadcrumbs.

**Comment by abettermap** [comment]
Breadcrumbs axing. 

So here’s what I’m thinking about the breadcrumbs and that top panel bar in general: not a ton of value UI-wise. I’m sure there have been suggestions or flip-flops on this in some fashion or other, but the more stuff we add to the “intro” panel section, the less useful our crumbs are. 

Don’t get me wrong, my brain really likes the hierarchical aspect- I feel safe as a user knowing what depth I’m at, how my current decision is related to its navigational ancestors, and that I can climb out of it as needed. However, I don’t imagine even “power users” on their first visit (or even third) will appreciate or even notice the navigational structure. Not to mention the top of any panel or bar-like thing is pretty high-level UI real estate. 

That said, I think we could restructure, if not scrap entirely, the breadcrumbs concept. I know I proposed it and I certainly appreciate it as a UI concept, but more so in the sense of traditional web structure, like “Minneapolis > Bars > Whatever This One Is”, and less so for feature-heavy web apps like the language map. 
 
SO, and please forgive my phone-only graphic, how about this:

![image](https://user-images.githubusercontent.com/4974087/111561834-bc3f3f00-875a-11eb-964e-7135f0731467.jpeg)


YELLOW: adios. Just a fat green border to separate panel from map. More room for goodies below it. 

BLUE: we’re only going to have the “panel toggle” arrow eventually and then the omnibox popout trigger button next to it, so I feel like those buttons could just get shifted down into the panel area. And maybe even keep our current friends, Help and About (AND omnibox popout toggle would be my vote, since it’s just kind of a bonus nav feature that doesn’t need to be accessed app-wide in one click) by relocating them into a menu like so: https://material-ui.com/components/menus/#customized-menus

RED: ...then, we’d only have at the most 2 buttons taking up top-right panel real estate, which (in the absence of breadcrumbs) leaves plenty of room for “up one level” in the top left. 

As usual, very visual and “feel”-heavy, but any thoughts at this level?

**Comment by abettermap** [comment]
( @rperlin-ela )

Also, depending on how the user arrived at a certain panel view or depth, they may not even understand the breadcrumbs hierarchy in the first place, especially once we throw in more cross-app navigation. 

For example, if they arrive at/Explore/Neighborhood/Whatever via a map popup versus top-to-bottom starting from Explore, the crumbs are not going to make a ton of sense. 

Lastly, on mobile they have to be scrolled through anyway due to occasional meatiness. 

Many reasons to scrap...

**Comment by rperlin-ela** [comment]
Yeah, I like 'em personally but I think I see your logic, and I agree it's valuable real estate. I don't think I understand all the implications, and I'm not sure about this menu you speak of, but in theory I could see axing the breadcrumbs if it's still clear how to do (and undo) the drilling down that Explore is all about. Or at least people feel those "back-button" vibes they love so much. So it depends on how "one-level-up" feels, which I'm not 100% sure about yet. Could we make that clicking the Explore panel button then brings you back to the beginning of Explore? And if we do axe, the outlines of what you suggest sound good, though I don't want to overstuff the top and hang too much on the "panel toggle", the omnibox-thing is still speculative, and Help/About is hopefully going to have its whole nice own panel... Anyway, I'm on board with exploring this!

**Comment by abettermap** [comment]
All good points and I think this is going to be a larger conversation worthy of a zoom next week, especially in tandem with the up one level/back button. It's all part of the shared concept of improving navigation, so we should treat it holistically with a good conversation or lots of screenshots, I'm up for either. 

I have a bunch of ideas and no doubt questions jotted down so I'm just going to upload for my near future reference. Don't worry if you can't read it, but awesome if you can understand ￼￼￼ the part above the horizontal line. That's what I'm envisioning for the top left of all nested panels, and the top right of every panel. ￼

![image](https://user-images.githubusercontent.com/4974087/111655595-66f14500-87cf-11eb-91da-956574436290.jpeg)

**Comment by rperlin-ela** [comment]
Cool, I kinda get some of it but not exactly, a holistic zoom sounds good

**Comment by abettermap** [comment]
For the top-left nav menu I'd also like to consider a Timeline even though that's not its purpose: https://material-ui.com/components/timeline/#basic-timeline

Icons would supplement it well (not as intense or staggered as [example](https://material-ui.com/components/timeline/#customized-timeline) though).

**Comment by rperlin-ela** [comment]
Keep the ideas coming! I can’t picture it all yet, but I’m open

**Comment by abettermap** [comment]
rough but better than dry erase board haha, this is what i was going for top left split btn as breadcrumbs alternative:

![image](https://user-images.githubusercontent.com/4974087/111857619-61434e80-88f8-11eb-94d8-cdbdd805a1f3.png)

and the menu btn arrow triggers a transit/timeline thing (pretend they're vertically centered within each item and all aligned left at the same edge):

![image](https://user-images.githubusercontent.com/4974087/111857640-7cae5980-88f8-11eb-935d-4312b6281220.png)

certainly looks less cluttered and 🤮 ed into the top bar like breadcrumbs but tradeoff is that we'd likely want it sticky and floating over the rest:

![image](https://user-images.githubusercontent.com/4974087/111857762-56d58480-88f9-11eb-951a-68527d959444.png)

first draft but i don't hate it.

**Comment by rperlin-ela** [comment]
Nice, I don’t hate it either, decluttering is key and this feels like the most innovative solution yet to the big “back button” request. I guess it’s going to take a little magic too to shoehorn longer-named things into that menu button

**Comment by abettermap** [comment]
yeah there's no way things like "Prospect Lefferts Gardens (Brooklyn)" are going to fit up there, plus we still need room for these things on the top right:

1. "panel collapse" icon/btn
2. if we're doing it, a "search" btn to show the omnibox (and presumably location search) in a popout so users can hit it from any panel w/o having to go Home. 
3. maybe a catch-all `...` btn that would trigger a dumping-ground popout for quick access to things like help, about, feedback (into addition to their new access point in the soon-to-be "info" panel that will replace Details), along with maybe some settings, location tools, etc. Totally optional but the amount of two-clicks-to-get there stuff we could add to that little popout might be worth the small tradeoff of an extra small btn.

as for "Back", i could see it going a couple ways:

1. _try_ to show the full text of the parent route (aka Astoria in the screenshot), but only allow the btn to be at most half the width of the panel (including its little triangle btn to show the timeline nav thing).
2. use `Back` as the text 24/7.

Option 2 is certainly easier, my only concern is that it will be mistaken for "Back to the last view I came from". However, after a few experiences clicking the btn (_especially_ if they're also clicking the triangle to show the timeline and understand the nav hierarchy), maybe it's not a problem? 

Option 2 also has some nice consistency and obviously is easier to code (although Option 1 shouldn't be terrible either).


### Positioning 

regardless of text choices, i'm not sure how i feel about the "floating" btn on top of the other stuff. even w/the shadowy elevation, it's kinda messy. so i'm thinking maybe a sticky top bar just like we have now w/breadcrumbs, etc., but meaty enough height-wise (nothing crazy, just like an extra 10 pixels or so) to accommodate the new UI residents. in other words, more like the "Menu" bar that you see 24/7 on Macs (and Windows, within programs at least). i don't know about you but on mobile i find myself clicking the "Improve this map" link waaaay too often on mobile since the panel title bar is so freakin small.

i just slapped this together so use your imagination haha:

![image](https://user-images.githubusercontent.com/4974087/111883513-87f99780-8981-11eb-9c6c-33fcb2fd0be3.png)

allow past halfway:

![image](https://user-images.githubusercontent.com/4974087/111883557-afe8fb00-8981-11eb-8c40-ef29945a831a.png)

truncation station: 

![image](https://user-images.githubusercontent.com/4974087/111883617-14a45580-8982-11eb-8da9-057f41c54e70.png)

depending on how you want to structure the timeline, i think "Home" is the only view in the app w/o a Back btn, which opens up some other space-saving doors:

![image](https://user-images.githubusercontent.com/4974087/111883755-e2dfbe80-8982-11eb-901c-48db4a38b23e.png)

or if we choose to omit the Back btn at top-ish-level views, then they could have something like this:

![image](https://user-images.githubusercontent.com/4974087/111883860-74e7c700-8983-11eb-91e7-d88fc4dba636.png)

### How the big boys do it

...apple at least. i tried to find examples of non-iOS apps with Back btns, but many only have one level of nesting. but if there is nesting, then "Back" is _very_ common (or at least a `<`) at the top left. Their app may only allow them to reach the Backable view from the parent though, in which case it's impossible to have arrived there from anywhere but the parent and therefore Back makes total sense (Google Maps ios app = good example).

as for iOS apps, Settings has some excellent depth:

`Settings app > General`

![image](https://user-images.githubusercontent.com/4974087/111883921-cbed9c00-8983-11eb-87f0-a1ad4bcbcc9c.png)

`Settings app > General > About` preserves the behavior:

![image](https://user-images.githubusercontent.com/4974087/111883935-e45db680-8983-11eb-9099-10de503a1686.png)

however, `Settings > Passwords & Accounts > Add Account` makes its own truncation decision:

![image](https://user-images.githubusercontent.com/4974087/111883961-0f480a80-8984-11eb-84f6-39b98773aced.png)

however, this might be dependent on iOS version and/or device. screenshots above are iphone 11 pro max, while i have an iphone X myself, and on that device it's very space-dependent in that it will just be like "screw it, not enough space, i'll just say `< Back`", or `Trunca...Middle` truncation when not enough room.

so part of the question we should ask is **what does the user expect of "Back"?**  say a user arrives at something in Settings app from another app (classic example: `Settings > Notifications > Some App` when "Some App" wants to pummel you with alerts). in that scenario, presuming it only had enough room to say "< Back", which takes you "UP one level" rather than "Back" to Some App, does this UI pattern apply to the language map or do you think users will think Back = Previous View? 🤯 

### Just spitballing

...but **any impressions/revelations so far?**

**Comment by abettermap** [comment]
Ah, the **ios Calendar app** has non-"Back" backness: 

![image](https://user-images.githubusercontent.com/4974087/111884237-eb85c400-8985-11eb-8562-e578a8ec1fd4.png)

![image](https://user-images.githubusercontent.com/4974087/111884262-0d7f4680-8986-11eb-96aa-ce8237112e4c.png)

it's not fair though since they have short names w/known length. get yourself a "Prospect Lefferts Gardens (Brooklyn)", Apple, THEN we'll talk.

**Comment by rperlin-ela** [comment]
Good spitballs. Yeah let’s be deliberate about how much we cram up top, even the functionality is great and it’s cleverly nested! Don’t want too many distractions. Just clarifying — the “Back button” is only really needed for Explore, but will the possibly three things you mention for top right be everywhere? I get the need for consistency, but for starters it occurs to me that we don’t need Search where we’re Home and we may not need for “catch-all” when we’re at Info.

I’m kind of digging the idea of just calling the Back button “Back”, and maybe eliminating it at said top-ish levels. Small thing, but did you have a thought about clicking the “Explore” icon at the bottom bringing people back to the top of Explore (instead of nothing, as currently)? I’m not sure floating is crucial either.

**Comment by abettermap** [comment]
Back button is going anywhere we have nesting. `/info/about` should let the user go back to `/info` for example. Info is the landing view, and Back is the lifeline to get back to it. 

I'm fine with axing it for top level routes though, e.g. the first /Explore. Users can already get Home in one click on the bottom nav, or the logo. 

As for consistency with the top-right button/s I'm proposing, I will argue in favor of consistency instead of little piecemeal conditions and scenarios like you mentioned. For example, if you're in a Help view in any application, does the `?` button that took you there disappear? Kinda never. 

I get the logic behind what you're asking, but it's jarring as a user to have things (especially in something that should be steady like a panel/nav bar) constantly changing. I will consult the internets for UX evidence if you disagree, but I don't feel the "96% of the time Button A is shown, just make sure you're not in View B" is the way to go. 

Keep in mind everything I've proposed is essentially a new feature anyway, and it only indirectly matches what we discussed in this scope (which was basically just a Back button and making sure breadcrumbs aren't wrecked). It's not like changing a color or something, it's tons of new code and improvements and functionality, and consequently time. If you want me to hide the search button on Home, that's fine. But not something like omitting the catch-all button just for help or about. 

As for the `...` in general, it was totally just a suggestion and if you're fine with the user accessing info-ish stuff only from the upcoming Info panel and our other sprinkles, that's totally fine, but if we're going to add the catch-all menu then it's going to be across the board and I'm not down for mixing conditional checks to see if we're currently at Info or something trivial like that. Search button, sure, if you really feel that strongly about it. But let's keep these:

- "panel close" button 24/7
- Search button on all non-Home views, although I think that's largely unnecessary and somewhat confusing, not to mention the button was just a suggestion I threw in post-SOW to soften the blow of Neighborhood changes, but keep in mind I also threw in a bunch of bells and whistles there as well, so I'd almost be more inclined to say forget about my 24/7 Search btn suggestion if it's so important to hide it in Home. 
- catch-all dots if you want them in all views, otherwise omit

As for clicking the Explore button in bottom nav to take you to top level Explore, YES. Totally on board, but only if it's for all nested panels. Again, UI inconsistencies are confusing for many of us, so if we're having that functionality then it will be for all nested panels. It's also AFAIK a full-on standard in native apps, and it feels very natural to me as a user. 

I think we're both on board with these:

- "Back" as the button label
- no floating (still sticky though hopefully? It's pretty important)
- omitting it from "top" levels, although I think the level of things like Explore should technically include it since it takes you to the Root Of All Things Where You Began, but since Home is one-clickable at bottom and logo, I'll concede. 

Good to go?

**Comment by rperlin-ela** [comment]
Totally good to go on those three bullets, and I 100% know that these are all nifty goodies that you’re throwing in. I hadn’t read your Census routing thread and I’d forgotten about Info being multi-part, that’s why I hadn’t realized where else nesting would be. And I get it about consistency, was just asking and thinking out loud, because of Search on Home. I know you’re a master of squeezing stuff in elegantly, so do your thing, I’m just trying to give Johnny Minimal a little representation. Search button and catch-all are still kind of theoretical for me but sound great — will probably become indispensable a few minutes into their existence

**Comment by abettermap** [comment]
too much?

![image](https://user-images.githubusercontent.com/4974087/112560751-7527fe00-8d99-11eb-9da4-58fd30c67609.png)

couldn't find a good back btn. worst case i can rotate it through css, but let's exhaust all options first.

if it sweetens the deal, i added tooltips on hover:

![image](https://user-images.githubusercontent.com/4974087/112560864-a7d1f680-8d99-11eb-9027-3084c528fa79.png)

**Comment by abettermap** [comment]
kinda diggin the centered title on just about any view (up to /Explore/Something at least)

![image](https://user-images.githubusercontent.com/4974087/112562381-c2599f00-8d9c-11eb-8b5f-c5a2550dfa1d.png)

even the big guys have hope

![image](https://user-images.githubusercontent.com/4974087/112563446-f9c94b00-8d9e-11eb-8d88-5a34ead49487.png)

**Comment by rperlin-ela** [comment]
Thumbs up on the centered title — only thing (looking at Language Families) is that the subhed text (“Group of…”) is now kind of far away, maybe you can either move that or style it bigger/differently

Some up-back arrow ideas: BsArrow90DegUp or BsArrow90DegLeft or RiArrowGoBackFill or CgArrowTopLeftO? 

For Table I think I can dig ImTable2 or similar

**Comment by abettermap** [comment]
> Thumbs up on the centered title — only thing (looking at Language Families) is that the subhed text (“Group of…”) is now kind of far away, maybe you can either move that or style it bigger/differently

Totally, i was just going to use the same component I'm using for all the other paragraphy things like that. 

Any chance you'd want to add some meat to the text? If so then probably doesn't need to be centered.

i'll try those icons, thanks.

**Comment by rperlin-ela** [comment]
Add? That would be fun for a change. You mean for all the Explore/Something subheds, like Explore/Languages, Explore/Neighborhoods etc? I could definitely turn all those into not-just-definitional but slightly more interesting one or two sentence little blurbs if you let me.

**Comment by abettermap** [comment]
ha no permission needed, you've got all the control in AT. go nuts! and yeah i mean this stuff:

![image](https://user-images.githubusercontent.com/4974087/112657753-574dae00-8e18-11eb-9139-ba61f144d30d.png)

i wouldn't recommend any links in your text though. just stick w/text.

**Comment by abettermap** [comment]
> Some up-back arrow ideas: BsArrow90DegUp or BsArrow90DegLeft or RiArrowGoBackFill or CgArrowTopLeftO?

i know i've asked this before but **how are you finding these**? it's almost like you're on a different site entirely since i can NEVER find the ones you mention. there's not even an Ri or Bs or Cg category, let alone those icons. the search never works either.

**Comment by abettermap** [comment]
i just scrolled through all the categories:

![image](https://user-images.githubusercontent.com/4974087/112678922-29289800-8e31-11eb-875d-a2bd4de2f983.png)

and none have the prefixes you mentioned. where's your secret icons site bruh??

**Comment by abettermap** [comment]
OH PROBABLY THIS ONE https://react-icons.github.io/react-icons/

my goodness where has that been all my life, it's seriously got like 2x as many categories!

**Comment by abettermap** [comment]
yeah the up arrow is exactly what i wanted haha

can you handle BsTable for table? pretty ballin to me:

![image](https://user-images.githubusercontent.com/4974087/112680007-76593980-8e32-11eb-9870-39bad3dd1cc2.png)

**Comment by rperlin-ela** [comment]
Love it

**Comment by rperlin-ela** [comment]
Speaking of icons, “About” is a tough nut to crack. I know we use people elsewhere, but maybe something like BsPeopleCircle?

**Comment by abettermap** [comment]
ah i forgot about About ha. you're referring to the /Info link to it right? yeah that's fine, no strong opinions since it's only used once in the app. 

let me know if that's what you meant and i'll wire it up

**Comment by abettermap** [comment]
also here's what i came up with for the /Something/Something levels:

![image](https://user-images.githubusercontent.com/4974087/112691119-7103eb00-8e42-11eb-8948-da8247e78842.png)

the only catch for now is no plural title as i'm going straight off the URL. there are plenty of ways to fix w/o touching the data, but i'd rather wrap up today w/higher priorities. if you can stomach the singular name (like we had  in the pre-AT days) let me know as it's already wired up.

**Comment by abettermap** [comment]
oh and i don't hate this for About: GrContactInfo

![image](https://user-images.githubusercontent.com/4974087/112691907-a230eb00-8e43-11eb-8261-d1ce5763d3dd.png)

you?

**Comment by rperlin-ela** [comment]
﻿That’s fine with me— yeah I meant the About icon within Info, to set it apart, either one good

For Something/Something, I do think it needs to match what people clicked to get there (back in good old /Something). I could probably live with singular across the board, let me take a look when it’s ready. Nice new Up arrow!

**Comment by abettermap** [comment]
well you know i'm not into removing functionality that was already there, plus i do like plural and there's an AT column i set up just for that, so i intend to get it back. good Week 4 stuff in a pinch, although would rather that not pile up though: #204 

singular for now though. 😞

**Comment by abettermap** [comment]
since we're talking about icons so much and now i know (again haha) how to get to the _actual_ icons site, any of these better for timeline trigger btn?

https://react-icons.github.io/react-icons/search?q=list

our current one is just kinda too "bold" or something

**Comment by rperlin-ela** [comment]
Yeah, whatever you think best, could just be a lighter one like AiOutlineUnorderedList or MdFormatListBulleted or something

**Comment by rperlin-ela** [comment]
Btw I added some meat to Explore/Languages, and I like it and could do the others, but I don’t like how it makes the card look overstuffed at Explore— don’t know if it’s worth unless it’s easier to cut it off there with a … I feel like that’s happening on (most but not all?) other cards and I generally like it

**Comment by abettermap** [comment]
ah shoot i forgot about that. two options:

1. continue using the same AT field for both the /Explore cards AND the /Explore/Something panel intros, OR
2. new AT field in Schema table for /Explore cards

i think Option 1 makes more sense since i could apply it to other cards and views. the reason you're seeing inconsistencies is that i'm probably doing some crappy character count in JS for some views and not others. shabby approach either way, but the CSS solution i mentioned the other day in the context of Read More could work very well for this.

i don't think the /Explore cards are enough to justify a "truncated" or "simple" or "summary" field in AT, would be just one more thing for you to write without adding much value, so i'll do `...` after 4 lines if that works?

**Comment by abettermap** [comment]
(digging the new descrips you've added btw, looking solid)

**Comment by rperlin-ela** [comment]
Sure thing, thanks, 3 or at most 4 lines sounds good

**Comment by abettermap** [comment]
3 is looking good so I went with that. This is only for the main top level /Explore view, right? The other card footers look fine? I have a different check going on for the 5-instance footers in /Explore/Neighborhoods for example. It's not line-based but rather shows all five no matter what.

I think that's a different concept though since it it is a list rather than a paragraph so I think we're good?￼￼
