### ISSUE TITLE
Census: text tweaks

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#203]
We now have 2015-2019 data and one day will have 2016-2020 etc, but the census pop-out says 2014-2018. Can we just tweak text to "... census category of [Lang Name] at the tract [/PUMA] level in the most recent ACS."

## Jason edit: added this from #202

Current Census panel text can be reduced to match the slimmed-down version in the census pop-up, followed by one additional sentence (can we squeeze into the pop-up too?): 
 
"The Census Bureau's American Community Survey (ACS) provides an indication of where the largest several dozen languages are distributed. Census data is presented _only_ in green, as polygons. **All other data is Endangered Language Alliance data**. More info"

**Comment by abettermap** [comment]
ah shoot i forgot about the date thing, definitely have a note in the code.

if you're okay with that, fine by me. definitely one less moving part that way, and Future Ross doesn't have to call Future Jason for the tiny change each time. i'm hoping maybe users who care about dates and metadata will click More Info to their heart's content. you can put the dates in there if you haven't already.

**Comment by rperlin-ela** [comment]
All good, let’s make it generic and then I’ll keep things updated in more info

**Comment by abettermap** [comment]
this one should be easy but feels like a better fit for Week 3 as well.

**Comment by rperlin-ela** [comment]
By all means

**Comment by abettermap** [comment]
Ross- with the advent of the AT UI Text control over the census wordings, are we all set on this? Do you have what you need to edit it?￼￼ If so then let's close this issue. ￼

**Comment by rperlin-ela** [comment]
Under “UI Text" I see the census-popout-intro text in question, but in there I only see the text above the dashed line in the pop-out. I understand the text below the dashed line is dynamic because of the language names and might be hard to include in “UI Text". So I don’t see how I can do it, still just need you to take out 2014-2018 to make it generic

**Comment by abettermap** [comment]
my bad, i hadn't looked at it while writing and was on my phone. do you want a new entry in UI Text for the years or just make it generic?

**Comment by rperlin-ela** [comment]
If it’s fairly easy to include despite the language names being dynamic, great to have it in there, for sure. If that’s a hassle, just make it generic.

**Comment by abettermap** [comment]
done
