### ISSUE TITLE
Minor panel tweaks and fixes

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#204]
* [x] `UI Text` at the top of /Explore: "For an explanation of the options below..."
* [x] re-pluralize /Explore/Something: https://github.com/Language-Mapping/language-map/issues/200#issuecomment-808517391
* [x] One other UI Text tweak to go with rigging up the /Explore text... The census pop-out text seems to be drawing on census-panel-intro-bottom rather than census-popout-intro.
* ~~Search Locations tab: migrate elsewhere (details in thread below, break out if needed)~~ **will be in other issues**, and we decided in favor of not moving the zoom to my location into a new menu￼ 
* ~~in-panel feedback form on mobile: either make it look good in panel or scrap the in-panelness in favor of modal.~~ move to #257

**Comment by abettermap** [comment]
@rperlin-ela here's what i'm thinking for this tab, which is currently:

![image](https://user-images.githubusercontent.com/4974087/112707817-c3a9cb00-8e73-11eb-9231-cacc1e3dce92.png)

- don't need Show Neighbs. it's going into all /Explore/Neighborhoods views (except lang profile)
- Show Counties and Show/Zoom to my location can both go into a popout spatial dumping ground below the "3D" button. 
- ample room then in popout for small explanations (the ℹ️  contents we currently have next to them), don't need popout-inside-popout
- if someday we do /Explore/Counties, then the "Show Counties" toggle can go at those levels just like we'll have for /Explore/Neighbs. not this scope though.
- with my recent style changes to improve space for the Search Languages/locations tabs, we now have room for an ℹ️  btn next to each of them, where we could explain some of the many things that could use explaining, without sacrificing space.

**Comment by rperlin-ela** [comment]
I’m on board with all this, sounds very good, I’d go for all but the last bullet and then see if we need that last one after all

**Comment by abettermap** [comment]
i don't think "we" will, we've already determined that you feel the search box placeholders + tabs sufficiently describe the concepts, and i imagine many of our testers our linguists, so ℹ️  am not optimistic that the btn will see the light of day despite its potentially high value-to-real-estate ratio. would cover a lot of bases w/o consuming space, even on mobile. there's really no need for a 350px search bar (besides seeing a really long suggestion) unless someone is typing a really long address and wants to see it all at once.

**Comment by rperlin-ela** [comment]
Ok, ℹ️ am thinking about using this after all and I hope it’s not too late :)

What I’d want to put in the “Search Languages” tab is "All data, unless otherwise specified, is from the Endangered Language Alliance”— a key message which is not yet clear enough, especially as we up our Census game. I really think understanding that there’s ELA Data and Census Data and a way to compare the two is key to making full use of the app, and I’m despairing that I haven’t done enough to communicate that.

The Census panel will be another chance, but I’m wondering also how I can bribe you to slip this same little message into the Data table...

**Comment by abettermap** [comment]
For the search languages tab are we talking about helper text or the info button? I think it's the latter and if so go ahead and make a new record in UI Text table with an id￼￼ of `omni-info-popout` and populate the other two columns.￼ 

Also please create a new issue for this, I know we have a lot of them but there's already four that I smashed together in this one and I could see the comments getting out of hand quickly, and I have a ton more issues that I haven't documented yet as well.￼ I will create a new milestone for week four and dump them in there as needed, not likely I will get to it this week and it seems like a good week 4 item anyway.￼

As for the table request, I'll have to say no to that one for now, not because it's difficult to hit Airtable to get your text, but because the top part of the table is really hard to work with, especially adding a new item to it instead of just changing text.￼￼

Good issue candidate there as well…￼

**Comment by rperlin-ela** [comment]
One more thing for the Search Locations tab when we get there— unlike with Search Languages (and unlike, I think, how location search used to be back in the bad old "Local" days), only one search result is now visible until you scroll down. Would be great for that dropdown to go on top of other stuff so searchers can see a bunch of options.

**Comment by rperlin-ela** [comment]
One other bit it would be great to have in UI Text if possible is at the top of /Explore: "For an explanation of the options below..." Hope I'm not missing any others.

**Comment by abettermap** [comment]
ah good call, i'll wire that up. was withholding in the past due to all the links, but ain't no thing now.

**Comment by rperlin-ela** [comment]
One other UI Text tweak to go with rigging up the /Explore text... The census pop-out text seems to be drawing on census-panel-intro-bottom rather than census-popout-intro.

**Comment by abettermap** [comment]
oops, lost in the shuffle. added to issue above.
