### ISSUE TITLE
Census panel: add dynamic legend

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#207]
(originally from #202, which will need to be completed first)

Census panel: add a legend with gradient color scale, dynamic numbers that change with the language selection change, and supportive info text as needed.

very related: #203 and anything else w/census in issue title. think it through, big stuff here!

**Comment by abettermap** [comment]
@rperlin-ela i'd like to kick this to Week 3 if that's ok with you? feels like it fits in there better, and it's going to take some time.

**Comment by rperlin-ela** [comment]
For sure

**Comment by abettermap** [comment]
how's this?

![image](https://user-images.githubusercontent.com/4974087/113607391-61d12a00-9606-11eb-917a-3f45944e4c59.png)
