### ISSUE TITLE
Restructure routes and fifth panel

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#208]
## Summary

This is a monster, but they're all related so it's gotta be one issue...

- [x] Off-canvas sidebar: migrate contents into a new panel (the fifth panel, which “Details” currently occupies) named "Info". Remove top-right About and Help buttons from the panel toolbar.
- [x] In tandem with the sidebar migration, create nested views (one level of depth only, no sub-views) for help, about, and the feedback form. This content will be nested into the second level of the Info panel rather than the current approach of modal dialogs, which will allow users to see the map while they read Help content, and presumably resolve issues related to closing modal dialogs.
- [ ] Nest “Details” view into `/Explore/Language/Language-Name`: rather than devoting an entire permanent panel view to Details (with its own bottom nav tab like we have now), set up URL routes for this info as a child of /Language/Language-Name and remove top-level direct access from the bottom navigation bar.
- [ ] “No community selected” scenario: adapt this to the new nested Details setup and ensure that it is linkable throughout the application, possibly through a dedicated URL such as one with a “no-selection” suffix as an alternative to “details” being in the URL, e.g. `/Explore/Language/no-selection`.

make sure #200 works with all these instances once they're ready. probably best to do this Restructure issue before 200...

**Comment by abettermap** [comment]
@rperlin-ela not sure if you considered this yet, but the modal-free world we're about to live in will take a LOT more scrolling with the long content of help and about. Our new back-to-top btn will be great for this, but the super-long content is something to consider breaking out into more digestable WP chunks down the road. then we can have one more nest depth like `/info/about/census`, which will enable the Back-ness and improve life for the attention-challenged (my people, errrr my ppl), whereas `/info/about#census` like we have now will not have Backness to climb from census to about since it's all one page.

ideally we'd use... airtable. or maybe you create WP pages with really specific page names (slugs)? i feel like we had this convo elsewhere, but just something to keep in the back of brain region for now, although i won't likely get to it in this scope.

**Comment by rperlin-ela** [comment]
Noted, thanks for flagging— might just have to cross this bridge when we come to it.

**Comment by abettermap** [comment]
diggin it. panels are the new modals! 🚀 

![image](https://user-images.githubusercontent.com/4974087/112415011-b44a4680-8ce8-11eb-8eb1-9f9c129a5c7b.png)
