### ISSUE TITLE
Link/s to "Intro" video or help doc PDF

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#209]
This one has been super up-in-air but I think most recent decision was PDF link for now?

- [x] "Intro" video: add CSS support for WordPress (WP)-driven content, which is currently Welcome, Help, and About modal dialogs. Provide Ross with HTML structure and consulting as needed. Note that this task may be removed in favor of a simple link to a static PDF manual.
- [x] "Intro" video: include the video at the top of the new "Info" panel using an iframe from YouTube. Address the in-progress status as needed since the video has not yet been created. Note that this task may be adjusted in favor of a simple link to a static PDF manual. In that event, the link will still be included in the requested position where the video would have been placed.

**Comment by abettermap** [comment]
@rperlin-ela i think this was the last of the Week 2 SOW items but if you happen to see that i missed any, let me know. some got combined, others maybe axed, and then some monster census ones evolved into their own beasts.

**Comment by abettermap** [comment]
Ross, think you could dump a **placeholder PDF** on dropbox or WP or wherever is linkable for the final PDF? and i assume that's still the direction we're taking in this round? 

also which do you prefer for **link placement**?

1. top of the list in `/Info`, with the same icon, title, descrip layout as the others
2. on its own in a paragraph above the list, either with or without a title (e.g. "New Fish?  Start here"), and a regular in-paragraph link to the doc.
3. some variation of Option 2, but maybe with a _button_ as the link
4. ???

lastly, between the census text and search tabs, i'm pretty spent on the wording stuff! i'm happy to provide input/feedback, but i think it should be up to Ross et all to provide me with the copy to include in the UI. so, regardless of which Option you pick, let me know what you'd like it to say.

**Comment by rperlin-ela** [comment]
Does this work for a placeholder? https://languagemapping.org/wp-content/uploads/2021/03/Help-Video-Script.pdf <https://languagemapping.org/wp-content/uploads/2021/03/Help-Video-Script.pdf>

I actually think this should go under Help but above that handy line, and I think I like Option 1. For the icon something standardly PDF-y, maybe just old Details, the page with writing on it (folded or not in the upper right hand corner). Let’s call it Manual, and the little text under can be: “Download a PDF with detailed instructions”. That ok?

I hear you on text and will keep trying to do my best, though it can be key to see the space and a lot of your suggestions are spot-on.
