### ISSUE TITLE
Map popups: establish behavior and content

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#215]
- [ ] Determine the pop-up behavior relative to other pop-ups, e.g. should we only have one pop-up open at a time, or can there be one for census and neighborhood and county and language points all at the same time, plus hovering and tool tips. Those considerations are typically what makes the pop-up stuff more difficult in the code, and less user-friendly in the UI, ￼so if we can simplify that would be great.
- [ ] Also consider the pop-up content relative to the info we intend to show in the panel in tandem with the pop-up, such as census stuff, and decide how much value the potential redundancy between the pop-up and panel actually provides￼￼. Since we are putting so much nice info into the panels, is a pop-up really necessary for polygon layers, or could we simply highlight the clicked polygon like we are doing now, auto zoom to it, go to corresponding panel, and lean on the panel as the sole source of information? 

I guess this conflicts with our plan to include a link to neighborhoods from the neighborhood pop-up, so instead maybe we could adjust the approach to only show the neighborhood name on _hover_, but then on click have it automatically take you to that neighborhood in the panel?

E.g. hover on Astoria polygon, see "Astoria" tooltip. _Click_ on Astoria polygon, go to /Explore/Neighborhood/Astoria. And for puma, tooltip on hover has name, but _clicked_ puma takes you to /Census/puma/language/name or /Census/puma/name. Can't remember what we decided. And not sure how tracts fit into this ideally behavior would be the same.￼

Just brainstorming for now, but it's going to be one of the first discussions of the week, and the more consistent we get the behavior for each of the polygon layers, hopefully the easier the coding should be. If this requires the same behavior with a dedicated counties (inc. boroughs) Explore panel to sweeten the deal, let's sweeten it.

If I'm doing that though, I would propose that the behavior be the same for language points as well. No pop-up, only a tool tip on hover. Then, when a point is clicked, a symbol marker would show up on top of the point instead of a pop-up￼. Could probably do something fancier than the stock blue icon we are using for the geosearch result point, but I'm just thinking the pop-up does not provide a ton of value given that its info is already present in the panel and in a much more styled and legible manner. I feel like the pop ups are just a legacy remnant of the original approach to show a lot of things in the pop-up rather than panel, but we've definitely evolved since then!￼￼￼￼￼￼

Whatever we can do to make things more consistent in code and UI, and to make the map less busy with tons of pop-ups and tooltips for multiple layers, the better, so let's dial it in.￼

**Comment by abettermap** [comment]
@rperlin-ela not sure if all this makes sense how I typed it, just threw it together, but if you have any initial thoughts, please share.￼

**Comment by rperlin-ela** [comment]
Cool, this is a tricky area for me with so many moving parts, so I'd either say let's zoom as soon as possible (even today if you want, tomorrow also pretty free), and/or feel free to really hone what you think would be the best approach. I'm down with minimizing if we can get people the info they expect, instinctively I can see for instance having two pop-ups open at once but maybe not more. 

> E.g. hover on Astoria polygon, see "Astoria" tooltip. _Click_ on Astoria polygon, go to /Explore/Neighborhood/Astoria. And for puma, tooltip on hover has name, but _clicked_ puma takes you to /Census/puma/language/name or /Census/puma/name. Can't remember what we decided. And not sure how tracts fit into this ideally behavior would be the same.￼
 
> Just brainstorming for now, but it's going to be one of the first discussions of the week, and the more consistent we get the behavior for each of the polygon layers, hopefully the easier the coding should be. If this requires the same behavior with a dedicated counties (inc. boroughs) Explore panel to sweeten the deal, let's sweeten it.

Want to understand how it would work for mobile users, but otherwise this sounds good, and this behavior should be consistent across all these geographical units. All the sweeter with counties of course.
 
> If I'm doing that though, I would propose that the behavior be the same for language points as well. No pop-up, only a tool tip on hover. Then, when a point is clicked, a symbol marker would show up on top of the point instead of a pop-up￼. Could probably do something fancier than the stock blue icon we are using for the geosearch result point, but I'm just thinking the pop-up does not provide a ton of value given that its info is already present in the panel and in a much more styled and legible manner. 

I don't totally understand this, let's discuss. Is this in reference to 3.1.9? In other words, leave current functionality as is for clicked points and then just have tooltip rather than pop-up for hoverers?  

In general I feel like we can lean on the panels a good bit for info and that the pop-ups and tool tips are really about making sure that people know exactly what/where the panel info is referring to.

**Comment by abettermap** [comment]
Hmm i'm not sure I'll be able to hone in on the best approach too well, I feel like there are some pretty mixed opinions within the group and no doubt across our user base as well, so I'm not really sure what's the ideal setup. ￼

You bring up a good point about the hover on mobile though. That's part of the challenge, because if you want to make sure mobile users have the same content that desktop users have on hover, then it has to be on click for mobile since there is no hover. But then what becomes of the click for desktop users? And how does it differ from what they see on hover?

As for number of pop-ups and tooltips shown at once, two sounds like a rational number, but does this include pop-ups and tooltips total, or just pop-ups?￼￼￼ I'm not sure I would want to do some kind of numeric check though, I'd really like to just have behavior that is like "close the other stuff so I can focus on this one". Especially if the popup of the clicked feature is associated with the panel info, then it can all be integrated cohesively through routes. 

Keep in mind there will soon be the potential for **four** clickable layers, and it's sounding like four hoverable layers as well. so maybe it's best to outline some scenarios and find out what you would expect in each one?￼￼ Let's assume they happen in order. ￼

1. _Language point clicked, no visible polygon layers_ I think same behavior as now except probably instead of current subtitle in the pop-up, we show its symbol and value (e.g. a green dot that says Northern Europe)￼.￼￼￼
2. _neighborhoods layer turned on, then a polygon is clicked￼￼_ I would expect the previous pop-up from the point to close, the map to zoom to the neighborhood that was clicked, and a popup showing the neighborhood name as the title and the borough as the subtitle.￼ Additionally there will be a link under it that says "view details" or "view languages" or something￼, and the link points to /Explore/Neighborhood/Name.
3. _language point clicked￼_. I would expect the neighborhoods pop-up to close,￼ its polygon no longer highlighted, and the behavior to proceed as usual. Details, popup, map zoom, etc.
4. _basically any point or polygon clicked￼_￼ should close the previous pop-up, open a new one with the title, a subtitle, and for anything except points, a link at the bottom pointing to the corresponding route panel view.￼￼ only allow one popup in the map at a time.￼
5. _For desktop users_, show a really simple tooltip for any point or polygon layer on hover, regardless of any pop-up being open￼. The tooltip content would be whatever the title is from the clicked feature of the pop-up in that layer. So essentially the most basic piece of text that describes the feature that was hovered on. ￼￼Puma name for puma layer, neighborhood name for neighborhoods, language or endo for points, etc. 
6. No tooltip for mobile users. They'll survive the ONE-CLICK gauntlet required to obtain info.

I guess I had a preferred approach after all, just had to think it through. As for how this affects the reverse scenario, where the user auto-zoomed to￼ a particular neighborhood or puma polygon by clicking through stuff in the panels, that's a bit trickier. I suppose it would still show the pop-up same as if they had clicked that polygon in the map, except without the link in the bottom of it encouraging them to visit the corresponding panel since they're already there?￼￼

To keep the highlighted selected polygon behavior consistent though, what if we always show the highlighted polygon even if the layer as a whole is turned off? 

For example,￼ if user goes to /Explore/Neighborhood/Astoria by whatever means, as long as they have the auto zoom turned on, the map will zoom to Astoria but also highlight its polygon border somehow, without turning on the rest of the neighborhoods (unless of course the user turned that toggle on). ￼￼￼The highlighted border could also be used even when they do have neighborhoods turned on.￼

YES. I think we got it. Lots of visual and not an easy one to code a demo for, so I suppose zoom either in an hour or so, or tomorrow, whichever works for you. The place I'm staying has a data cap on Internet though, and evidently I'm at 90% so no video this time but screensharing upstream should be fine￼￼. 

Consequently I'm writing all this from my phone on cellular to not impact the Data any further, so apologies for any typos, hard to write all this on the phoneskies!￼

**Comment by abettermap** [comment]
Ah, forgot about the other alternative to polygon tooltips, and I believe Maya suggested this, and that is to label the polygons. I looked into it a bit though and the only way to do it in MB is to create an actual separate points layer￼ (as in point geometry, but no actual symbols are shown). 

I could see that getting out of hand quickly since we would have to maintain twice as many polygon layers. I wouldn't be terribly worried about counties or tracts, but the other two layers seem volatile enough to make this a headache. Not to mention we would be opening a new can of worms for things like: show labels at all zooms? If not, at what zoom level should the labels turn on? What color and font and all that would they be? Should the user be allowed to turn them on and off?

Not to mention, the points layer that I would come up with would just be the centroid of each polygon rather than the ideal spot to place its label. When you and I were looking at the MB Boundaries label placement the other day, this is exactly what I'm referring to. They didn't just plop each neighborhood label in the center of the polygon because it would look off-balance or just simply not fit into their basemaps without conflicting with other symbols and/or labels. 

There's a whole science to it, so let's just stick with the plan I had above if it works for you.￼￼￼￼

I would also be very much OK with not having any tooltips on hover for polygons. I've done this before on other projects where we let everything be hoverable for tooltips and, depending on the zoom level, it can get really annoying because then you're looking at tooltips constantly regardless of where your cursor is￼. Reason being, with a polygon layer turned on while you are zoomed in close, there's ALWAYS something to hover over, and you can never escape triggering a tooltip in that scenario￼ unless you move your cursor off the map.

This is probably how it initially was in the scope and then I added it later, but let's **stick to only showing tooltips when the language points are hovered￼**. I can at least change the fill color of the polygon layers on hover to encourage the user to click it. I just know it's going to get ugly if every single feature in the map￼ is hoverable.

**Comment by rperlin-ela** [comment]
> 1. _Language point clicked, no visible polygon layers_ I think same behavior as now except probably instead of current subtitle in the pop-up, we show its symbol and value (e.g. a green dot that says Northern Europe)￼.￼￼￼

Agree current behavior is good. What do you mean "current subtitle"?
Just a pet peeve, but I wonder if it's quick to only show Language in the pop-up if Language and Endo are same.

> 2. _neighborhoods layer turned on, then a polygon is clicked￼￼_ I would expect the previous pop-up from the point to close, the map to zoom to the neighborhood that was clicked, and a popup showing the neighborhood name as the title and the borough as the subtitle.￼ Additionally there will be a link under it that says "view details" or "view languages" or something￼, and the link points to /Explore/Neighborhood/Name.

Sounds very good

> 3. _language point clicked￼_. I would expect the neighborhoods pop-up to close,￼ its polygon no longer highlighted, and the behavior to proceed as usual. Details, popup, map zoom, etc.

Sure, I'm with you.

> 4. _basically any point or polygon clicked￼_￼ should close the previous pop-up, open a new one with the title, a subtitle, and for anything except points, a link at the bottom pointing to the corresponding route panel view.￼￼ only allow one popup in the map at a time.￼

Ok, let's try, I think I'm on board. I can see scenarios where people are looking at a language and then they're like, What neighborhood is this again and just want to get the name by clicking (especially if they're not set to auto-zoom), but maybe this is an edge case and maybe it's preferably to having a cloud of confusing pop-ups.

> 5. _For desktop users_, show a really simple tooltip for any point or polygon layer on hover, regardless of any pop-up being open￼. The tooltip content would be whatever the title is from the clicked feature of the pop-up in that layer. So essentially the most basic piece of text that describes the feature that was hovered on. ￼￼Puma name for puma layer, neighborhood name for neighborhoods, language or endo for points, etc.

Yes. And I guess this is where your follow-up comment about tooltips on the polygons comes in. I'm not totally sure, curious what Maya thinks. I think I can see the annoyance you describe, but I can also see the utility, especially from further out, of quickly scanning to see where you are and what the surrounding neighborhoods are before you commit to the click and get zoomed in. We don't really have a quick way for non-New Yorkers especially to get the lay of the land and see where they are on the map.

> I guess I had a preferred approach after all, just had to think it through. As for how this affects the reverse scenario, where the user auto-zoomed to￼ a particular neighborhood or puma polygon by clicking through stuff in the panels, that's a bit trickier. I suppose it would still show the pop-up same as if they had clicked that polygon in the map, except without the link in the bottom of it encouraging them to visit the corresponding panel since they're already there?￼￼

Yes, just as we're treating clicking on a point the same as we're treating reaching that point via Search or Explore

> To keep the highlighted selected polygon behavior consistent though, what if we always show the highlighted polygon even if the layer as a whole is turned off?
> 
> For example,￼ if user goes to /Explore/Neighborhood/Astoria by whatever means, as long as they have the auto zoom turned on, the map will zoom to Astoria but also highlight its polygon border somehow, without turning on the rest of the neighborhoods (unless of course the user turned that toggle on). ￼￼￼The highlighted border could also be used even when they do have neighborhoods turned on.￼

That sounds good. +1!

**Comment by abettermap** [comment]
Subtitle = bottom line of map pop-ups currently. E.g. ￼ Bhojpuri, not the endo

> Just a pet peeve, but I wonder if it's quick to only show Language in the pop-up if Language and Endo are same.

For sure. 

> ￼I can see scenarios where people are looking at a language and then they're like, What neighborhood is this again and just want to get the name by clicking (especially if they're not set to auto-zoom), but maybe this is an edge case and maybe it's preferably to having a cloud of confusing pop-ups.

Understandable, and this is where labels for polygons would be handy, but yeah like you say might be an edge case. Worst case they just click the neighborhood again, get the name, then click the point again. Seems worth it to only have one pop-up at a time, plus tool tips for language points.

> ￼￼but I can also see the utility, especially from further out, of quickly scanning to see where you are and what the surrounding neighborhoods are before you commit to the click and get zoomed in.

The key phrase there is further out. Zoomed in would be not quite the same level of usefulness since tooltips would be always visible.￼ If user has auto zoom disabled then they should be able to just click the neighborhood without it panning and still get the name that way. Makes it consistent for mobile too.￼

**Comment by rperlin-ela** [comment]
> Subtitle = bottom line of map pop-ups currently. E.g. ￼ Bhojpuri, not the endo

I'm open to trying it, but not sure we should go endo only in the pop-up if that's what you mean. I think a main function of the pop-out is for people to be able to cross-reference dot and panel and be like, Oh great this dot is for the same Bhojpuri community I can read about in the panel.

> Understandable, and this is where labels for polygons would be handy, but yeah like you say might be an edge case. Worst case they just click the neighborhood again, get the name, then click the point again. Seems worth it to only have one pop-up at a time, plus tool tips for language points.

Ok, let's give it a go as you envision it.

**Comment by abettermap** [comment]
> I'm open to trying it, but not sure we should go endo only in the pop-up if that's what you mean. 

no, sorry, not what i meant, was just defining "subtitle" since you'd asked what i meant by it. 

language point popups will look same as they do now: 

- title: endo
- subtitle: Language, unless Endonym === Language, in which case show only title

**Comment by abettermap** [comment]
i think we made the right call on the one-popup-at-a-time policy, here's what it looks like without 😆 

![image](https://user-images.githubusercontent.com/4974087/112878886-ac422c00-9085-11eb-8058-39cc3d98011b.png)

in that scenario i clicked the Zarma point, which opened a popup as we want, then clicked the Fordham poly and... yucko haha

**Comment by abettermap** [comment]
Ross-

are you sure you want the intermediate step of having to click a link inside the neighborhoods popup to trigger opening of /Explore/Neighborhood/Something? tradeoffs either way UI-wise, but considerably more difficult in code to deviate away from how we do it with the language points (click point = more-than-popup stuff happens).

i could go either way on this one as a user. on one hand it's like UGH, i already clicked the neighborhood, i'm obviously interested in what this polygon is about and have committed myself to investigating it through click. just show me the info already! the popup alone is not enough gratification, and the extra link click required for whatever we put in the bottom of the popup kinda feels like an unnecessary chore.

on the other hand, and this goes for points as well, it's like "whooaaa there, wasn't expecting all this panning and zooming around, i kinda liked where i was at before! really just wanted to see a simple popup before i made the commitment to all this auto-zooming and info"

if i had to pick one (and there's probably subconscious dev motivation here), i'd go with the first option. if we were still living in the "name is the only attribute neighborhoods have", by all means, just a popup with a link to the corresponding panel. but now that we've got boroughs/counties, potential neighborhood-level descriptions, and a tighter coupling of panel-to-map relationships (e.g. neighborhood toggle _in_ the panel, along with the auto-zoom setting), it feels somewhat natural to have the panel just open up when the polygon is clicked.

thinking beyond neighborhoods, counties and census would have the same behavior. no intermediate step, just the same approach we've taken with points.

let me know what you think, although know that the "do THIS for points, but THAT for everything else" will take considerably longer as i'm really struggling to wrangle the code logic with all the scenarios (even something as simple as closing the popup).

**Comment by rperlin-ela** [comment]
Ok, I don’t have an immediate strong instinct on this so if option 1 feels more intuitive, is more consistent, and is more straightforward to code, go for it

**Comment by abettermap** [comment]
Well the last two for sure, but we'll see on intuitive. Haven't wired it up yet but I'll push it up when I do. 

As far as closing the popup via its X button, currently for points it has the same effect as clicking an empty spot in the map, or the "clear selection" button in the details panel. Ideally we keep all things consistent, otherwise there's no real way to clear the selection if you're zoomed in close and the neighborhoods are turned on. Clicking out of the popup will just trigger a click on whatever you hit in the map. 

We didn't really discuss the close button so hopefully you're ok with similar behavior. Or, we could have a click on a neighborhoods popup X button take you to /Explore/Neighborhood as kind of a landing page to see more hoods without triggering an auto zoom?

**Comment by rperlin-ela** [comment]
Good point. I guess it’s not terrible as is when you close a language point pop-up, though I can feel people who just want to close the pop-up but not lose where they are in the panel. Same with the Neighborhoods pop-up — currently I like that you can just close it are still stay in the neighborhood, though I know right now we don’t have the whole panel thing going on. So my instinct would just be to let people close a pop-up and otherwise leave them completely be, but if you feel it really should be a clear selection thing (and likewise with all pop-ups) I guess we can roll with that, though it might be a little jarring to people. Taking people to /Explore/Neighborhoods (and I guess also /Explore/Neighborhoods?) at least feels a little more interesting (and yes without zooming them around)

**Comment by abettermap** [comment]
OK I will try it how I suggested only if the "click X button only closes the pop up but doesn't clear selection" approach is getting difficult in the code.￼ 

And if the "click also clears" alternative￼ feels like garbage, might need to circle back on that to figure out how to do it with the first approach, once the dust settles on some of the other basic functionality we're adding. ￼

**Comment by abettermap** [comment]
I got the X close button working the way we wanted, and I agree it's pretty smooth. But it does make it trickier to "clear" selections. The only way to do it now is to click an empty space in the map which may or may not be an option depending on how far in you're zoomed and whether or not there are any polygon layers turned on￼.￼ if it's a sea of polygons, there's not really anything to click off of.

I'm also not sure it's intuitive that when you have a neighborhoods pop-up open and are looking at a neighborhood panel view, that clicking in the empty map space to clear the selection takes you to the "no community selected" view. It's not terrible, but I'm not sure where else it should go. /Explore/Neighborhood maybe?￼￼￼￼ 

In other words say you were looking at Astoria and you click an empty space in the map, where would you expect it to go? The neighborhoods list seems more intuitive to me than that no community selected panel. And similarly would do this for counties and census as well. Basically just up one level in the route hierarchy.

Not to add additional work, but I wouldn't mind a clear selection button (like we have in details) in each of the polygon panels when our polygon is selected. So, clicking clear selected button in Astoria would take you up one level to /Explore/neighborhood list, same as clicking an empty space in the map if you are currently looking at a neighborhood instance in the panel.

That's sounding complicated already, but if I can make it generic enough and we stick to our guns on the routing and consistency, seems doable.

## Auto zoom polygon on click
This feels pretty natural and not annoying in the least. Can we just remove that part of the scope about having a toggle at each of the corresponding polygon panels? The only ones I could see it being annoying for are the really big polygons like some of the counties, or when you are zoomed really far out and it zooms you way in on a small neighborhood you clicked. 

Those seem like edge cases though, and since we had the auto zoom with no toggle option before, I say we just continue to roll with that. Consistent and no new cruft in the UI.

I know we have a toggle for auto zoom to full extent on census change, but that's not the same concept since that one is going all the way to the full view every time. ￼￼￼￼￼￼

**Comment by rperlin-ela** [comment]
What you describe here in terms of taking people one level up the route hierarchy sounds promising to me. I’m not sure Clear Selection is such a crucial use case, but I defer to you, sounds like it could be nice.

As for auto-zoom polygon on click, by remove the toggle I take it you mean we just zoom people around whether they like it or not with neighborhoods. Seems probably ok to me.

**Comment by abettermap** [comment]
> As for auto-zoom polygon on click, by remove the toggle I take it you mean we just zoom people around whether they like it or not with neighborhoods. 

correct. we don't offer that option for points, so i could go either way. definitely easier to leave as-is if it doesn't feel choppy.

so here's a new question. i know we want to see popup and zoom and selection _here_:

![image](https://user-images.githubusercontent.com/4974087/113079993-552a7d00-9193-11eb-8fe5-a874ccf37bb5.png)

but what about one level deeper?

![image](https://user-images.githubusercontent.com/4974087/113080041-6e332e00-9193-11eb-92c2-8f13a2a99eb9.png)

i would think not but let me know.

**Comment by rperlin-ela** [comment]
Sounds good.

Yeah if you mean close the neighborhood pop-up once they click on a language profile, not super-critical maybe but that makes good sense. And then open the language pop-up once they click on a specific language community — that sounds smoooth. Nice to be running on routes!

**Comment by abettermap** [comment]
> close the neighborhood pop-up once they click on a language profile, not super-critical maybe but that makes good sense.

well close the neighborhood AND don't highlight the polygon is what i should've said. language profile for that language in that neighborhood doesn't make as much sense to zoom and highlight.

**Comment by abettermap** [comment]
> well close the neighborhood AND don't highlight the polygon is what i should've said. language profile for that language in that neighborhood doesn't make as much sense to zoom and highlight.

This is what I implemented and it feels intuitive to me. No need to respond to this lengthy thread unless there's disagreement!￼
