### ISSUE TITLE
Neighborhoods: separate and de-Boundariesize

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#217]
This is going to affect a lot of things, but I'll try to keep as little in this branch as possible before moving on to census stuff.

## Data
- [ ] add neighborhoods ~~and counties layers~~ **just neighbs in this issue** from our own custom tilesets as separate, distinct layers
- [ ] rm all instances and refs to MB Boundaries, including lookup tables

## Controls
- [ ] ~~below the 2D/3D btn, add a `...` btn that triggers a popout containing the "show/zoom my location" and (for now at least) the Counties toggle.~~ PENDING
- [ ] ~~if needed, include neighborhoods toggle in that menu as well.~~ PENDING
- [ ] ~~either way, add neighbs toggle to /Explore/Neighborhoods and /Explore/Neighborhoods/Something~~ MOVED to #225 

## Behavior
probably won't get ALL the stuff we discussed in this branch, but ~~counties and~~ **JUST COUNTIES in this branch** neighborhoods will ~~both~~ still:

- [ ] zoom to selection on click
- [ ] make bg color of selected polygon stand out symbology-wise from the others
- [ ] popup: just the name for now. bells whistles later.

Can get all fancy with the routing and highlighting in another branch. Big stuff here is just to start using our own layers.

**Comment by abettermap** [comment]
@rperlin-ela i'm just going to rewrite this as neighborhoods-only, then apply a new issue to counties.

> below the 2D/3D btn, add a ... btn that triggers a popout containing the "show/zoom my location" 

can we scrap this? i think it's fine in Search Locations, don't really need another map btn. was mostly to de-clutter w/neighbs and counties toggles in there, but those will be in their own panels now.

> if needed, include neighborhoods toggle in that menu as well.

also scrap, right? 

> make bg color of selected polygon stand out symbology-wise from the others

should counties be same color as neighborhoods? we don't have a legend for either one (and we're not going to in this scope since we didn't have it before, except for upcoming census gradient)

**Comment by rperlin-ela** [comment]
yeah, scrap and scrap. different colors would be nice but no need for legend
