### ISSUE TITLE
Zooming back out from a point

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#218]
Sometimes when zooming in on a point, it pulls you right back out to the default view. @abettermap notes that it only happens if you click on a point or go to it directly like from the URL, and the full data query for the table has not finished loading yet

**Comment by abettermap** [comment]
I'd love to fix this but I can see it being a challenge, and I want to say it was happening before this scope but I'd have to look at code to know for sure. If it was caused by recent work, I'll try to fix, otherwise punting.￼

**Comment by abettermap** [comment]
tried to troubleshoot this but i can't reproduce it consistently. gonna have to punt in this scope anyway, got some other bugs piling up, and this one feels like edge case somewhat, and can't troubleshoot it if i can't make it happen. also pretty sure it happened months ago.
