### ISSUE TITLE
Add info button to Search Languages panel

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#220]
Button text should read "All data, unless otherwise specified, is from the Endangered Language Alliance."

**Comment by abettermap** [comment]
Sorry if I already asked this somewhere, but are we talking about an info button to the right of that search bar? Or some helper text below it? I can whip up the helper text pretty quickly, but I think you're referring to button. Also not crazy hard and still super related to scope, so I'm down for week 4 on this. Just let me know button or helper text.￼..

**Comment by rperlin-ela** [comment]
I would think i button since it’s not 24/7 crucial, but I’m going off your original suggestion ("with my recent style changes to improve space for the Search Languages/locations tabs, we now have room for an ℹ️btn next to each of them, where we could explain some of the many things that could use explaining, without sacrificing space”). but I’m down with any artful way of getting this message in there with Search Langs

**Comment by abettermap** [comment]
for consistency can we have this for omnibox as well? plenty of room now. just looking for something to cover what the heck the search box does and means, especially since it's front and center the first thing users see.

**Comment by rperlin-ela** [comment]
Omnibox = Search Languages panel, no? But yeah I think we’re on the same page

**Comment by abettermap** [comment]
correct. i'm still stuck on omnibox and just running w/it haha

cool i'll get you a UI Text soon.

**Comment by abettermap** [comment]
ah sorry, i misread, i meant an ℹ️  for the _Search locations_ panel.

**Comment by rperlin-ela** [comment]
Makes sense. Put it in UI Text if it’s easy, or I can make it… 

I don’t immediately know the best wording, but probably something like “Searchable locations include addresses, postal codes, landmarks, neighborhoods, and municipalities (NYC area only)"

**Comment by abettermap** [comment]
That's better than what I had probably. Mine is a little more blatant in the lack of counties support though. Since we now have a county/borough deal, I don't want users to accidentally search for one.￼

All yours though, I added the row for you and should have something pushed up shortly along with some other solid fixes.￼
