### ISSUE TITLE
Add wording to Data table

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#221]
Somehow add this text somewhere prominent in the Data table: "All data, unless otherwise specified, is from the Endangered Language Alliance." Possibly could replace Help button in upper right if we feel that's less crucial now with Info panel.

**Comment by abettermap** [comment]
I have to call out of scope on this one, so good move on the wishlist label!

Future Jason is on board with replacing the info button though. Users will survive being able to access Help "only" from pretty much every other view except the table.￼ that and the top of the table is really difficult to work with, or at least trying to make it fit on smaller screens, so my vote is info button.

**Comment by abettermap** [comment]
actually i'm happy to do this since i didn't realize how related it was to the Help stuff we've changed. seems awkward to leave the table now that help is in Info.

**Comment by abettermap** [comment]
the Help btn replacement approach isn't going to fly, that whole top btn area has always been a 💩 -show to work with and i'm not going to fight it again for something like an info popout, so i tried these things:

![image](https://user-images.githubusercontent.com/4974087/113792090-5105de80-9702-11eb-93e9-834b13863cfc.png)

...which looks too small and out of place and just another "thing" in that row.

and this:

which looks good on mid-size and up:

![image](https://user-images.githubusercontent.com/4974087/113793529-be673e80-9705-11eb-8f9b-b8b71048cd49.png)

but breaks everything in mobile.

![image](https://user-images.githubusercontent.com/4974087/113793491-a7c0e780-9705-11eb-82dd-8bbf78984cf9.png)

this is styles JUST for the stuff at the top of the table, not counting the tons of styles for the table itself:

![image](https://user-images.githubusercontent.com/4974087/113793598-e8206580-9705-11eb-99ae-06cb89dc6936.png)

if it looks overwhelming and unintuitive, it is. you can see the frustration in my in-code comments reflected over the months haha.

anyway total nightmare to do anything w/the top and really the table in general has been a constant fight, so just let me know what you want.

oh and the swapping-out of the current Help btn made it really small and weird for some reason (ends up being a btn inside a btn the way i set it up) so i didn't bother with a screenshot.

**Comment by abettermap** [comment]
this sucked the least so i went with it

![image](https://user-images.githubusercontent.com/4974087/113794169-2cf8cc00-9707-11eb-88be-75e834aed5d5.png)

![image](https://user-images.githubusercontent.com/4974087/113794204-3eda6f00-9707-11eb-92d9-5c726b4cbc00.png)

**Comment by rperlin-ela** [comment]
Yep, just writing to that effect, let’s give it a whirl
