### ISSUE TITLE
Anchors only work on second click in Info panel

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#223]
Not sure if this is related to #219 or something else, but for About and Help in the Info panel, which draw on Wordpress pages with anchor links, it seems to require two clicks to get to where the anchor is pointing. The first click briefly seems to go there before returning to the top of the page.

**Comment by abettermap** [comment]
@rperlin-ela i think i fixed this but the only quirk is if you _start_ from an anchored "route", e.g. `/Info/Help#local` then it doesn't auto-scroll and also hides the title bar:

![image](https://user-images.githubusercontent.com/4974087/113631027-0fa00100-9626-11eb-90c6-c721ec1a5a88.png)

i believe this was the case w/the modals as well, so not going to fix in current scope. hopefully edge case anyway but just to mitigate, try not to link to any anchored routes like that from external sources (linking to unanchored things like /Info/Help is still fine though). not sure what "external sources" you'd have haha, but just an FYI.
