### ISSUE TITLE
iPad Portrait: max width for search bars

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#226]
Sorry I lost track of iPad for a bit— I'm guessing this got out of whack when we added the search bar? It looks good and desktop-like on Landscape, but Portrait is doing the mobile thing and putting the panels at the bottom, but not in a good way: search bars and legend extra long on Home, top of the table squished on Data. Hope we can make iPad Portrait go desktop-style.

**Comment by abettermap** [comment]
@rperlin-ela 

Was this not the case always, or it something I broke in this scope? If not then I won't be addressing it in this go-around. Unless you're on one of those monster iPad Pros, the mobile layout is correct. The sidebar is too wide (400-500ish px) to comfortably fit the map alongside it. Granted I have an old iPad Air 2 that's 768px wide or so, but the mobile layout looks fine on there in portrait. Even if you're on a wider device, the sidebar would take up the left half of the screen in portrait mode, leaving only a narrow strip of map left. 

If you can upload a screenshot and let me know what device you're on, and whether or not it's a new thing you're experiencing with the recent changes, we'll go from there.

**Comment by rperlin-ela** [comment]
Will send screenshots separately. Don’t think I have anything to go back to, but I had been checking iPad pretty consistently until SOW 3, and I’m sorry I didn’t check as much across SOW 3. The super long search bars in the panel and sprawling legend are the things that I’m noticing

**Comment by rperlin-ela** [comment]
… and didn’t remember top-line stuff in Data being pushed together

**Comment by abettermap** [comment]
I've been neglecting tablets too. Those 'tweeners are a far less common screen size and they tend to slip through the cracks, Both of those screenshots are how they've always been though. 

There's already 4 breakpoints in the layout, and I agree that things could be improved in iPad portrait, but the 50/50 strip of map to the side would not be a good approach. And the insane amount of overrides I've got going to make the top section of the table look so-so on a range from iPhone SE to large monitors is pretty heavy. 

If you want me to set a max width on the search bar though, that's fair since it's a new addition, and I'll make sure it doesn't get wider than 500ish on any screen size.

**Comment by rperlin-ela** [comment]
Cool, ok, do what’s doable!

**Comment by abettermap** [comment]
Also for the table top part, the margins and padding to make it fit would have to be pretty nickel and dimed to squeeze it in on one line, and it would basically involve creating a custom breakpoint just for the sake of fitting on one line. And with the recent requests for _more_ stuff up top, forget it. Not gonna fit, so wrapping seemed like an easy and clean concession. 

**Fun suggestion:** "Add to Home Screen" on your phone and tablet. Feels like a true app!

**Comment by rperlin-ela** [comment]
Sorry, two more questions on this, which you can check on one of the screenshots I sent: 
-the placement of the mapbox logo and the © Mapbox etc bit, which cover part of the top green bar
-the bottom panel icon bar being wider than the rest of the panel in my screenshot

**Comment by abettermap** [comment]
first one i'll fix. second one ain't hurtin' nobody and i think it's always been like that. any variation of #212 would fix both though, as well as #246 and possibly #139 and possibly #138
