### ISSUE TITLE
Search Locations: increase open list height

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#227]
> One more thing for the Search Locations tab when we get there— unlike with Search Languages (and unlike, I think, how location search used to be back in the bad old "Local" days), only one search result is now visible until you scroll down. Would be great for that dropdown to go on top of other stuff so searchers can see a bunch of options.

__Originally posted by @rperlin-ela in https://github.com/Language-Mapping/language-map/issues/204#issuecomment-811082887__

**Comment by abettermap** [comment]
Yeah I noticed this. The containing element around those tabs when it's toggled on has a maximum height set so that the smooth animation can occur when you toggle it open or closed. I could just make it a regular toggle without a maximum height, but we would lose the smooth open/close.

If I'm able to make it look like it appears above The panel below it, I will do that instead. Seems possible since that's what the omnibox search box does.￼￼￼

**Comment by rperlin-ela** [comment]
Leave the approach to you, but this is definitely important— now I'm not even seeing the top result

**Comment by abettermap** [comment]
yikes, ok i'll try to knock this one out today

**Comment by abettermap** [comment]
good to go i think, the only difference layout-wise is that it "pushes down" the stuff below it, which is a neutral impact IMO and looks fine to me:

![image](https://user-images.githubusercontent.com/4974087/113759251-197f3e00-96d2-11eb-8238-2a2bf28ef94d.png)

to offset that a bit, i also dropped down the results limit to 3 instead of 5 (default). 

cool?

**Comment by rperlin-ela** [comment]
Looks good to me
