### ISSUE TITLE
Restore Gentium

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#228]
I added some checks to remove fonts during local development but looks like it slipped into other environments somehow. Just need to restore so the fonts look right…￼

**Comment by abettermap** [comment]
@rperlin-ela i think i was on the wrong track, nothing to do w/my font stuff, it was actually the markdown conversion thing since i started using that for Details too. 

i think you're wanting this:

![image](https://user-images.githubusercontent.com/4974087/113324739-b60d9e80-92d4-11eb-843f-8315cc7216ab.png)

rather than this?

![image](https://user-images.githubusercontent.com/4974087/113324783-c0c83380-92d4-11eb-93d0-16e0ef751d34.png)

first one is an actual paragraph, which has more line-height. looks easier to read to me, so go with that?

**Comment by abettermap** [comment]
either way, if that's not it, i think the first one looks good so rolling with it unless disagreement!

btw i'm not going to restore my "don't load fonts on local dev" even though that wasn't the problem. the lack of the proper fonts makes it way too different to style anything and work with layouts. lesson learned!

**Comment by rperlin-ela** [comment]
nice, yes
