### ISSUE TITLE
No Community Selected — don't direct people to Home

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#231]
Not sure about best practice here, but ideally now we wouldn't say "Search for a language from Home" and link people there, but instead something like "Search for a language using the 🔎 above". Fix only if easy!

**Comment by abettermap** [comment]
Makes sense. Easy with no icon, and I think we can come up with some wording to cover it.￼

**Comment by abettermap** [comment]
i made this a UI Text record. ;)

FYI i switched all the "/table" routes in code to "/Data". you've won the war of attrition! i'll take a bronze for fighting the good fight, skipping right over silver 🥉 

just make sure to /Data-fy anything in AT

**Comment by abettermap** [comment]
oh and i didn't actually make the requested changes haha, totally forgot. your baby though, and the first of its kind with... a bulleted list!
