### ISSUE TITLE
Neighborhoods panels: auto-zoom on load

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#232]
from #225 

- [x] support auto zoom on initial page load when starting from something like /Explore/Neighborhood/Astoria.
- [x] Share btns if we have to (???). Was my idea in the SOW, but we've also added 1k tasks to it, so my vote is making it optional in favor of the other massive tasks i created for myself. Not to mention it's kinda useless unless i fix the auto-zoom on load.

if i can get auto zoom working on load after A LITTLE more effort, time permitting, i'll do the shares too. already put ages into it though, so probably best later...

**Comment by abettermap** [comment]
@rperlin-ela 

Actually maybe it wouldn't be that bad if I still added the sharing buttons even without functional auto zoom? The popups and highlight are working, as is, most importantly, the cards list at /Explore/Neighborhood/something. 

Thoughts?

**Comment by rperlin-ela** [comment]
I’m going to soup up these Nabe Profiles for all they’re worth, so if you can wire up sharing without too much trouble, still seems like a nice net plus

**Comment by abettermap** [comment]
(for the share buttons, that is)

**Comment by rperlin-ela** [comment]
Totally equivalent if not identical

**Comment by abettermap** [comment]
status: added the Share btns (merged in PR), but kicking this out of this scope since might not figure out the auto-zoom on load issue.

**Comment by abettermap** [comment]
got this working for neighbs, county, census. and show the "selected" style to boot.
