### ISSUE TITLE
Bring Counties back

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#234]
## Data

- [x] Need an Airtable table w/a `name` field at a minimum. **i think everything will come from Maya's CSV derived from GIS and will just be a wholesale upload to create this Airtable table** and will be a one-off. _Maya then Ross_
- [x] Tables using it should point to it (will look into) _Likely Jason_
- [x] ...including the Neighborhood table, which is currently using a Text field for County. yessss more fields, but noooo chances of typos that way. small tradeoff for a new /Explore route ;) _Likely Jason_
- [x] x_min, etc... columns (just making sure to note it, but should be in CSV already) _Maya then Ross_
- [x] MB: either overwrite the existing counties, or start with a fresh Dataset (the latter is preferred but might require 2 uploads since it's likely bigger than the 5MB max upload size) _Jason or Maya_
- [x] an entry in the Airtable `Schema` table (_Ross_)

## UI
(all Jason unless noted)

- [ ] Layer toggle in /Explore/County, just like we have for 'hoods
- [ ] need a County icon _Ross, the icon master_ `CgTrees? RiGovernmentLine?`
- [ ] establish where/how we mention that boroughs are included _Ross_
- [ ] please no chip. too many chips.
- [ ] new color for counties polygons
- [ ] wire up map clicks to trigger route _Jason_
- [ ] column in table (hidden, only added for Searchability), and rm Description 🤩 
- [ ] what else? _Ross_

**Comment by rperlin-ela** [comment]
All sounding good. I think I've done what I can on the Data end, but let me know if not. Will make sure the borough thing is clear. Icon-wise, oh man that's a tough one. CgTrees? RiGovernmentLine?

This will be a hidden column in the Data table, right? I think an important use case is people filtering the map for all the languages of Queens or Brooklyn, for example— that's why I started with the parentheses— so I want that back in some form. I'm not sure if people would be more likely to use the top search bar or Location for that. It may be hairy given how often Queens, Brooklyn etc. are mentioned in Descriptions, so I guess a fallback is always to... add another column.

**Comment by abettermap** [comment]
> All sounding good. I think I've done what I can on the Data end, but let me know if not. 

just add Middlesex-CT back please. it's like 15 minutes of work for me or a couple seconds for you.

> Will make sure the borough thing is clear.

where? at the top of /Explore/County i imagine?

> Icon-wise, oh man that's a tough one. CgTrees? RiGovernmentLine?

cool, i'll add it to the issue and look later.

> This will be a hidden column in the Data table, right?

news to me, first time you've brought it up, and it sounds like there's an assumption again that i'll just do everything asked of me, hard to tell though. not sure how this scope somehow creeps into such size. i'll make a point to never suggest anything again ever, ha!

> I think an important use case is people filtering the map for all the languages of Queens or Brooklyn, for example— that's why I started with the parentheses— so I want that back in some form. I'm not sure if people would be more likely to use the top search bar or Location for that. It may be hairy given how often Queens, Brooklyn etc. are mentioned in Descriptions, so I guess a fallback is always to... add another column.

if we added County (hidden) to the table, could we conceivably axe Descriptions from the table search? it's honestly like 500kb on page load, every single time, just for that field. it's a disproportionate amount of data relative to the rest of the app, for something that may or may not get used (i think i've used it like 3 times, ever). if i recall, the use case was to find boroughs mostly, right? if so, then County would accomplish this?

**Comment by abettermap** [comment]
@fiddleHeads do you have any colors that work well in your other maps for polygons? we could use a different color for counties to make them stand out from neighborhoods. maybe a blue or something?

if so, these are the properties i'd need:

```
fill-color
fill-opacity
line-color
line-opacity
```

if not, no worries, i'll figure something out.

**Comment by rperlin-ela** [comment]
> just add Middlesex-CT back please. it's like 15 minutes of work for me or a couple seconds for you.

Done

> news to me, first time you've brought it up, and it sounds like there's an assumption again that i'll just do everything asked of me, hard to tell though. not sure how this scope somehow creeps into such size. i'll make a point to never suggest anything again ever, ha!

We emailed about this two weeks ago. I asked, "Would there still be a way to filter in the Data table without adding yet another column? That was one of my motivations in the first place [for adding boroughs in parentheses]" And you wrote "via the "Search..." at top. that will pick up hidden field results (like with Description)".

> if we added County (hidden) to the table, could we conceivably axe Descriptions from the table search? 

That's fine, we can axe

**Comment by abettermap** [comment]
Sorry, I must've forgotten that conversation, it's sounding only vaguely familiar. But removing descriptions is the sweetest possible deal I could ask for, so sign me up!￼

It's actually being "used￼" by the second column of the table, The one where you click for more details, but I'm pretty sure I could use just about any other column for that, including county…￼￼

Will county be included and populated in the airtable￼ Data table? I think it would have to be because there is no county Column in the Town table, only Neighborhood table, so we can't steal it via link, lookup, formula approach.

**Comment by fiddleHeads** [comment]
> @fiddleHeads do you have any colors that work well in your other maps for polygons? we could use a different color for counties to make them stand out from neighborhoods. maybe a blue or something?

What do you two think about this?

![image](https://user-images.githubusercontent.com/65880816/113327771-35e53a00-92d0-11eb-9db4-82c950a4a09b.png)

> 
> if so, these are the properties i'd need:
> 
I'm not sure where to get these exact properties. I can provide the HEX # for RGB (HEX # D6E9F2 for fill, HEX # 9EBBD7 for line) or the percentages of the different colors for CMYK, or percentages of hue and saturation for HSV.
> ```
> fill-color
> fill-opacity
> line-color
> line-opacity
> ```
> 
> if not, no worries, i'll figure something out.

**Comment by rperlin-ela** [comment]
Looks good to me

**Comment by rperlin-ela** [comment]
> Will county be included and populated in the airtable￼ Data table? I think it would have to be because there is no county Column in the Town table, only Neighborhood table, so we can't steal it via link, lookup, formula approach.

Sure, it can. But I'm going to need your help or gudiance in getting you exactly what you need in AT. I did put a County column in Town. Tho whatever the issue was last night with County in the Neighborhood table, maybe an array thing, I assume the same thing would apply to the Town table.

**Comment by abettermap** [comment]
Thanks Maya, that's enough to get me started. I usually think of blue as water, but kinda depends on the basemap and context, so I'll use yours as a starting point and adjust as needed.

> Sure, it can. But I'm going to need your help or gudiance in getting you exactly what you need in AT. 

I'll set it up for you.

> I did put a County column in Town. Tho whatever the issue was last night with County in the Neighborhood table, maybe an array thing, I assume the same thing would apply to the Town table.

yep, pretty much need a link/lookup/formula whenever we're after a single text value like this. the multi-things like Macrocommunity (or whichever chip supports multiple) do not need the formula.

or, similarly like i did yesterday, the array worked in my favor. for /Explore/Neighborhood/Something, to populate the card footers w/descrips, i just linked from Neighborhood table (already had a link actually), then just needed a lookup field to get an array of endos and descrips. voila.

**Comment by abettermap** [comment]
> I'll set it up for you.

@rperlin-ela County stuff is all set in Town, Neighborhood, and Data tables. didn't need a lookup after all for first two, my mistake, just link + formula. and 2 lookups + 1 formula in Data. could be worse!

**Comment by fiddleHeads** [comment]
> Thanks Maya, that's enough to get me started. I usually think of blue as water, but kinda depends on the basemap and context, so I'll use yours as a starting point and adjust as needed.
> 
Happy to play around with another clue. You had suggested some kind of blue, so that's what I went with. This is like a blue-grey. Let me know if you'd like some other options.

**Comment by abettermap** [comment]
Ha thanks, I thought of the water thing after I suggested blue. Wait, so those are lakes?? ...is my usual reaction. But I think your blue-grey could work!

**Comment by abettermap** [comment]
@rperlin-ela i'm sure you're well aware of the annoyance that is county-vs-borough distinction, so if you can think of any clever ways to mitigate (aside from renaming the "County" table and all "County" fields), i'm semi-open.

![image](https://user-images.githubusercontent.com/4974087/113443633-9c8d5500-93af-11eb-8a9a-8ff434b364eb.png)

for starters, could just say "show **features** in map" or something. or show boundaries, or polygons, or layer. anything to make it generic and not add another spot where "counties" is inaccurate.

**Comment by abettermap** [comment]
i wired this up but didn't commit yet. just don't want to create additional confusion:

![image](https://user-images.githubusercontent.com/4974087/113444195-a2376a80-93b0-11eb-9ade-2bb9259093ca.png)

but if it's fine then let's borough in.

**Comment by rperlin-ela** [comment]
All in all I don't care (and would probably prefer) if we never use the
word boroughs anywhere and just call them all counties. If we can get away
with that toggle that says "Show counties and boroughs in map", that's nice
(tho not essential). And I don't expect boroughs to be mentioned anywhere
else.

The only difference I see is the back-end one that borough-counties are
tied to Neighborhoods and county-counties are tied to Towns. I'm just back
on AT, but it looks you're doing some fancy footwork in the last column of
the County table?

**Comment by abettermap** [comment]
if this is fancy then yes :)

```
CONCATENATE(
  ARRAYJOIN( ARRAYUNIQUE({Languages from Neighbs}), ", "),
  ARRAYJOIN( ARRAYUNIQUE({Town languages (lookup)}), ", ")
)
```

so so gross. it's the only one in all of AT that i can't make into an array, so i do it in the code. not sure how else to do it though. 

so run with "Show counties and boroughs in map" then? or just counties?

**Comment by rperlin-ela** [comment]
Either is good by me. Maybe just “Counties” for consistency, if Boroughs are not going to mentioned anywhere else? I’ll write something about it in UI-text

**Comment by abettermap** [comment]
Sounds good. no boroughs mention except your `The entire 31-county tri-state area (including the 5 counties aka "boroughs" of NYC)`. shouldn't be any in the code.

**Comment by abettermap** [comment]
removing the Descriptions from the table in the app cut the size of the full Data query for the table almost exactly _in half_

 📉  🎉  📉  🎉  📉  🎉 

searched for "brooklyn" as a test and it's picking up borough and Brooklyn Heights, so seems to be working. haven't pushed yet so you'll have to test in the next push
