### ISSUE TITLE
Layer toggles: improve availability

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#237]
this is sprinkled in places like #236 and #234 but the TLDR is to do something like this:

![image](https://user-images.githubusercontent.com/4974087/113466125-7fc84000-93f6-11eb-927e-032eff32d56d.png)

to trigger:

![image](https://user-images.githubusercontent.com/4974087/113466164-d6357e80-93f6-11eb-80dc-943615af2144.png)

**Comment by abettermap** [comment]
@rperlin-ela  

- do we need the ℹ️  for show my loc?
- we have room for a smaller version of the heading + helper text like we use in Info:

![image](https://user-images.githubusercontent.com/4974087/113466216-26144580-93f7-11eb-803d-ddf1d33e0d47.png)

so, include any of that? the ℹ️  just looks a little silly in this context, so i was thinking 

- neighborhoods toggle has helper text mentioning the data source
- ...as does counties toggle, and/or it could include boroughs mention
- the "show/zoom my loc" helper would simply use the current contents of the ℹ️  btn

## Heading

also, and i know you're not as big a heading fan as i am, but we certainly have room for a `Map Tools` or something (even if we use helper text). here is heading without helpers on toggles (and the menu doesn't need to be this wide):

![image](https://user-images.githubusercontent.com/4974087/113466370-8b1c6b00-93f8-11eb-941f-428dac05b29e.png)

yay or nay, and **if yay then what text**? i'll use it for the hover tooltip on the button as well.

## "X" close btn

could probably use on of those, yeah?

## Things you'll like

the convenience and placement of this approach. i've only been testing it for a few minutes, but supa smoove, especially on mobile.

**Comment by abettermap** [comment]
last thing. do we still need this toggle?

![image](https://user-images.githubusercontent.com/4974087/113466446-29103580-93f9-11eb-8acd-c3a4ae5a4bbd.png)

you can answer after you've experienced the glory that is the layers menu yourself, but it feels unnecessary now, and always felt "off" to me anyway. this level still fine though:

![image](https://user-images.githubusercontent.com/4974087/113466462-46450400-93f9-11eb-8c74-c4f9dd109931.png)

**Comment by rperlin-ela** [comment]
> so, include any of that? the ℹ️ just looks a little silly in this context, so i was thinking
> 
> * neighborhoods toggle has helper text mentioning the data source
> * ...as does counties toggle, and/or it could include boroughs mention
> * the "show/zoom my loc" helper would simply use the current contents of the ℹ️  btn

no ℹ️ and every toggle gets a little helper text if possible sounds good to me.

- "show/zoom my loc" helper as you say
- neighborhoods toggle as you say that old bit of text (mention NYC-only and data source).
- for counties could be something like "The entire 31-county tri-state area (including the 5 counties aka "boroughs" of NYC), as defined by NYC's Department of City Planning and other sources"
 
> ## Heading
> also, and i know you're not as big a heading fan as i am, but we certainly have room for a `Map Tools` or something (even if we use helper text). here is heading without helpers on toggles (and the menu doesn't need to be this wide):
> 
> ![image](https://user-images.githubusercontent.com/4974087/113466370-8b1c6b00-93f8-11eb-941f-428dac05b29e.png)
> 
> yay or nay, and **if yay then what text**? i'll use it for the hover tooltip on the button as well.

Are we also going to have "Hide Census data" toggle here?

Heading is not a bad idea but "Map tools" and "Show map menu" feel too vague. Not sure but how about something like "Layers & Settings"?

> ## Things you'll like
> the convenience and placement of this approach. i've only been testing it for a few minutes, but supa smoove, especially on mobile.

Loving the whole thing. I see what you mean about that toggle at Explore/Neighborhood, and I guess you feel the same way about Explore/County— I could go either way, fine disposing

**Comment by abettermap** [comment]
Just pushed some super tasty nuggets for ya 😉  🚀 

Helper text for all four of the things in that menu are yours to do with as you wish in `UI Text` table. I don't have markdown conversion set up on those though, so no Rich Text please. I don't think any of the stuff in the menu is so complex that it needs a link, so maybe just do the writeup in Help if you need it. And things like italics and bold are probably overkill for the helpers. You can get away with `SOURCE: ...` in all caps if needed.

Holler if it's not the case. Otherwise let's merge this puppy!

**Comment by abettermap** [comment]
I should point out that the caveat of adding the basemap switcher is that i'm not going to do any style tweaks for it, hence the disclaimer. with ONE exception being the map labels color in Dark and None mode. if i just swap that to white for Status and Size, it would be legible. everything else is sufficient for reading at least.

speaking of Dark mode, @fiddleHeads i think your counties colors look positively badass against the dark bg:

![image](https://user-images.githubusercontent.com/4974087/113490946-93bd8180-948a-11eb-909c-0c2d49c5f422.png)

**Comment by abettermap** [comment]
> Are we also going to have "Hide Census data" toggle here?

sorry @rperlin-ela i forgot to reply and to add it...

it's not going to be a toggle because we don't have a toggle for it elsewhere. not quite the same concept as neigbs n counties. so best i can do without it getting complicated is the "clear" functionality identical to the Census popup. will get it in another branch though, just want to merge this guy first.

**Comment by rperlin-ela** [comment]
Tasty! Basemap beauty! Mark will swoon. Good disclaimer, totally. No need for markdown for that helper text, either. 

Merge away!

**Comment by abettermap** [comment]
ha i thought Mark was anti-dark with the doomsday video game darkness comment! 🌑   maybe that was for the all-dark UI though, so valid point there.

merging...
