### ISSUE TITLE
Census: remaining tweaks & fixes

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#242]
...excluding the #207 stuff. 

- [x] Fix census popup text (show pretty name, not field name)
- [x] White search box like omni? would stand out much better amidst the paragraphs, and promote UI consistency.
- [x] Census popout: "view in map" goes to /Census but shouldn't it just close the popout rather than change pages?
- [x] "Clear census" link in map menu: still doing this even though it's not a toggle? seems intuitive enough in census popout so that's my vote. If including, where? below "show/zoom my loc" helper and above basemap stuff? does it need helper text? hopefully not, it's getting a little busy in the menu and "clear census XXXXX" seems sufficient if we have a good XXXXX, like _______________ 
- [x] Census dropdown: can we have smaller group headings for puma and tract? there's a lot going on in there with all that text (takes up a serious amt of space on mobile) and it seems like with all the new text in the panel we should be able to explain what the group headings currently explain, but above or below the dropdown?
- [x] Fix hover issue which causes census poly's to oil-spill
- [x] Include Ross's new top/bottom UI text in Census panel

**Comment by abettermap** [comment]
@rperlin-ela i think i know enough answers to get started, but let me know when you have a chance

**Comment by rperlin-ela** [comment]
Will take a look but tied up so probly not till tonight

**Comment by rperlin-ela** [comment]
An excellent list — I think I agree with all of it.

> * [ ]  Census popout: "view in map" goes to /Census but shouldn't it just close the popout rather than change pages?

Good call.

> * [ ]  "Clear census" link in map menu: still doing this even though it's not a toggle? seems intuitive enough in census popout so that's my vote. If including, where? below "show/zoom my loc" helper and above basemap stuff? does it need helper text? hopefully not, it's getting a little busy in the menu and "clear census XXXXX" seems sufficient if we have a good XXXXX, like _______________

Right on

> * [ ]  Census dropdown: can we have smaller group headings for puma and tract? there's a lot going on in there with all that text (takes up a serious amt of space on mobile) and it seems like with all the new text in the panel we should be able to explain what the group headings currently explain, but above or below the dropdown?

Makes sense. It's good now, but I could see that it would probably be work if I can just work in the secondary text for both tracts and PUMAs somewhere in the the rest of the text.

**Comment by abettermap** [comment]
Sounds good. 

> we have a good XXXXX, like _______________

I was hoping you'd fill in the blank there. ;)

**Comment by rperlin-ela** [comment]
XXXXX sometimes marks the spot, but my brain is a little fried right now and I'm stumped. The Clear Census button in the pop-out is a good model— disabled unless a census layer is on, right? Don't think it needs helper text. Could even just be "Clear Census", no? I guess "Clear Census Language Data" or that kind of that is better, if longer. Or do you mean dynamically filling in depending on what language layer is on?

**Comment by abettermap** [comment]
> I guess "Clear Census Language Data" or that kind of that is better, if longer

ok i'll run with that, but if there's any requests to change it then it's going into **UI Text** table in AT. the wording stuff is kinda draining and it derails progress on my end so it's worth the few minutes to wire it up and put the ball in your court!

> Or do you mean dynamically filling in depending on what language layer is on?

no, nothing crazy like that, just the wording of the text 24/7.

> Fix census popup text (show pretty name, not field name)

i can't reproduce this except on page load, like if i go to `/Census/puma/F3113__Panjabi/3604105` then hit refresh, it happens. but i can't make it happen in the UI otherwise. are you experiencing it?

**Comment by rperlin-ela** [comment]
I hear you — trying my best! But definitely slam anything you like into UI Text.

With census pop-up yeah: I click a point on the map, click the census pop-out, then click on one of the PUMAs or Tracts and I get the non-pretty name. Going via Omnibox it’s the same, mobile or destkop. Doesn’t happen to you — or am I misunderstanding?

**Comment by abettermap** [comment]
so i tried this flow just now:

1. fresh load from Home
2. Click Census nav btn
3. Click search box
4. Click Urdu
5. Click a map polygon

result: 

![image](https://user-images.githubusercontent.com/4974087/113528193-1fafd600-957d-11eb-9b24-c7a42c21a8d2.png)

not the case for you?

**Comment by abettermap** [comment]
OH from the popout. nvm i got it, will fix

**Comment by rperlin-ela** [comment]
Sorry maybe I’m mixing up pop-out and pop-up. From Census panel, totally, there’s no problem, I’m talking about the Census chip in Lg Profile or Details. It’s when I go via that route.

**Comment by abettermap** [comment]
no i gotcha, i'm getting it too, will just have to hit AT Schema table to grab the pretty name. easy fix.

how's this for map menu?

![image](https://user-images.githubusercontent.com/4974087/113529392-8256a100-9580-11eb-820c-f5769cea485f.png)

**Comment by rperlin-ela** [comment]
I dig. View options just takes you to Census panel I assume

**Comment by abettermap** [comment]
affirmative

**Comment by abettermap** [comment]
i dropped the bold on "Census data:" is all. stands out too much.

**Comment by abettermap** [comment]
actually i'm feeling the View options link first since it will be enabled always, whereas Clear selection makes it harder to identify that both of those links pertain to Census:

![image](https://user-images.githubusercontent.com/4974087/113529781-a2d32b00-9581-11eb-97ec-cc45b743bad0.png)

**Comment by rperlin-ela** [comment]
Looking good

**Comment by abettermap** [comment]
gonna have to throw in the towel on the selected census feature highlight. i got it to work but it oil spills everything else:

![image](https://user-images.githubusercontent.com/4974087/113535198-02383780-9590-11eb-8876-e9db55dd16f6.png)

super complicated, hard to explain, got an hour into it and just not worth it. we'll have to settle for the dynamic fill colors and auto-zoom and popup on click.

not sure there's a one-size-fits-all highlight color for the census layers anyway since their fills are so dynamic, where as counties and neighbs are same 24/7.

i did find simple ways to make the highlighted feat stand out on those though:

![image](https://user-images.githubusercontent.com/4974087/113535340-5b07d000-9590-11eb-9396-adda49070ed5.png)

**Comment by abettermap** [comment]
ok i think i'm all set on census stuff except for #207 which i'll get tomorrow.

pushed my other stuff though, give it a look. more info in commit log.

**Comment by abettermap** [comment]
If you'll consider shorter group headings for census dropdown let me know, they take up about 20% of the available vertical space on my phone, and it's not a very small phone. 

![image](https://user-images.githubusercontent.com/4974087/113538531-10db1a80-95a1-11eb-81cd-a1a92081a305.jpeg)

**Comment by abettermap** [comment]
This seems to sum it up enough and you can elaborate more about which one is used when available in your paragraphs maybe?

![image](https://user-images.githubusercontent.com/4974087/113538707-88a94500-95a1-11eb-9acd-11106b4e62a8.jpeg)

**Comment by rperlin-ela** [comment]
Perfect, sure

**Comment by abettermap** [comment]
cool. i gave you two more UI Text rows just in case ;)

**Comment by abettermap** [comment]
found a quirk about how i'm calculating the "center" of a polygon based on its bounds corners:

![image](https://user-images.githubusercontent.com/4974087/113603707-7eb72e80-9601-11eb-871d-a98b03d29bc7.png)

it's just doing its job here, but the popup is actually referring to the larger polygon, not the lil guy in the middle. it's definitely in the center of the big one, but also... the little one. i don't think there's an easy fix for that one, so just pointing it out.
