### ISSUE TITLE
Panel titles: show for all views

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#251]
It's annoyingly inconsistent to see some blank headings (and the lack of plurals mentioned in #204), so i'd like to see something for all of them, e.g.

![image](https://user-images.githubusercontent.com/4974087/113798783-135c8200-9711-11eb-9497-6e0011121824.png)

![image](https://user-images.githubusercontent.com/4974087/113798927-54549680-9711-11eb-9028-2784531ff28f.png)

actually i think those are the only two we're missing?

**Comment by abettermap** [comment]
@rperlin-ela are these the only two views which don't have panel titles? 

and if i wire this up, are these the names you'd want to use? i want to keep it generic because i have might doubts about many of the language names, for example, fitting on mobile (or even close to it). plus we already have a nice layout which includes the language name below the endo. the `...` truncation on mobile would also get annoying for long names and take more work to wire up.

**Comment by abettermap** [comment]
> are these the names you'd want to use?

...as in Language Profile and Community Profile.

**Comment by abettermap** [comment]
(picking up also where we left off in https://github.com/Language-Mapping/language-map/issues/250#issuecomment-814541503)

**Comment by rperlin-ela** [comment]
I know what you mean about the blank headings being confusing, but I feel like we'd have to do this for every Explore/Something if we actually wanted to be consistent. So not just Language Profile and Community Profile, but also Neighborhood Profile and Macrocommunity Profile and all that, and things like the latter are just lists of cards, "profile" doesn't feel right in any case... Starts to feel like overkill, and reminds me why your idea about going just two levels deep in the first place made some sense.

It would probably make more sense to kick the headings upstairs to the green, but I understand that some of the names would be long, and also lots of complications with subheds like the boroughs or endonyms...

**Comment by rperlin-ela** [comment]
Or were you thinking of kicking all the others upstairs but then just labeling Language Profile and Community Profile?

**Comment by rperlin-ela** [comment]
Side issue, but what do you think about changing "Languages of NYC" to something like "Language Sites of NYC"? On the one hand I don't want to be confusing and inconsistent with our map title; on the other hand, we've already shortened to NYC (to fit on mobile?) and maybe don't need to be redundant anyway, and this could be a high-visibility way to address the issue raised by Ben and others that what we're really mapping with ELA data are the sites.

**Comment by abettermap** [comment]
i didn't reply to your other part, i just pushed what i had, looks great to me but let me know what you think. hard to close some of these issues because we have so many bulleted checklists, so they're like half closed. 

> Side issue, but what do you think about changing "Languages of NYC" to something like "Language Sites of NYC"? 

ha you know my take on it. the heading should describe what the panel contains like the rest of them do (e.g. _Search and Display_ or _Search Language Sites_ , and the inconsistency is a little misleading (and the blanks jarring, which i fixed in my push, so hopefully we can keep).

> on the other hand, we've already shortened to NYC (to fit on mobile?) 

not sure what you mean. instead of New York City? yeah i suppose, although it might fit now.

> and maybe don't need to be redundant anyway

yeah i feel like the logo covers it and the panel title should be dedicated to describing what's below it.

> and this could be a high-visibility way to address the issue raised by Ben and others that what we're really mapping with ELA data are the sites.

understandable, and up to you, but i don't think the panel title is going to fix a large concept like that. i still think people aren't going to understand full what the map represents without reading Help/About. i do think our little bits and blurbs and info btns are a good second-line defense sprinkled throughout the app though. small pieces of info to digest as a supplement to the full-on About, and more descriptive than relying on headings to describe the big-big concepts.

i get what you mean though, and i'll put whatever you want, and i'll get to those other issues next, i'm just thinking as a user i'd like to know what each panel is for based on its title, including Home.
