### ISSUE TITLE
Classic call-to-action (CTA) button

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#256]
Quoting @abettermap email: "if we bring in my new desktop layout, it could go in the bottom right side where i stuff those other btns. maybe a popout from there with the donate/join wording (via UI Text of course!). using current layout though, i'd probably stuff it at the top of /Info above About. would just be an intro-ish thing like the other panels, followed by a bigger CTA btn (or btns plural if you have a Donate link)."

"Get Involved"? "Support the Work"?

Top of /Info doesn't immediately feel ideal, but definitely not the worst, and maybe good if it's different-looking and button-y...

**Comment by abettermap** [comment]
> "Get Involved"? "Support the Work"?

regardless of where I put them, where￼ should these things lead? External website? Nested route/s inside /Info?￼ Automatic PayPal deduction? 🤑

**Comment by abettermap** [comment]
Happy to do this if it's easy, just need a little more guidance￼ on what's required.

**Comment by rperlin-ela** [comment]
Yep, I’m just thinking on my feet here… but my instinct is maybe that the button just does some kind of popout or modal where I can write a little UI Text message, like 3 or so sentences. Two main CTAs would be to donate (and get a print map) to support further development— good if I could link to an ELA page— or else something like “start one in your city” which could contain a link for them email us ***@***.*** ***@***.***>) ?

**Comment by abettermap** [comment]
Yeah we can modal it. Just wondering how putting the trigger button into somewhere useful on mobile would work anywhere but inside a panel. Taking up map real estate 24/7 with a bright button when less than half the screen is available for map interaction... Seems like it could have the opposite effect and turn people off on smaller screens.

I feel like info panel would be a pretty frequent destination for people. So still leaning towards the top of that with some nice buttons leading to modal if that works?

Open to ideas but how about you create the text in UI Text first and I'll get a feel for it that way?

**Comment by rperlin-ela** [comment]
Ok, your call, top of info could work, just made the UI Text with some very quick and dirty bits — bulleted, which may not be the right vibe but anyway

**Comment by abettermap** [comment]
the approach i used is based off a list being in your UI Text and it's pretty fragile style-wise. it just assumes a paragraph and list to be in there like you have. welcome to try other markup in there, should still work, but just FYI'ing that that's what the style is on.
