### ISSUE TITLE
Wording changes: nav, menus, titles

### ISSUE THREAD

**Issue by abettermap** [Language-Mapping/language-map#260]
- [x] change "Community details" in the timeline breadcrumbs to "Site Details"?
- [x] we generally are capitalizing top-level header text, so maybe also "Map options" > "Map Options"
- [x] change Explore panel title to "Explore ELA Data"?

_Originally posted by @rperlin-ela in https://github.com/Language-Mapping/language-map/issues/258#issuecomment-816687378_

**Comment by rperlin-ela** [comment]
Also "No site selected" to "No Site Selected"

**Comment by abettermap** [comment]
> Also "No site selected" to "No Site Selected"
>
> Would also be great, on that page, to change "Show me a community" button to "Take me to a site"

shoot i missed these because they weren't in the issue. if you add stuff please just edit the issue so i don't have to skim through comments. the issue body is what i check before pushing/requesting, too easy to lose stuff if it's all in the threads.
