### ISSUE TITLE
External links now broken?

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#264]
I think there may be a new issue with all external links resolving locally. See the "Read more here" at https://languagemap.nyc/Explore/Language/Sicilian/1007 or https://languagemap.nyc/Explore/Language/Wakhi/1205 for examples. Also from the Data table.

_Originally posted by @rperlin-ela in https://github.com/Language-Mapping/language-map/issues/261#issuecomment-818062720_

**Comment by abettermap** [comment]
i think the only way i'll be able to make this work is if the relative (internal) links are consistent. not sure how we/you normally enter them but i just did a test with:

```
/Info/About
```

...exactly like that, as the URL when i highlight the word Test and paste that text in:

![image](https://user-images.githubusercontent.com/4974087/114480893-a89fc080-9bc0-11eb-9325-d4112d5b5bb8.png)

this comes back as i expect in the browser:

![image](https://user-images.githubusercontent.com/4974087/114480749-66767f00-9bc0-11eb-882d-b8870946697a.png)

...which is total garbage, but it's _consistent_ garbage that i can work with.

i confirmed this is how i did it in the `none-selected` AT text as well:

![image](https://user-images.githubusercontent.com/4974087/114481079-0e8c4800-9bc1-11eb-96ff-fcc0d669ccfd.png)

so just make sure your internal links are like that, and i'll treat the normal links as external. those ones i don't think we have any way for you to specify if they should open in a new tab, so i'll just make them all do that.

i also noticed both the links are bad (in different ways) in `explore-intro` in UI Text, so might want to fix those.

**Comment by abettermap** [comment]
oh and i've seen a few like `/info/About` when the route is actually `/Info/About`. again, best way to get it exact is just copy it from the actual URL.

the only route i've changed is `/table` to `/Data` but all the rest should be `/Something` capitalized first letter.

**Comment by abettermap** [comment]
my guess on the explore-intro is that there wasn't a slash at the beginning:

![image](https://user-images.githubusercontent.com/4974087/114481951-e867a780-9bc2-11eb-84c8-35f126af68b7.png)
