### ISSUE TITLE
Scroll-to-top 24/7 on mobile only?

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#266]
I take it there's no way just to have "scroll-to-top" 24/7 on mobile? I know I seconded you on 24/7, but maybe would just go back to how it was yesterday, working 98%

_Originally posted by @rperlin-ela in https://github.com/Language-Mapping/language-map/issues/261#issuecomment-818062720_

**Comment by abettermap** [comment]
So I think I finally figured out the source of the problem, which was the thing I was using to try and animate the panels between route changes. I've never been able to get that very smooth anyways so I just gutted it and, even before that today, went to town on some smaller piecemeal animations.

I think it looks stellar, you'll see it in my next push, hope you dig! If any of the intro sections are too much, I can crank it down or just not animate them, but it feels smoother than the janky all-or-nothing loading we have now. ￼
￼
